* Residuals :noexport:

Recently,  textcite:arestis_residential_2015 update \citeauthor*{poterba_tax_1984}'s citeyear:poterba_tax_1984 framework by estimating an autoregressive distributed lag (ARDL) model for 17 OECD countries.
In summary, they conclude that residential investment depends mainly on disposable income.
This result would  question the possibility of treating housing as an autonomous expenditure and jeopardize the analysis from the Sraffian supermultiplier perspective.
However, with regard to the US they report that real house prices and the volume of banking credit are the main determinant of residential investment.
Therefore, this result allows considering housing as a non-capacity creating autonomous expenditure.
Although the macroeconomic relevance of residential investment is not restricted to the US, most scholars have examined this specific case.

No entanto, a literatura macroeconômica sobre determinantes do investimento residencial ainda é escassa. Como apontam Arestis e Karakitsos (2008), para o caso dos EUA, nosso país de interesse, a literatura tradicional trata US housing market como segmentado, usando um abordagem de mercados regionais, por regiões metropolitanas.
, Como apontam Arestis e Gonzalez-Martínez (2014), a literatura sobre preços de imóveis é muito mais extensa do que a literatura sobre investimento residencial. E mesmoa


of residential investment. It worth noting that this variable is much less studied than housing prices (Arestis
econometric papers that includes residential investment has failed to treat it macroeconomically, restricting it to microeconomic and regional issues (arestis; karakitsos, 2008).
Although the macroeconometric relevance of residential investment is not restricted to the US, most scholars have examined this specific case. In this context, we analyze the macroeconometric literature that explicitly includes housing to evaluate the determinants of its growth rate.

After the US housing bubble burst, there have been a growing attention in the macroeconomic implications of residential investment.
It worth noting that most econometric papers that includes residential investment has failed to treat it macroeconomically, restricting it to microeconomic and regional issues cite:arestis_u.s._2008.
In this context, we analyze the macroeconometric literature that explicitly includes housing to evaluate the determinants of its growth rate.

Others scholars analyzed the investment (residential and non-residential) to depict the determinants of the business cycle.
textcite:green_follow_1997, for example, estimates which investment Granger-causes GDP tests for the US from 1952 to 1992 and reports that residential investment leads --- more than firms' investment --- the business cycle.
However, he argues that this result does not imply a causal relationship:

#+BEGIN_QUOTE
[P]erhaps residential investment, like stock prices and interest rates, is a good predictor of GDP because it is a series that reflects \textbf{forward-looking behavior}. Presumably households will not increase their expenditures on housing unless they expect to prosper in the future. Building a house is a natural mechanism for doing this. Thus, the series can do a good job of predicting GDP \textbf{without necessarily causing GDP} \cite[p.~267, ephasis added]{green_follow_1997}.
#+END_QUOTE


Despite paying attention to a non-capacity creating autonomous expenditure, textcite:green_follow_1997, restricts its relevance as temporal precedence indicator.
textcite:leamer_housing_2007, on the other hand, reports a causal relationship between housing and GDP.
In summary, states that residential investment implies a higher durable goods consumption, that is, the US business cycle is a ``consumer cycle''.

Alternatively, textcite:huang_is_2018 assess both \citeauthor*{leamer_housing_2007}'s \citeyear{leamer_housing_2007} hypotheses related to residential investment (prediction and causality).
To do so, they estimate a Structural Vector Autoregressive (SVEC) model with wavelets transformation for the US and G7 countries.
They find residential investment is not only a monetary policy transmission channel, but it also has temporally distinct effects on business cycle.
In the short-run, housing is more predictive while house prices have a bigger influence in the long-run[fn::
	More precisely, textcite:huang_is_2018 also conclude that residential investment prediction increases with its share on GDP.
	].
These distinct temporal influence of housing occurs due to the large wealth effect in the long-run while credit and collateral effects are more relevant in the short-run.
Regarding the causal relationship described by textcite:leamer_housing_2007,
textcite:huang_is_2018 report inconclusive results for all countries due to their institutional heterogeneity[fn::
However, textcite:huang_is_2018 claim that for most G7 countries, residential investment at least amplify the business cycle.
], but remains valid for the US.
Despite the inconclusive results on fluctuations, they find that housing related variables (house prices, real mortgage rate --- deflated by a general price index --- and bank spread) lead the business cycle.

In a recent paper, textcite:wood_house_2020 evaluate the relationship between economic growth, household indebtedness and house prices.
To do so, they estimate a ARDL model for 18 OECD countries from 1980 to 2017 and report that house prices determine household indebtedness which is central to describe recent economic growth rate.
Despite shedding light on the macroeconomic relevance of real estate, their model does not include both residential investment nor mortgage interest rate.
As discussed before, other scholars have found statistical significance for those variables to determine housing cite:gauger_residential_2003.



As we have seen in the previous session, there have been a growing attention to the macroeconomic implications of housing.
However, most of this literature treat housing-related variables in a microeconomic and regional fashion.
According to textcite:arestis_u.s._2008, the US housing market in particular is quite heterogeneous.
As a consequence, most econometric papers do not analyze residential investment in macroeconomic terms, restricting it to regional and metropolitan issues cite:arestis_u.s._2008.
Additionally, if the housing macroeconomic literature is scarce, even fewer scholars examinate residential investment specifically.
Most of them emphasize house prices consequences and not its volume implications cites:arestis_residential_2015,perez_Montiel_2021.

*** Taxa própria

MELHORAR DEFINIÇÃO DE TAXA PRÓPRIA

From this literature review, we conclude that the econometric literature is more concerned with the implication of housing instead of focussing on its determinants.
One way to describe housing growth rate is the houses' own interest rate proposed by textcite:teixeira_crescimento_2015 following \citeauthor*{sraffaDrHayekMoney1932}'s citeyear:sraffaDrHayekMoney1932 contribution.
In summary, this particular real interest rate depicts debt service and capital gains effects altogether.
On the following section, we discuss this proposal in further details and evaluate its econometric significance.

#+BEGIN_EXPORT latex
\input{tabs/EmpiricalMotivation}
#+END_EXPORT

*** Gauger
Despite clarifying some macroeconomics  implications of housing on the business cycle, the results reported above are centered on supply side variables.
textcite:gauger_residential_2003, on the other hand, evaluate the consequences of deregulation of depository institutions throughout the 1980s.
To do so, they estimate a VECM between monetary aggregates (M2), GDP, residential investment and alternate between short-term government bonds and long-term mortgage interest rates.
They report an increasing contribution of long-term mortgages interest rate over resident investment variance after those institutional chances mentioned above:

#+BEGIN_QUOTE
The findings for the two interest rates give valuable information to evaluate results in other studies. Results here suggest that use of a short-term FFR and post-deregulation data may lead to conclusions that `interest rate shocks are much less important after deregulation.' The fuller state of evidence here indicates that interest rate shocks remain important post-deregulation; however, now it is the long-term rate shocks that carry more information for housing sector movements \cite[p.~346]{gauger_residential_2003}.
#+END_QUOTE
It worth noting that \citeauthor*{gauger_residential_2003}'s citeyear:gauger_residential_2003 work reports other two interesting results:
	(i) GDP level is determined by residential investment and both expenditures share a common long-term trend;
	(ii) show some relevant institutional changes in real estate market.

Figure ref:Fig:CreditFDICIA illustrates item (ii) mentioned above in which we mark some reforms that occurred due to the savings and loans crisis throughout the 80's and early 90's.
This institutional changes --- notably Financial Institutions Reform, Recovery, and Enforcement Act (FIRREA) in 1989 and Federal Deposit Insurance Corporation Improvement Act  (FDICIA) in 1991 --- increased the credit volume to households[fn::
	textcite:federal_deposit_insurance_corporation_savings_1997 argues that this consequence stems from the different regulation of S&L compared to commercial banks. The financial deregulation of the 1980s encouraged speculation in other sectors, especially real estate. As a consequence, engendered a banking run, increasing overall credit volume, which, however, was followed by the S&L crisis:
@@latex:\begin{quotation}@@
Clearly, competition from savings and loans did not cause the various crises experienced by the commercial banking industry during the 1980s; these crises would have occurred regardless of the thrift situation. But the channeling of large volumes of deposits into high-risk institutions that speculated in real estate development did create marketplace distortions \cite[p.~168]{federal_deposit_insurance_corporation_savings_1997}
@@latex:\end{quotation}@@
Therefore, the increase in credit volume cannot be dissociated from speculation with real estate.][fn::According to textcite:federal_deposit_insurance_corporation_savings_1997, had two main objectives:
		(i) Recapitalize the bank insurance fund and;
		(ii) Reform the deposit guarantee system and bank regulation to minimize  taxpayer in the event of bank collapse cite:mishkin_evaluating_1997.
		\textcite[p.~170]{federal_deposit_insurance_corporation_savings_1997} describe banking operation before FDICIA as follows:
@@latex:\begin{quotation}@@
Legislation for S&Ls was driven by the public policy goal of encouraging home ownership. It began with the Federal Home Loan Bank Act of 1932, which established the Federal Home Loan Bank System as a source of liquidity and low-cost financing for S&Ls.
@@latex:\end{quotation}@@
and the implications after its implementation is depicted as:
@@latex:\begin{quotation}@@
Prior to the act’s passage, the FDIC and the Federal Savings and Loan Insurance Corporation provided 100 percent \textit{de facto} deposit insurance at almost all failed banks. The FDIC did so by comparing bids to acquire the entire bank (including all its deposits) with the cost of liquidating the bank, which generally produced the result that covering all deposits was less expensive (FDIC 2003, chap. 2). FDICIA sought to change this process by mandating least-cost resolution, which required consideration of all possible resolution methods (FDIC 2003, chap. 2) \cite[p.~iii]{wall_too_2010}
@@latex:\end{quotation}@@].
As a consequence, real estate finance has increased considerably in the following periods.


#+BEGIN_EXPORT latex
\begin{figure}[htb]
	\centering
	\caption{Mortgage and Consumer credit growth rate (1979-2019)}
	\label{Fig:CreditFDICIA}
	\includegraphics[width=\textwidth]{./figs/FDICIA.png}
	\caption*{\textbf{Source:} U.S. Bureau of Economic Analysis, Authors' elaboration}
\end{figure}
#+END_EXPORT

Although textcite:gauger_residential_2003 emphasize the relevance of long-term mortgages interest rate in residential investment dynamics, this procedure is not appropriate once policy rate is determined by monetary aggregates.
Thus, such a proposal is incompatible with modern macroeconomic theory in which policy rate is an exogenous variable determined through a decision-making process \cite[p.~230--256]{lavoie_post-keynesian_2015}.

* Empirical review configs                                           :ignore:noexport:

bibliography:ref.bib

* Review of the Macroeconometric Literature                          :ignore:


** Ausência de trabalhos que analizam investimento residencial de um ponto de vista macroeconômico :ignore:

As we have seen in the previous session, there has been a growing attention to the macroeconomic implications of residential investment. It is worth noting, there is a vast empirical literature on housing. However, this literature is mainly focused on urban and regional economics or microeconomic issues. As a consequence, few econometric papers analyze housing in macroeconomic terms. Additionally, if housing macroeconomic literature is scarce, even fewer scholars examine residential investment and its determinants specifically. In this section, we review papers that analyse the determinants of residential investment (or some proxy) focusing on the US case, as well on some panel analysis of multiple countries.

In this sense, \citeauthor*{poterba_tax_1984}'s \citeyear{poterba_tax_1984} contribution stands out once it considers houses as an asset and not only as a durable consumption good.
Based on asset-market model for the construction sector, he estimates a residential investment supply function for the US from 1974 to 1982.
In order to estimate the determinants of residential investment, he includes real house prices, a non-residential constructor deflator index, wages of the housing sector and alternates between two measures  of  credit  rationing.
Therefore, textcite:poterba_tax_1984 concludes that residential investment is positively induced house prices.

textcite:topel_1988_Housing come to a similar conclusion to textcite:poterba_tax_1984.
Based on instrumental variables, they estimate the determinants of housing starts (as a proxy for residential investment) for the US from 1963 to 183.
Their functional form for residential investment includes hedonic prices and some cost shifters for the construction sector such as interest rate, expected inflation, wages and median market time since the construction begins.
In summary, they found that residential investment is highly sensible to house prices movements while interest rate is a relevant cost shifter.

Recently,  textcite:arestis_residential_2015 update \citeauthor*{poterba_tax_1984}'s citeyear:poterba_tax_1984 framework by estimating an autoregressive distributed lag (ARDL) model for 17 OECD countries.
In their model, they specify residential investment as a positive function of house prices, real disposable income and bank credit while mortgage interest and unemployment rate are expected to have negative effects.
They report that disposable income is the major determinant of residential investment for most OECD countries while banking credit and house prices are more relevant for the US.

Some scholars estimated residential investment based on a Tobin's Q for residential investment[fn::This adapted Tobin's Q is defined as the ratio between the market price of new houses and construction cost to build a new one.].
textcite:barot_2002_House, for instance, investigate the differences and similarities for the Sweden and UK housing market based on a stock-flow framework from 1970 to 1998.
Their residential investment functional form includes both Tobin's Q for residential investment and real interest rate.
They report some opposite results regarding Granger causality tests for house prices, financial wealth, household debt and interest rate.
The only result that is equally valid for both Sweden and UK is that Tobin's Q for residential investment  granger causes housing investment.
More recently, textcite:kohlscheen_2018_Residential, also estimate residential investment as a function of this particular Tobin's Q with an unbalanced panel data for 15 OECD countries from 1970 ownwards[fn::More precisely, textcite:kohlscheen_2018_Residential include Tobin's Q for residential investment numerator and denominator as separate variables.].
Beyond this adapted Tobin's Q they also include real house prices, GDP level, population density, net migration rates and house stock share on GDP.
In summary, they conclude that real house prices growth, nominal interest rate, net migration rates and existing house stock are the main determinants of residential investment.

Other common ground in the housing literature is the relevance of interest rate for residential investment.
In a OLS model for 7 OECD countries, textcite:egebo_1990_MODEL concludes that real disposable income and interest rate deflated by consumer price index are relevant for residential investment.
For the US in particular, they report that mortgage interest rate coefficients are robust.
Some scholars have reported that the residential investment sensitivity to interest rate are still valid after institutional changes of mid-1980s[fn::Just to name some of them: Depository Institutions Deregulation and Monetary Control Act (1980); Financial Institutions Reform, Recovery, and Enforcement Act (FIRREA, 1989). For a detailed chronology, see  \textcite[Appendix B]{mccarthyMonetaryPolicyTransmission2002} and textcite:green_american_2005.].
textcite:mccarthyMonetaryPolicyTransmission2002, for instance, evaluate the responsiveness of residential investment to interest rates considering these changes in the housing financing system.
In order to isolate these effects, they estimate  a GMM model for the US in two sub-samples (1975-1985 and 1986-2000).
They conclude that the residential investment response magnitude to a monetary shock before and after these institutional breaks are similar.
textcite:gauger_residential_2003 also evaluate the consequences of deregulation of depository institutions throughout the 1980s.
In order to do so, they estimate a VECM between monetary aggregates (M2), GDP, residential investment and alternate between short-term government bonds and long-term mortgage interest rates.
They report an increasing contribution of long-term mortgages interest rate in order to explain resident investment variance after those institutional changes mentioned above.


Table ref:tab:summary_models presents an overview of the discussed topics and its main conclusions.
From this brief review of the literature, we conclude that may be the only consensus about the determinants of residential investment is on house prices (nominal or deflated by consumer price index) and some rate of interest (mortgage or long term, as proxy)[fn::For a broader review of econometric literature, see textcite:egebo_1990_MODEL.].
Some authors deflate the rate of interest by the CPI, others use nominal interest rate to capture the effect of monetary illusion.
In the next section, we will present a particular way of combining house prices and mortgage rate of interest in a single index that we will use on our econometric estimation.



#+BEGIN_EXPORT latex
\input{tabs/EmpiricalMotivation}
#+END_EXPORT
