* Introduction Configs                                               :ignore:noexport:
#+BIBLIOGRAPHY: ref.bib
bibliography:ref.bib

* Fora :noexport:


#+BEGIN_COMMENT
A current trend among empirical research on demand-led growth agenda is to test its  relevance and stability.
\textcite{freitas_pattern_2013} present a growth accounting decomposition and show the relevance of those expenditures to describe the Brazilian GDP growth rate between 1970-2005.
\textcite{braga_investment_2018} shows evidence that economic growth and induced investment are governed by unproductive expenditures in Brazilian economy from 1962 to 2015.
For the US, \textcite{girardi_long-run_2016} show that autonomous expenditures do cause long-run effects on the growth rate. \textcite{girardi_autonomous_2018} bring evidence that autonomous expenditures determine the investment share on GDP for twenty OECD countries.
\textcite{haluska_growth_2019} employ Granger-causality tests to assess the stability of the SSM for the US (1987-2017). They find: (i) causality goes from autonomous expenditures to the marginal propensity to invest; (ii) induced investment share has a higher temporal persistence and presents slow and statistically significant adjustment rate to demand growth, as described by the SSM.
#+END_COMMENT

Among aggregate demand expenditures, non-residential investment is the most examined  one between (at least) heterodox macroeconomists.
As a consequence, the relevance of others (autonomous) expenditures on macroeconomic dynamics has been underestimated cite:brochier_macroeconomics_2017.
The Sraffian supermultiplier (SSM) model presented by textcite:serrano_long_1995 establishes a prominent role for non-capacity creating autonomous expenditures in the theoretical ground.
Despite the late interest in those expenditures cites:freitas_pattern_2013,girardi_long-run_2016,girardi_autonomous_2018,braga_investment_2018, there still is a lack of studies on the role of residential investment in particular.

* Introduction                                                       :ignore:

The importance of non-residential investment to macroeconomics is a commonplace among economists.
An unintended consequence is the underestimation of the relevance of other expenditures on macroeconomic dynamics cite:brochier_macroeconomics_2017.
The subprime crisis (2008) and the Great Recession (2008-2009) changed this landscape.
Policymakers have payed more attention on housing market.
Most of the new recommended housing macroprudential policies have started to focus on household indebtedness, banking regulation and Loan-To-Value (LTV) rules as in textcite:arena_2020_Macroprudential[fn::In the literature there are several examples of the limitations of those polices. For instance, textcite:galan_2019_LTV discuss those restrictions for the Spanish economy.].
While concerns about house price bubbles and credit grant play a major role on those recommendations, residential investment is only indirectly considered as in textcite:baptista_2016_Macroprudential and textcite:Ozel2019.
In this paper, we argue that the scarce attention that residential investment receives is not compatible with its macroeconomic relevance.

The Sraffian supermultiplier (SSM) model presented by textcite:serrano_long_1995 and textcite:bortis_institutions_1997 establishes a prominent role for non-capacity creating autonomous expenditures in the theoretical ground.
This model inaugurated a research agenda on autonomous demand-led growth following two directions.
The first concerns empirical applications of the model cites:freitas_pattern_2013,girardi_long-run_2016,girardi_autonomous_2018,Braga2020,Haluska2020.
The other is about the financial determinants of the autonomous expenditures and its consequences to economic growth cites:Pariboni2016,brochier_supermultiplier_2018,Mandarino2020,petrini_2021_TD.
Residential investment is one kind of autonomous expenditure.
Some authors have analyzed its macroeconomic consequences focusing on business cycle and long-run economic growth  cite:fiebiger_trend_2017,fiebiger_semi-autonomous_2018,perez_Montiel_2021,petrini_2021_TD.
But few works have examined its determinants in a macroeconomic level and still there is not a consensus about it.

Our main objective is to present and evaluate a parsimonious way of explaining the behavior of the residential investment growth rate, focusing on the US case (1992-2019).
The time range was selected because it captures the effects of changes in depository institutions in the 1980s and  begining of the 1990s, the rise of house prices, the bubble of the 2000s, and the aftermath of the 2008 crisis.
We base this explanation on a single index that combines two relevant variables of the housing market: mortgage interest rate and house price inflation.
The results of our investigation indicate its relevance in explaining the dynamics of residential investment growth rate.
We find a common long-run trend between the proposed index and residential investment.
The former accounts for more than a half of the variance of the latter.
We also report unidirectional Granger-causality from the proposed index to residential investment growth rate.

The article is organized as follows.
In Section ref:sec:Stylized_Facts, we present some stylized facts and discuss the macroeconomic relevance of residential investment regarding the US case.
Next, in Section ref:sec:empirical_review, we review empirical works that estimate the determinants of residential investment.
In Section ref:sec:VECM, we estimate a bi-variate vector error-correction model (VECM) using time-series data for the US economy from 1992 to 2019 and present the results.
Section ref:sec:Conclusion concludes the paper.
Appendix ref:appen:A provides results for all statistical tests employed and for the robustness check.
