#+TITLE: Untitled
#+OPTIONS: toc:nil author:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt, a4paper]
* Configs :ignore:
** Packages :ignore:
#+LATEX_HEADER: \addbibresource{ref.bib}
#+LATEX_HEADER: \usepackage{svg, caption, multirow, booktabs, tabularx, subfigure, subcaption, lscape, tablefootnote, threeparttable, makecell}
#+LATEX_HEADER: \newcolumntype{b}{>{\hsize=2.3\hsize}X}
#+LATEX_HEADER: \newcolumntype{s}{>{\hsize=.45\hsize}X}
#+LATEX_HEADER: \newcolumntype{m}{>{\hsize=.9\hsize}X}
#+LATEX_HEADER: \usepackage[english]{babel}
*** Original date ([[https://tex.stackexchange.com/questions/142999/the-proper-way-to-cite-the-earliest-publication-date-in-brackets-followed-by][Link]]) :ignore:
#+begin_export latex :exports none
\DeclareLabeldate{%
  \field{date}
  \field{year}
  \field{eventdate}
  \field{urldate}
  \literal{nodate}
}

\renewbibmacro*{date+extradate}{%
  \iffieldundef{labelyear}
    {}
    {\printtext[parens]{%
       \iffieldundef{origyear}
         {}
         {\printtext[brackets]{\printorigdate}%
          \setunit{\addspace}}%
       \iflabeldateisdate
         {\printdateextra}
         {\printlabeldateextra}}}}

\renewbibmacro*{cite:labeldate+extradate}{%
  \iffieldundef{labelyear}
    {}
    {\printtext[bibhyperref]{%
       \iffieldundef{origyear}
         {}
         {\printtext[brackets]{\printorigdate}%
          \setunit{\addspace}}%
       \printlabeldateextra}}}
#+end_export

** Submission specifications :ignore:
#+LATEX_HEADER: %\usepackage{endfloat}

** Authors infos :ignore:
#+LATEX_HEADER: \usepackage{authblk}
#+LATEX_HEADER:\author[1]{Gabriel Petrini}
#+LATEX_HEADER:\affil[1]{PhD Student at University of Campinas (Brazil), Email: \url{gpetrinidasilveira@gmail.com}} % Author affiliation
#+LATEX_HEADER:\author[2]{Lucas Teixeira}
#+LATEX_HEADER:\affil[2]{Assistant Professor at University of Campinas (Brazil), Email: \url{lucastei@unicamp.br}} % Author affiliation
#+LATEX_HEADER:\author[3]{Frankin Serrano}
#+LATEX_HEADER:\affil[3]{Associate Professor at Federal University of Rio de Janeiro (Brazil), Email: \url{}} % Author affiliation

#+PROPERTY: header-args:python :python /usr/bin/python3 :exports none :eval never-export
#+BIND: org-latex-prefer-user-labels t

* Abstract :ignore:
#+BEGIN_abstract
This article investigates the relationship between residential investment, asset inflation, and macroeconomic dynamics based on
the US post-deregulation case (1992-2019). To do so, we estimate a vector error correction model (VECM) to asses the relevance of
real interest rate of real estate. We find residential investment growth rate and houses’ own interest rate to be cointegrated. We
also find that long-run causality goes unidirectionally from houses’ own interest rate to residential investment growth rate,
as expected. In summary, our findings support the relevance of houses’ own interest rate in determining residential investment
while the other way round does not occur.
	
#+LATEX: \noindent \textbf{Keywords:} Residential Investment; Asset price inflation; Mortgage Interest rate; Vector-Error correction model
#+LATEX: \noindent \textbf{JEL cods:} E39; E44; R39
#+END_abstract


* TODOs :noexport:ignore:
** TODO Printer-friendly plots
** TODO Fix axis labels font size
* Introduction
#+LATEX: \label{sec:Introduction}
#+INCLUDE: "Introduction.org"



* Residential investment, economic growth and business cycle in the US economy
#+LATEX: \label{sec:Stylized_Facts}
#+INCLUDE: "Stylized_Facts.org"
* Determinants of residential investment: review of empirical literature
#+LATEX: \label{sec:empirical_review}
#+INCLUDE: "Empirical_Review.org"

* Macroeconometric analysis
#+LATEX: \label{sec:VECM}
#+INCLUDE: "VECM.org"

* Concluding Remarks
#+LATEX: \label{sec:Conclusion}
#+INCLUDE: "Conclusion.org"


* Acknowledgments
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+LATEX: \noindent The authors wish to acknowledge the financial support from the Brazilian National Research Council (CNPq; grant 130777/2018-8). We are grateful to Rosângela Ballini, Carolina Baltar, Júlia Braga, Ítalo Pedrosa, Cecon/Unicamp and UFRJ Macroeconomic discussion groups for useful comments and suggestions on earlier drafts of this article. All remaining errors are, of course, our own.


* Disclosure statement
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
No potential conflict of interest was reported by the authors.

* References
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+LaTeX: \printbibliography[heading=none]


#+Latex: \appendix
* Statistical Appendix
#+LATEX: \label{appen:A}

In this appendix we report several tests: unit root tests on our variables of interest, Structural break test, Johansen procedure and hypothesis tests on residuals. 
The time-series of residential investment growth rate, mortgage interest rate and real estate inflation are all taken using textcite:yeo_new_2000 transformation.  
As shown in Table ref:unitroot, the null hypothesis of a unit root in the first differences of the series is overwhelmingly rejected.
As mentioned, we found structural breaks related to institutional changes and our series are co-integrated (see Tables ref:structbreak and ref:Johansen).
Our estimation order selection was based both on statistical and theoretical reasoning with homoscedasticity residuals (see Tables ref:criterios and ref:testes_resduos).
All expected results are statistically significant and most of them are not restrict to model specification (see Table ref:tab:robust).

#+begin_export latex
\input{./tabs/UnitRoot.tex}
\input{./tabs/StructBreak.tex}
\input{./tabs/Johansen.tex}
\input{./tabs/lag_order.tex}
\input{./tabs/H0_Residuals.tex}
\input{./tabs/robust.tex}
#+end_export

