-*- mode: org -*-
#+OPTIONS: num:nil
#+TITLE: Atas Compom
#+AUTHOR: Gabriel Petrini
#+LANG: pt_Br

* LaTeX headers                                         :noexport:ignore:

* HTML headers                                         :noexport:ignore:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>

#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>



* <2002-02-21> [[https://www.bcb.gov.br/htms/copom/not2002022068.asp?frame=1][Ata Nº68]]
** Atividade Econômica
- Recuperação econômica
  + Indústria e comércio
    - Destaque crescimento bens de consumo duráveisi
    - Concessionárias em queda
  + Queda dos estoques e mercado de trabalho reforçam (queda do desemprego)
  + Delineada em 2001
  + Recuo produção dos bens de capital e crescimento da importação (aumento absorção doméstica)
- Maior nível de confiança (consumidores e empresários) $\Rightarrow$ tendência do nível de atividade
  + Melhora dos efeitos negativos do setor externo adverso
- Fatores de sustentação demanda
  + Crescimento da massa de rendimentos
  + Condições de crédito
- Atendimento parcial da demanda reprimida de energia
- Superávit transações externas (importante)
  + Queda das exportações menor que das importações
  + Sinais de substituição de importações associada à *depreciação*
- Aumento da produção *não* sinaliza pressão sobre o nível de utilização da capacidade produtiva
  + Elevado grau de ociosidade
  + Maior fluxo de investimento externo $\Rightarrow$ aumento de produtividade $\Rightarrow$ expansão da demanda é sustentável
** Ambiente externo
- Recuperação da atividade nos EUA e manutenção da taxa de juros americana (interrompe flexibilização)
  + Impacto positivo no comércio mundial e nos mercados mundiais de capitais
  + Diminuição dos efeitos negativos do /flight to quality/
- Espiral deflacionária no Japão
  + Contrapõe a retomada dos outros países
- Taxa de juros do Euro inalterada
** Preços
- IPCA elevou (acumulado 7,62%), mas em desaceleração
  + Alta dos preços dos alimentos
    - Condições atmosféricas
  + Preços administrados
  + Queda do preço da gasolina, mas aumento do gás (retirada subsídios)
- IGP-DI similar ao anterior
- Queda dos preços industriais
- Efeitos sazonais do aumento dos gastos com educação
- Espera-se *desaceleração* dada expectativa de redução dos preços dos alimentos
** Mercado monetário e operações de mercado aberto
- Movimentos de pequena intensidade na curva de juros
  + Manutenção da taxa de juros reverteu curva de juros negativa
- Tentativa de desconcentração dos vencimentos dos títulos 
  + Maior demanda por títulos de prazos mais curtos
- Retomada do oferecimento de LFT cuja demanda foi reduzida
- Aumento dívida pública doméstica
** Avaliações prospectivas das tendências de inflação

- Elevação IPCA
- Redução nos preços de gasolina, gás, bujão
- Projeção de reajuste nas tarifas de energia elétrica
- Elevação da inclinação da curva de juros
- Estabilidade do prêmio de risco soberano
- Expectativa de aumento dos preços administrados
- Hipótese de cumprimento das metas de superávit primário (setor público consolidado)
** Diretrizes de política monetária
*Decisão:* Reduzir a taxa de juros
- Preços administrados não recuaram tanto quanto esperados
- Pressão por recomposição das taxas de lucro e repasse cambial pode *diminuir*
  + Expansão moderada do crédito
  + Aumento de investidores, da capacidade produtiva e fim do racionamento de energia $\Rightarrow$ ampliação do potencial produtivo
    - *Memo:* Capacidade ociosa
  + Expansão da demanda pode não pressionar preços
- Expectativas de inflação estáveis
- Cenário internacional menos adverso, mas ainda sim incerto
- Política monetária poderia ser flexibilizada
- Queda da inflação em direção à meta

* <2002-10-30> [[https://www.bcb.gov.br/publicacoes/atascopom/01102002][Ata Nº76]]

** Diretrizes de política monetária
*Decisão:* aumentar taxa de juros em 3 p.p.
- Índices indicam aumento da inflação
  + Depreciação cambial real
  + IPCA acima do valor esperado
  + Inflação de preços livres
- Expectativas de mercado de aumento de inflação e o mesmo vale para a projeção do COPOM
- Maior grau de incerteza dados os resultados da *eleição presidencial*
- Projeção da inflação futura esta acima da meta
  + Recomenda uma política monetária mais restrita mesmo que não relacionada com aumento da demanda
  + Depreciação cambial significativa
- Reunião extraordinária

* <2002-10-22> [[https://www.bcb.gov.br/publicacoes/atascopom/22102002][Ata Nº77]]
** Atividade Econômica
- Estabilidade do nível de atividade junto de movimentos opostos
  + Aumento de incertezas (eleição)
  + Efeitos negativos no mercado financeiro $\Rightarrow$ efeitos negativos sobre consumo de bens de elevado valor agregado e investimento
  + Efeitos positivos sobre comércio varejista
    - FGTS
    - Aumento do nível de emprego
    - Renda agrícola
    - Desepenho favorável da balança comercial
    - Aumento do faturamento
      + Bens de consumo semi e não-durávies
    - Redução IPI
    - Expansão dos negócios a vista
  + Expansão do crédito $\Rightarrow$ aumento varejo
    - Aumento inadimplência
- Incertezas futuras e volativlidade cambial
  + Redução índice de confiança do consumidor
- Queda inadimplência de crédito livre $\Rightarrow$ maior seletividade dos bancos
- Aumento da atividade industrial
  + Produção extrativa mineral
  + Nível de produção constante
  + Aumento da produção dos bens intermediários
  + Recuo produção dos bens de capital e de consumo duráveis
  + Expansão das vendas industriais
  + Estabilidade do nível de utilização da capacidade e uso de estoques
- Aumento da taxa de desemprego aberta
- Superávit na conta de transações correntes, balança comercial e queda da remessas líquidas ao exterior
** Ambiente externo
- Aversão ao risco e elevada volatilidade nos mercados globais
- Expectativa de redução da recuperação econômica mundial
  + Ataque terrorista na Indonésia e tensão entre EUA e Iraque
  + Dúvidas sobre capacidade de recuperação dos EUA
  + Ligeiro crescimento da produção industrial no Japão
  + Sinais de recuperação na zona do Euro
** Preços
- Aumento dos preços livres
  + Taxa de câmbio deve ser a principal pressão inflacionária
  + Elevação IPCA
    - Alimentação e bebidas
    - Variação cambial
  + IGP-DI eleva-se por conta do câmbio e dos efeitos intrassafra
    - Elevação dos preços agrícolas e industriais
** Mercado monetário e operações de mercado aberto
- Tendência de queda dos juros em função da redução das incertezas quanto ao cenário político-econômico
- Maior demanda por NTN-C
- Objetivo de reduzir volatilidade dos preços das LFTs
** Avaliações prospectivas das tendências de inflação
- Incerteza quanto as trajetórias dos preços dos derivados de petróleo
- Projeção do aumento das tarifas de eletricidade
- Aumento dos preços administrados dado repasse cambial
- Trajetória decendente do /spread bancário/


*** Resultados

- Aumento do IPCA mensal e acumulado
- Hipótese de cumprimento da meta de superávit primário
- Manutenção da taxa de juros e da taxa de câmbio
** Diretrizes de política monetária
*Decisão:* 


*Decisão:* Manter meta em 21%
- Crescimento das vendas e estabilidade da produção industrial
- Crescimento da massa de rendimento dos salários
- Estabilidade no nível de emprego
- Aumento  do consumo deve-se concentrar nos bens não-duráveis
- Redução dos estoques, mas acima do nível desejado
- Aumento dos custos decorrentes do repasse cambial
- Redução do nível de utilização da capacidade
- Ajuste na conta corrente
  + Depreciação cambial
  + Crescimento lento
  + Melhora na conta corrente e bom desempenho da balança comercial
- Crise de confiança reduziu crédito ao Brasil e aumento da percepção do risco soberano
- Estabilização e recuperação do mercado financeiro
  + Real se manteve estável
  + Maior demanda por títulos no mercado doméstico
- Expectativas de aumento da inflação e maior dispersão das expectativas
  + Copom também reavaliou para cima por conta da depreciação cambial
    - Entendimento que se trata de uma inflação de custo
  + Aumento gasolina

* <2003-06-19> [[https://www.bcb.gov.br/publicacoes/atascopom/01062003][Ata Nº85]] 
** Evolução recente da inflação
- Queda contínua da inflação
  + Redução preços do atacado $\Rightarrow$ apreciação cambial
  + Preços ao consumidores cairam, mas menos que os preços do atacado
    - Preços agrícolas e industriais
- Redução IPCA
  + Reajuste das tarifas de energio foi o que mais contribuiu para aumento
    - Aumento da tarifa de ônibus, água e esgoto
  + Atenção à safra de arroz
  + Queda tanto dos preços livres como nos monitorados
    - Redução dos produtos não comercializáveis
    - Redução menos intensa dos bens comercializáveis
    - Redução do preço da gasolina e do álcool
** Avaliação prospectiva das tendências da inflação
- Elevação do preço da gasolina
- Diminuição dos preços monitorados $\Rightarrow$ apreciação cambial
- Projeções de que a inflação futura estará acima da meta
** Implementação da política monetária
*Decisão:* Reduzir meta em 26% para garantir desaceleração recente da inflação
- Fatores do declínio da inflação
  + Elevada depreciação passada explica inércia da inflação (persistência) 
  + Apreciação cambial tem efeitos de redução da inflação
  + Atuação da política monetária para reverter expectativas de inflação e pressões inflacionárias via controle da demanda agregada
  + Normalização dos preços in natura
- Destaque para a persistência inflacionária e subsequente recomposição das margens de lucro
- Destaque para apreciação cambial
  + Elevação da liquidez internacional
  + Queda do risco Brasil
- Atividade econômica em desaceleração, mas não uniforme (diferença dos preços relativos)
  + Expansão do setor agrícola e extração
  + Maior retração para o setor de bens duráveis 
    - Dependente das condições de crédito
- Convergência das expectativas de inflação para meta
- Destaque para a persistência inflacionária
** Atividade econômica
- Queda generalizada da venda no varejo 
  + Destaque para duráveis e semi-duráveis
  + Recuperação da confiança do consumidor 
- Fraco desempenho dos indicadores de investimento
  + Adversidades da conjuntura econômica
  + Produção industrial estável
- Expansão do setor extrativo e recuo na indústria de transformação
- Redução do grau de utilização da capacidade instalada
** Mercado de trabalho
- Aumento do emprego formal
- Estabilidade na taxa de ocupação junto do aumento do emprego informal
** Crédito e inadimplência
- Estabilidade no saldo de operações de crédito
  + Aumento no capital de giro
- Estabilidade na taxa de inadimplência
** Ambiente externo
- Expectativa de recuperação econômica mundial ainda baixa
- Lenta retomada da atividade econômica nos EUA
- Recuo no Japão e Alemanha junto de tendência de deflação
- Redução da taxa de juros pelo BCE
** Setor Externo
- Superávit balança comercial sobretudo por conta da melhora das exportações e ligeiro declínio das importações
- Saldo positivo em transações correntes e superávit nas transações unilaterais
  + Ingressos líquidos na conta financeira
** Mercado monetário e operações de crédito aberto
- Curva de juros mais negativa
  + Divulgação dos indicadores de inflação
  + Apreciação cambial
  + Redução do risco país
  + Aprovação do projeto da reforma da previdência
- Rolagem da dívida por meio de /swaps/
- Aumento do prazo médio de emissão da dívida
- Aumento da dívida interna

* <2006-04-17> [[https://www.bcb.gov.br/publicacoes/atascopom/24042008][Ata Nº 134]] 
** Evolução recente da economia
- IPCA estável, mas inflação em aceleração em 12 meses
  + Destaque para preços livres que aumentaram mais rápido do que os preços administrados
    - Aceleração dos bens comercializáveis e não-comercializáveis (in natura e serviços especialmente)
  + Apreciação cambial
  + Sinais de divergência da meta
- Recuo IGP-DI inicial seguido de aceleração
  + Aceleração dos preços industriais desde 2007
  + Destaque para repasse a depender da expectativa futura sobre inflação
- Redução da produção industrial geral, mas crescimento no ano $\Rightarrow$ estabilidade macroeconômica
  + Destaque para setor farmacêutico
  + Continuidade de expansão do setor industrial
    - Expansão do crédito, emprego e renda
    - Impulsos fiscais
    - Recomposição de estoques
  + Avanço produção de bens de capital e de bens duráveis
- Aumento na taxa de desemprego e da remuneração
  + Expansão do emprego formal
- Crescimento da demanda doméstica (sobretudo varejo)
  + Sem sinais de redução
  + Móveis e eletrodomésticos e setores mais sensíveis à expansão da renda e do crédito
- Manutenção da confiança do consumidor
- Aumento do grau de utilização da capacidade instalada
  + Crescimento da absorção dos bens de capital
  + Aumento de insumos da construção civil $\Rightarrow$ ampliação da capacidade
- Desempenho robusto da balança comercial
  + Aumento do preço de commodities
  + Redução do saldo comercial $\Rightarrow$ transações correntes mais deficitário
- Desaceleração da economia norte americana em função da crise
  + Mais avaliações negativas
  + O mesmo vale para Japão e Alemanha
  + Indicação de relaxamento monetário internacional adicional
  + Parece não ter afetado a economia doméstica
- Elevação do preço e da volatilidade do petróleo
  + Cenário de trabalho de preços de combustíveis inalterados 
** Avaliação prospectiva das tendências da inflação
- Sem reajuste dos preço dos combustíveis
- Manutenção da tarifa telefônica e dos preços administrados
- Diminuição do /spread/ de juros
- Manutenção da meta de superávit primário com possibilidade de redução
  + Implementação do Programa Piloto de Investimentos (PPI)
- Aumento das medianas de expectativas da inflação
- Convergência da inflação para acima da meta
** Implementação da política monetária
- Aceleração da inflação em função da maior robustez da atividade doméstica
  + Apesar do aumento da inflação e do investimento
- Balanço de pagamentos não deve apresentar risco à inflação
- Desaceleração dos mercados mundiais, mas riscos inflacionários a níveis globais $\Rightarrow$ benigno
  + Reduziria exportações líquidas (demanda)
  + Queda de preço de algumas commodities $\Rightarrow$ menor inflação doméstica
  + Posibilidade de maior aversão ao risco e incerteza
  + Possibilidade de restrição de oferta setorial $\Rightarrow$ repasse ao consumidor
- Possibilidade de um maior impulsionamento em função do aumento da massa salarial e do crédito além das transferências governamentais
- Destaque para redução do hiato do produto
- Ênfase ao combate dos efeitos inicias da inflação e não os persistentes
  + Sinais de excesso de aquecimento da demanda
** Inflação
- Aumento do IPCA e do IGP-DI
  + Destaque para o preço dos alimentos, habitação e transportes
  + Desaceleração dos preços livres e aumento dos monitorados
** Atividade econômica
- Aumento das vendas no varejo e queda no comércio
- Aumento do investimento, bens de capital e insumos
  + Destaque à maquinas agrícolas e infraestrutura
  + Aumento da importação dos bens de capital
- Expansão da atividade industrial
  + Estabilidade no grau de utilização da capacidade instalada
- Redução da produção física da indústria
  + Destaque ao setor farmacêutico
- Aumento produção de automóveis
- Aumento produção de grãos
** Expectativas e sondagens
- Aumento do índice de confiança do consumidor e estabilidade nas condições atuais
- O mesmo vale para a Confiança da Indústria
- Aumento do NUCI no setor de bens de capital em função da demanda doméstica e expectativas otimistas para o futuro
** Mercado de trabalho
- Criação de postos de trabalhos formais
  + Destaque para construção cívil e serviços
  + Redução da taxa de desemprego
  + Redução do emprego na indústria
- Aumento do rendimento habitual real
** Crédito e inadimplência
- Aumento do saldo de empréstimos
  + Atenção para recursos livres e direcionados para habitação
- Elevação da taxa de juros média
- Ampliação das operações de crédito
- Redução da taxa de inadimplência
** Ambiente externo
- Percepção de declínio na taxa de expansão da economia norte-americana  e seus efeitos sobre economia mundial
  + Temores nos mercados europeus
- Inflação global em função de alimentos e energia
- Elevação da inflação chinesa
** Comércio exterior e reservas internacionais
- Superávit na balança comercial maior que anteriormente
- Aumento das reservas internacionais
** Mercado monetário e operações de mercado aberto
- Elevação da curva de juros
  + Destaque para piora do cenário externo
- Realização de /swap/ cambial reverso
- Operações compromissadas longas 

* <2009-01-20> [[https://www.bcb.gov.br/publicacoes/atascopom/21012009][Ata Nº140]]
** Evolução rencente da economia
- Recuo inflação (IPCA)
  + Tanto preços livres quanto administrados
  + Aceleração do preços dos bens comercializáveis e não-comercializáveis
  + Persistência da inflação de serviços
- Convergência da inflação calculada pelos outros indicadores
  + Variação negativa do IGP-DI
  + Destaque para depreciação cambial $\Rightarrow$ preços agrícolas e industriais
- Redução da produção industrial
  + Destaque para problemas climáticos no Sul
  + Interrupção no ciclo de expansão
    - Ajuste de estoque e redução da produção
  + Destaque para recuo no setor de bens de capital, mas lidera expansão acumulada
    - Destaque para restrição de crédito
- Indicadores ambíguos de mercado de trabalho
  + Aumento na taxa de desemprego aberta
  + Aumento do Rendimento Mensal Médio
  + Perda de dinamismo na geral de empregos formais
- Redução das vendas do varejo
  + Destaque para queda acentuada do setor automotivo
    - Restrição de crédito e redução nos indicadores de confiança
  + Transferências de renda auxiliaram para que a queda não fosse maior
- Redução do grau de utilização da capacidade
  + Redução das pressões de demanda sobre capacidade produtiva
- Piora no saldo da balança comercial
  + Reversão da trajetória de apreciação cambial
  + Queda dos preços dos bens exportados atua na direção oposta
- Continuidade do estresse dos mercados financeiros
  + Aumento da aversão ao risco
  + Contração da liquidez internacional $\Rightarrow$ fluxos de capitais mais escassos $\Rightarrow$ volatilidade das moedas emergentes
- Tendências contracionistas a nível global
  + Choque negativo dos termos de troca $\Rightarrow$ /commodities/
  + Deterioração da qualidade do crédito
  + Destaque para tendência de depreciação cambial e estímulos fiscais nas economias maduras
- Elevada volatilidade do preço do petróleo
  + Efeitos via cadeias produtivas e expectativas futuras de inflação
** Avaliação prospectiva das tendências de inflação
- Sem inflação de combustíveis
- Manutenção do reajuste do setor de telefonia e o mesmo vale para os preços administrados
- Redução da mediana das expectativas de inflação
- Conclusão: recuo da inflação
** Implementação da política monetária
- Arrefecimento da expansão econômica
- Desaquecimento das demais economias
- Aversão ao risco $\Rightarrow$ ajustes no BP
  + Afeta demanda por ativos brasileiros
  + Diminuição dos preços de /commodities/ e da demanda externa
  + Efeitos benignos sobre a inflação
- Diminuição de riscos de pressão inflacionárias locais
- Expectativas de inflação estão superiores à meta apesar do recuo
- Crise internacional $\Rightarrow$ efeitos negativos sobre confiança
  + Expansão da economia depende mais ainda do crescimento da massa salarial e das transferências do governo
- Queda do nível de atividade deve reduzir pressões inflacionárias
  + Destaque para preço dos ativos brasileiros
  + Copom pontua necessidade de cautela para níveis de inflação compatíveis com a meta, mas há margem para flexibilização
- Condições financeiras restritivas $\Rightarrow$ contração da demanda $\Rightarrow$ pressão desinflacionária
- *Decisão:* Reduzir taxa de juros em 100 p.b. sem viés
** Inflação
- Indicação de recuo da inflação medida pelo IPCA
  + Desaceleração dos preços livres e dos monitorados
** Atividade econômica
- Retração das vendas no varejo
- Retração do crédito e da inadimplência
- Redução da produção de bens de capital e importação dessa categoria
- Desaceleração do rítmo de produção industrial
** Expectativas e sondagens
- Redução do índice de confiança do consumidor e o mesmo vale para os indicadores de confiança dos empresários
** Mercado de trabalho
- Redução do número de postos de trabalho
** Crédito e inadimplência
** Ambiente externo
** Comércio exterior e reservas internacionais
** Mercado monetário e operações de mercado aberto
* <2011-01-09> [[https://www.bcb.gov.br/publicacoes/atascopom/31082011][Ata Nº161]] 
** Evolução rencente da economia
- Aceleração da inflação medida pelo IPCA
  + Reflete tanto preços livres quanto administrados
    - Destaque aos bens comercializáveis e dos não-comercializáveis e queda do preço dos bens duráveis
  + Inflação de serviços elevada
  + Sugere persistência da alta dos preços
- Outros índices de inflação sugerem trajetória similar
- Tendência de moderação da taxa de crescimento medido pelo IBCBr
- Aumento do índice de confiança dos serviços
- Alta do índice de produção fabril
  + Expansão do índice de produção industrial no acumulado 12 meses
  + Crescimento tanto no setor de bens de consumo duráveis quanto no setor de bens de capital, mas é o menor dentre as categorias de uso
- Redução na taxa de desemprego e atingiu mínimo histórico
- Crescimento do rendimento médio habitual real
  + Destaque para sustentação no crescimento da demanda
- Crescimento no volume de vendas no comércio
- Grau de utilização da capacidade relativamente constante com tendência de queda na margem
- Aumento do saldo da balança comercial
  + Exportações cresceram mais que o crescimento das importações
  + Queda no déficit de transações correntes
  + Entrada de fluxos de capitais superiores à necessidade de financiamento externo
- Período de elevada incerteza
  + Destaque para maior risco para a estabilidade financeira global
    - Exposição de bancos internacionais a dívidas soberanas
  + Aumento dos indicadores de aversão ao risco
- Elevada volatilidade do preço do barril de petróleo $\Rightarrow$ estabilidade da demanda global
** Avaliação prospectiva das tendências de inflação
** Implementação da política monetária
** Inflação
** Atividade econômica
** Expectativas e sondagens
** Mercado de trabalho
** Crédito e inadimplência
** Ambiente externo
** Comércio exterior e reservas internacionais
** Mercado monetário e operações de mercado aberto
* <2020-11-03> [[https://www.bcb.gov.br/publicacoes/atascopom/28102020][Ata Nº234]]
** Atualização da conjuntura econômica e do cenário básico do Copom
- *Setor externo:* Desaceleração da retomada de alguns setores
  + Evolução da COVID-19
  + Possibilidade de resução dos estímulos governamentais
- Moderação da volatilidade dos ativos financeiros $\Rightarrow$ favorece economias emergentes
- *Mercado doméstico:* Recuperação desigual entre setores
  + Renda emergencial
  + Setores mais afetados continuam com a mesma tendência
  + Aumento da incerteza sobre a retomada da economia $\Rightarrow$ redução da renda emergencial
- Indicadores da inflação compatíveis com a meta
- Aumento da projeção da inflação
  + Alta do preço dos alimentos e de bens industriais $\Rightarrow$ depreciação do Real e das /commodities/
  + Perspectiva de normalização de preços com aumento extraordinário $\Rightarrow$ restrição na produção e aumento da demanda
  + Diganóstico de que este choque é temporário
- Ociosidade no setor de serviços
- Auxílios fiscais e adiamento de reformas $\Rightarrow$ aumento do prêmio de risco
- Maiores reduções nas taxas de juros $\Rightarrow$ instabilidade nos preços dos ativos
  + Proximidade à ZLB
- Projeções de inflação abaixo da meta
  + Expectativas de longo prazo ancoradas
* Texto apresentação 

** Panorama FHC e implementação do regime de metas

A década de 90, diferentemente da década anterior, está inserida em um contexto de retomada dos fluxos voluntários de capital (alta da liquidez internacional) em que as reformas liberalizantes desempenharam um papel norteador.
Nesses moldes, caberia ao Estado promover a estabilidade macroeconômica bem como funcionamento dos mercados.
A dinamização da economia, por sua vez, estaria a cargo do setor privado junto dos ganhos (de produtividade e competitividade) decorrentes das aberturas comercial e financeira.
Como consequência, desmontou-se a ossatura do Estado desenvolvimentista.

Em termos da *estrutura produtiva*, a combinação de abertura comercial e moeda sobrevalorizada impuseram dificuldades à indústria nacional. 
Soma-se a isso o comportamento patrimonialista do IDE que não ampliou a produtividade/competitividade, aumentando o coeficiente importado (acima do exportado) assim como não foi direcionado para ampliar capacidade produtiva. 

No que diz respeito à *política monetária*, destaca-se seu alinhamento com a âncora cambial e subsequente controle inflacionário. 
Em meio a esses objetivos, a taxa de juros (elevadas) teve um papel duplo:
(i) atrair fluxos de capitais e;
(ii) conter a absorção doméstica.
Desse modo, a estabilização monetária foi estabelecida às custas da estabilidade macroeconômica cite:belluzzoDepoisQuedaEconomia2002.
Em paralelo, como resultado das queimas de reservas em 1997/8, a âncora cambial foi substituída pelo regime de câmbio flutuante enquanto, em 1999, aderiu-se ao regime de metas para a inflação de modo a estabelecer uma âncora nominal doméstica.

Nos governos FHC, portanto, manteve-se o binômio juros elevado-câmbio sobrevalorizado, implicando em uma dinâmica /stop and go/, aumento do desemprego e crises bancárias e do balanço de pagamentos.
É em meio ao esse cenário adverso (``Herança Maldita'') que o governo Lula se inicia mas foi seguido de uma redução da restrição externa em decorrência da engrenagem comercial entre EUA-China-Periferia, elevando o ciclo de liquidez e promovendo melhora nos termos de troca (/boom/ de /commodities/) cite:carneiroDesenvolvimentoEmCrise2002. 

** Breve esquema do modelo de metas

** Continuísmo e descontinuidades dos governos Lula

Apesar da melhora da adversidade do setor externo, tal governo é marcado, até 2006, por um *continuísmo*. 
A preocupação com a solvência da dívida pública bem como da adesão da contração fiscal expansionista é um dos traços desse conservadorismo. 
Do ponto de vista dos fluxos, verificou-se uma deterioração da composição dos gastos em que ampliou-se os encargos com juros em detrimento do investimento público para gerar superávits fiscais.
Já em termos dos estoques, observa-se uma melhora da dívida pública (principalmente externa) junto de uma piora de seus prazos e custos.
A melhora da dívida em moeda estrangeira, no entanto, não indica que a restrição externa foi superada, mas sim que reaparece sob novas formas.
Por fim, destaca-se que o governo também aprofunda a abertura financeira, extinguindo a conta CC5 e unificando o mercado de câmbio livre e flutuante cite:pratesSECAOIVInsercao.

Apesar deste continuísmo macroeconômico, o governo Lula apresentou uma ruptura não-trivial: centralidade da questão fiscal.
Esta ênfase da questão social é impulsionada com o progressivo abandono do conservadorismo fiscal.
A *partir de 2006* ---  e acentuado no pós-crise --- tem início uma estratégia mais clara que coloca no Estado o papel de
articular o desenvolvimento em que o planejamento de longo prazo é retomado (PAC). 
Assim, a despeito de um banco central ainda bastante ortodoxo e da política de valorização cambial, coube a política fiscal assumir para si o papel de provedora do crescimento. 
Assume esse papel, no entanto, sem que se mude o regime fiscal instaurado por FHC, mas há uma nova gestão fiscal e orçamentária.

Sendo assim, a contração fiscal expansionista deu lugar a uma política fiscal mais ativa sem implicar em uma deterioração da dinâmica da dívida pública. 
Dentre os fatores que permitiram tal guinada, destaca-se os descontos do investimento público na metas de superávit primário da LDO bem como aumento da arrecadação.
Em linhas gerais, o aumento das receitas reflete a centralidade da questão social mencionada anteriormente que foi além de transferências e gastos sociais e avançou em direção às mudanças no mercado de trabalho (formalismo e ganhos salariais) e ampliação do crédito.
Em conjunto, tais medidas promoveram --- dada a redução da restrição externa --- o crescimento baseado no mercado interno junto da melhora na distribuição de renda.
Essa combinação de crescimento com inclusão social --- levada adiante pelo governo Dilma --- é entendida como a base da estratégia social-desenvolvimentista no período cite:biancarelliVelhaSenhoraEm2019. 

Em relação a *estrutura produtiva*, nota-se o insucesso em promover uma política industrial e creditícia capaz de reverter algumas tendências estruturais.
Nesses termos, a restrição externa reaparece sob novas formas que não são captadas pelos indicadores de solvência: redução do conteúdo tecnológico das exportações e aumento do coeficiente importando.
Em outras palavras, o governo Lula se encerra com um *descompasso* entre uma estrutura de demanda modernizada que não foi acompanhada da modernização da estrutura de oferta cite:melloIndustrialismoAusteridadePolitica.
O governo Dilma herda esses desafios estruturais, buscando readequar o modelo de
crescimento em contexto internacional mais difícil.

** Governo Dilma I

Em meio ao diagnóstico de *sobreaquecimento* da economia, são adotadas medidas macroprudenciais e de redução de gasto.
Após o entendimento de que esse diagnóstico foi inadequado, o governo Dilma passa a
aprofundar a direção do desenvolvimentismo.
De modo a superar os entraves mencionados anteriormente, adota-se uma agenda industrialista.
No centro da análise estava a necessidade de melhorar a competitividade industrial (pela desvalorização cambial) e a rentabilidade do investimento privado por meio de redução de custos (política monetária e fiscal). Vale notar que esta reordenação de prioridades foi feita sem que, para isso, fosse necessário abandonar a centralidade da questão social.

Alinhado com a agenda industrialista e em meio a retomada (súbita) dos fluxos de capital, a política cambial esteve no centro.
De modo a evitar a valorização e volatilidade do câmbio para melhorar a competitividade industrial, foram feitas intervenções no mercado interbancário.
Como resultado, reduziu a especulação pela apreciação e desprendeu o real do ciclo de liquidez internacional.
Contudo, a partir de 2014, em face de pressões para desvalorização, tais medidas de regulação cambial foram retiradas e a política cambial passou a contar
basicamente com intervenções no mercado de derivativos por meio de swaps cambiais e anuncia programa de leilões de câmbio
cite:cintraFinanciamentoContasExternas2015,melloIndustrialismoAusteridadePolitica.

Além do rompimento da valorização cambial enquanto instrumento de controle inflacionário, a *política monetária* também foi redirecionada para a agenda industrialista (sem romper com o RMI).
Na ausência de um padrão de financiamento autônomo de longo prazo, os bancos públicos foram acionados para reduzir a taxa de juros e os spreads bancários para facilitar o
financiamento do desenvolvimento.
Com redução da Selic e política cambial ativa, o controle de preços contou com o
represamento de preços administrados (com finalidade também de reduzir custos).
Na tentativa de ampliar o horizonte temporal do financiamento público, alterou-se o manejo da dívida pública substituindo LFTs por títulos pré-fixados para, assim, estimular o mercado de longo prazo. 


Em paralelo, fez-se uso da política fiscal por meio de incentivos, desonerações e concessões para promover investimento privado (em infraestrutura).
Além disso, é importante destacar que, na ausência de um padrão de financiamento autônomo de longo prazo, o financiamento ficou a cargo do setor público (BNDES).
Dentre as consequências, verificou-se uma deterioração do saldo fiscal cujo principal condicionante foi a redução das *receitas*.
No que diz respeito aos gastos, destaca-se uma redução do investimento público em que ampliou-se a participação relativa dos gastos com pessoal.
Assim, reduziu-se o efeito expansionista da política fiscal dada a concentração de gastos com menores multiplicadores fiscais.
** Conclusão e comparação geral
A título de conclusão, resta uma comparação geral.
Os governos FHC e parte do governo Lula são caracterizados pelo prosseguimento da agenda liberalizante em que o papel do Estado foi minorado.
Apedas de algumas continuidades, o governo Lula promoveu um ineditismo histórico: conjugação de crescimento com inclusão social.
Tal resultado --- levado adiante pelo governo Dilma --- decorre tanto da questão social quando do abandono progressivo do conservadorismo fical, reposicionando o papel do Estado no desenvolvimento.
Em conjunto, tais medidas promoveram uma dinamização do mercado interno e modernização da demanda que não foi acompanhada igualmente pela estrutura produtiva.
De modo a superar tais desafios, adotou-se uma agenda industrialista que, por sua vez, não foi industrializante.
Tal insucesso deve ser analisado além da conjuntura e da política econômico, incluindo elementos estruturais e de economia política.
