#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 212883 - Ana Pasti Villaba
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 212883
#+PROPERTY: NOME "Ana Pasti Villaba"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido satisfatoriamente
  :ARGUMENTO: Atingido parcialmente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingido satisfatoriamente
  :CLAREZA:  Atingido parcialmente
  :NOTA:     Atingido parcialmente
  :END:


** Comentários individuais 


Alguns pontos a serem destacados no início da sua resenha. Primeiramente, seria mais rigoroso dizer que o monetarismo é um escola e não um modelo. Por ser um questão menor não irei descontar nota em função disso. Seria interessante pontuar também o lugar dessa escola frente ao paradigma anterior (Síntese neoclássica). Mais ao fim, é colocado que os /ajustes econômicos/ formam expectativas adaptativas. Na verdade, são os *agentes*. A princípio, irei considerar como um erro de escrita. Caso isso persista ao longo da resenha (comento enquanto leio), considerarei como uma não compreensão do conceito.

No parágrafo seguinte é descrito o fenômeno de ilusão monetária sem antes discutir às hipóteses associadas à ele. Como existe ilusão monetária se os efeitos da expansão monetária forem persistentes? Como haverá retorno ao nível de desemprego natural se a velocidade de circulação da moeda não for constante? As perguntas que pontuei anteriormente são para levantar a reflexão de que a ilusão monetária é mais uma implicação associada à outras hipóteses e menos uma hipótese por si só (como pareceu a partir do seu texto).

Mais rigorosamente, para que a taxa de desemprego seja persistentemente menor que a natural, é preciso que o governo amplie a demanda agregada também persistentemente. Como consequência, há surpresa inflacionária. Daí em diante você descreveu corretamente o raciocínio econômico.

Em seguida, é apresentada a TQM. No entanto, pouco é dito sobre suas hipóteses. Além disso, dado o papel central da TQM, poderia ter sido apresentada antes. Com isso, seria possível explicar a ilusão monetária de forma menos expectacional. Mais ao fim (último parágrafo), você corretamente pontua a importância da hipótese de estabilidade de circulação da moeda para explicar a estabilidade macroeconômica e subsequente instabilidade decorrente da discricionariedade.

* Resenha 2: Novos Clássicos                                        :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido satisfatoriamente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingido satisfatoriamente
  :NOTA:
  :END:

** Comentários individuais

   Foram includos no documento enviado.
