#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 212900 - Ana Paula Martins
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 212900
#+PROPERTY: NOME "Ana Paula Martins"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingindo minimamente
  :ARGUMENTO: Atingindo minimamente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingindo minimamente
  :CLAREZA:  Atingido satisfatoriamente
  :NOTA:     Atingido parcialmente
  :END:

** Comentários individuais 

Após o parágrafo de abertura é apresentado o conceito de taxa natural de desemprego. No parágrafo seguinte, é discutido ``estabilização macroeconômica'' juntamente da flexibilidade de preços. Apesar de correta, esta discussão poderia ser um pouco mais rigorosa. Exemplos da falta de rigor/precisão:

- ``estabilização macroeconômica'' (poderia ser um pouco mais precisa)
- Taxa natural de desemprego poder se alterar por ``intermédio humano''. São os agentes isoladamente que podem alterar essa taxa? Política econômica? Pouco claro.
  - Mais adiante é detalhado o que quis dizer por ``intermédio humano''. De todo modo, fica registrado o comentário anterior.

Além disso, houve pouca adequação do texto aos objetivos da disciplina. Após a discussão da taxa natural de desemprego, é mencionado que variações no estoque de moeda alteram o nível de preços. No entanto, tal discussão é feita sem uma mediação teórica como a TQM. A importância dessa teoria se dá, especialmente, pelo tratamento teórico da demanda por moeda tal como proposto pelos monetaristas. Também é apresentado o conceito de ilusão monetária. No entanto, sem ter apresentados os pressupostos da TQM, tal discussão fica desconectada.

Em seguida, é mencionado que a autoridade lança mão da expansão inflacionária. Não muito por ai. O nível de preços não está sob o controle da política monetária, mas o nível de gastos do governo sim. O motivo pelo qual um aumento nos gastos do governo leva a um nível maior de preços está na convergência à taxa natural de desemprego bem como às hipóteses da TQM ainda não pontuadas. Adiante, é mencionado que as política monetária não tem efeitos no longo prazo, mas pouco é dito do porquê (esta "jogado"). No mesmo parágrafo a discussão das defasagens é pontuada corretamente. No entanto, a discussão de proposição de política econômica esta incompleta (nenhuma menção às regras monetárias).

No parágrafo seguinte, é contraposto o monetarismo com o keynesianismo ortodoxo em que é corretamente pontuada a importância da instabilidade do investimento. Ainda sim, cabe aqui uma sugestão. Ao longo da exposição da escola monetarista, não é feita nenhuma discussão à respeito da instabilidade dos componentes da demanda agregada (tampouco da TQM). Desse modo, a comparação fica comprometida em função da ausência de uma mediação entre ambas escolas. Uma forma de contornar isso seria por meio de uma exposição das hipóteses de cada corrente.

Adiante é mencionada a retomada da TQM pelo monetarismo. Cabe aqui a menção de que tal elemento é fundamental para essa escola e deveria ser exposta em maiores detalhes para que a construção dos argumentos desses autores fosse mais clara.
