#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 213731 - Bianca Senne Roma
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 213731
#+PROPERTY: NOME "Bianca Senne Roma"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido totalmente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido satisfatoriamente
  :DESENVOLVIMENTO: Atingido totalmente
  :CONCLUSAO: Atingido satisfatoriamente
  :CLAREZA:  Atingido totalmente
  :NOTA:     Atingido satisfatoriamente
  :END:

** Comentários individuais 


Em seu parágrafo de abertura é possível destacar que pontuou um dos elementos mais importantes dessa escola (TQM). Nos parágrafos seguintes dessa mesma página, é feita uma contextualização da escola analisada tendo em vista tanto o contraponto com o Keynesianismo ortodoxo quanto as interpretações da Grande Depressão. Vale aqui pontuar que a contextualização dos autores e dos livros resenhados (e não do monetarismo propriamente dito) podem ter comprometido a fluidez da resenha. É importante lembrar que a resenha crítica deve ter um propósito. Neste caso, o propósito não é exatamente resenhar Snowdown e Vane e Modenesi, mas sim a escola monetarista à luz da leitura desses autores sobre ela.

Em seguida, é corretamente pontuada a importância da TQM para o monetarismo e como variações no estoque de moeda estão entre os principais determinantes da inflação. No entanto, até o momento, pouco foi dito a respeito das suas hipóteses e implicações. A partir da sua exposição em que é destaca a inflação como fenômeno monetário, fica claro o porquê de se adotar regras monetárias. No entanto, existem hipóteses anteriores a essa conclusão que poderiam ser pontuadas. Adiante, é corretamente exposto o conceito de taxa natural de desemprego. No entanto, a ideia que tal taxa não é imutável poderia ser tratada de forma mais rigorosa (/i.e./ de forma mais precisa que ``ação humana'').

Adiante, é discutida a curva de Phillips Aceleracionista. Um adendo: cuidado ao impor causalidade que vai da hipótese das expectativas adaptativas à ilusão monetária. Os agentes poderiam formar expectativas de outra forma e ainda sim incorrer na ilusão monetária. O foco poderia recair mais sobre o que é tal ilusão decorre da confusão entre varições nominais e reais.
* Resenha 2: Novos Clássicos                                        :private:
  :PROPERTIES:
  :TAREFA:   Resenha 2
  :OBJETIVO: Atingido totalmente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido totalmente
  :DESENVOLVIMENTO: Atingido totalmente
  :CONCLUSAO: Atingido totalmente
  :CLAREZA:  Atingido totalmente
  :NOTA:     Atingido totalmente
  :END:

** Comentários individuais

   Foram includos no documento enviado.
