#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 222315 - Matheus Oliveira Lima
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 222315
#+PROPERTY: NOME "Matheus Oliveira Lima"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido totalmente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingindo minimamente
  :NOTA:     Atingido parcialmente
  :END:

** Comentários individuais 

Sua contextualização da escola monetarista esta bem colocado. No entanto, poderia ter sido um pouco mais claro. Uma forma de contornar isso seria por meio de frases mais curtas. Além disso, houve uma pequena imprecisão. Lei de Say não implica, por si só, pleno emprego. Para tanto, seria necessário lançar mão de outras hipóteses (substituição infinitesimal entre os fatores de produção, posso indicar literatura caso tenha interesse). Fica aqui o registro de que fez uma boa contextualização da importância do Friedman enquanto economista e enquanto "thinktanker". A seguir, descreveu quais são os determinantes da demanda por moeda, mas não mencionou a implicação dessas hipóteses: estabilidade[fn::Vi que mencionou isso adiante]. Adiante, ficou pouco clara a menção da moeda endógena. Para os monetaristas o estoque de moeda era controlado pela autoridade monetária (i.e exógeno). Mais a frente confunde a proposição de expansão dos agregados monetários como hipótese. Logo após, menciona as expectativas racionais (e não adaptativas) que, por sua vez, constituem a escola Novo Clássica. Apesar de apontar corretamente o que acontece com o nível de preços quando a economia opera sob a taxa de desemprego natural, incorre na imprecisão de que os agentes conseguem prever tal variável. Isso não ocorre no modelo monetarista. Os agentes não têm um modelo de como a economia funciona para guiar suas tomadas de decisão (/spoiler alert/: isso ocorrerá com os Novos Clássicos). Adiante, aparece a hipótese de expectativas racionais mais uma vez. Por fim, deixo registrada minha simpatia ao seu parágrafo de encerramento.
