#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 231898 - Beatriz Consolmagno de Marchi
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 231898
#+PROPERTY: NOME "Beatriz Consolmagno de Marchi"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido satisfatoriamente
  :ARGUMENTO: Atingido parcialmente
  :CONCEITOS: Atingido satisfatoriamente
  :DESENVOLVIMENTO: Atingido satisfatoriamente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingido satisfatoriamente
  :NOTA:     Atingido satisfatoriamente
  :END:

** Comentários individuais 

Após o parágrafo de abertura, corretamente associa a taxa natural de desemprego à hipótese de maximização das funções objetivo dos agentes. Adiante, corretamente pontua que a curva de Phillips aceleracionista esta relacionada à expectativa inflacionária. No entanto, não é discutido o porquê dessa inflação ser ``aceleracionista''. Sem seguida, é discutida a ilusão monetária em função das expectativas adaptativas. Mais precisamente, a hipótese de expectativas adaptativas é uma forma de simplificar a realidade enquanto a ilusão monetária é o fenômeno a ser explicado. Uma coisa não decorre necessariamente da outra tal como colocado na resenha. Os agentes podem formar expectativas adaptativas sem que exista ilusão monetária. Em seguida, a geração de inflação surpresa é tratada enquanto uma proposição. O argumento poderia ser construído de forma diferente: uma vez que a economia converge à taxa natural de desemprego e os agente sofrem de ilusão monetária, seria preciso que a autoridade monetária gerasse inflação persistentemente para que a taxa de desemprego permaneça abaixo da natural. Seu ponto esta correto, mas poderia ser apenas melhor articulado.

Adiante, são mencionados os argumentos contra a discricionariedade da política econômica bem como os contrapontos com a escola precedente. No parágrafo seguinte, é apresentada a TQM. Uma sugestão seria a de articular melhor as hipóteses e implicações da TQM (estabilidade da demanda por moeda) com as discussões anteriores. Com isso, pode-se entender melhor como uma expansão da base monetária geraria inflação e qual seria a proposição para evitar isso. Ao fim deste parágrafo, é pontuada as implicações da TQM e sua relação com a demanda por moeda, mas não é dada muita atenção a esse ponto.
