#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 233747 - Eduardo Ranieri Guedes Pinto
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 233747
#+PROPERTY: NOME "Eduardo Ranieri Guedes Pinto"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido satisfatoriamente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido satisfatoriamente
  :DESENVOLVIMENTO: Atingido totalmente
  :CONCLUSAO: Atingido satisfatoriamente
  :CLAREZA:  Atingido totalmente
  :NOTA:     Atingido satisfatoriamente
  :END:

** Comentários individuais 

Você corretamente pontuou a relevância da escola monetarista frente às anteriores. Adiante, você destacou a importância da retomada da TQM bem como a associou aos efeitos sobre variações no estoque de moeda. No entanto, pouco avançou na colocação das hipóteses da TQM como, por exemplo, estabilidade da circulação da oferta de moeda.

Em seguida, é afirmado que o monetarismo tem como principal *objetivo* a implementação de regimes monetários. Mais precisamente, esta é uma implicação de política econômica e não um objetivo preestabelecido. Em seguida, foi corretamente destacada a relação entre taxa de crescimento do produto e do estoque de moeda proposto pelo monetarismo. No entanto, não há nenhuma menção às hipóteses da TQM que permitem tal tipo de proposição (velocidade de circulação de moeda). Também é mencionada a taxa de desemprego natural e, em seguida, discutida sua relação com a inflação. 

Adiante, é destacado o retorno da taxa de desemprego efetiva à natural. No entanto, pouco é dito sobre os efeitos aceleracionistas sobre a inflação como resultado do distanciamento persistente entre o nível de desemprego efetivo e o natural. Apenas para te ajudar nessa explicação, imagine o seguinte: como o governo consegue manter o nível de desemprego menor que o natural? Via ampliação da demanda agregada por meio dos seus gastos. No entanto, como a taxa de desemprego converge à natural, é preciso que os governos gastem sempre mais para manter a taxa de desemprego menor. Qual o resultado? Inflação persistentemente maior. E qual a relação disso às hipóteses da TQM? a velocidade de circulação da moeda é relativamente estável enquanto a moeda é um ativo tal como os demais. Sendo assim, uma expansão da oferta de moeda só possui efeitos no curto prazo. O meu ponto é: expectativas adaptativas por si só não são capazes de explicar tanto a ilusão monetária quanto a neutralidade da moeda.

Logo depois, você corretamente associa a não recomendação de uma política monetária discricionária a outros elementos que não somente a ilusão monetária. Adiante, também foi relacionada à proposição de regras monetárias à não obstaculização da estabilidade econômica por distúrbios gerados pela política econômica.

Mais ao fim, foi colocada algumas críticas às hipóteses da TQM. No entanto, não foi pontuada em nenhum momento a importância dessas mesmas hipóteses na construção do argumento monetarista.
* Resenha 2: Novos Clássicos                                        :private:
  :PROPERTIES:
  :TAREFA:   Resenha 2
  :OBJETIVO: Atingido totalmente
  :ARGUMENTO: Atingido totalmente
  :CONCEITOS: Atingido totalmente
  :DESENVOLVIMENTO: Atingido totalmente
  :CONCLUSAO: Atingido totalmente
  :CLAREZA:  Atingido totalmente
  :NOTA:     Atingido totalmente
  :END:

** Comentários individuais

   Foram includos no documento enviado.


* Resenha 3: Novos Keynesianos :private:
  :PROPERTIES:
  :TAREFA:   Resenha 3
  :OBJETIVO: Atingido parcialmente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido satisfatoriamente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingido satisfatoriamente
  :NOTA:     Atingido satisfatoriamente
  :END:

** Comentários individuais

   Foram includos no documento enviado.

