#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 237618 - João Pedro de Paula e Silva
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 237618
#+PROPERTY: NOME "João Pedro de Paula e Silva"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido totalmente
  :ARGUMENTO: Atingido totalmente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingido satisfatoriamente
  :NOTA:     Atingido satisfatoriamente
  :END:

** Comentários individuais 

Você bem colocou a escola monetarista enquanto contraponto ao paradigma que o antecede. Em seguida, você destaca que esta escola parte da /hipótese/ de que a política monetária (mais precisamente variações na oferta de moeda) não possuem efeitos reais (a longo prazo) sobre a economia. No entanto, pouco desenvolveu o porquê disso. Existem hipóteses que fazem com que esse resultado ocorra.

Em seguida, são destacadas as hipóteses de expectativas adaptativas bem como a existência de uma taxa natural de desemprego. Apesar de corretas, ambas hipóteses são insuficientes para explicar o porquê de mudanças na oferta de moeda implicam efeitos temporários sobre a economia real. De toda forma, você apresentou ambas corretamente.

Em relação à curva de Phillips, fica um questionamento: a ausência do /trade-off/ entre nível de preços e taxa de desemprego é uma hipótese ou implicação do ``modelo monetarista''? Adiante, você apresentou a relação entre a Curva de Phillips aceleracionista com o conceito de ilusão monetária. Logo depois, há um salto em que você discute a redução do nível de bem-estar da sociedade. Como este não é o propósito da resenha nem da disciplina, não vou me alongar aqui.

No parágrafo seguinte, você menciona a TQM, mas vai pouco além. Por mais que a TQM é proposta por outras escolas que são anteriores ao monetarismo, seu resgate e às hipóteses associadas à ela são fundamentais para explicar as implicações da variação da oferta de moeda. Caberia aqui pontuar mais sua relevância. Exemplo disso é: como explicar a proposição de regime monetário sem ter como pressuposto que a velocidade de circulação da moeda é estável?

No parágrafo final, você entra em alguns debates sem as devidas mediações. Primeiramente é importante pontuar que esse esforço de conectar uma discussão dos países centrais aos problemas e particularidades da periferia é louvável. No entanto, você está discutindo (mesmo que de forma não intencional) diferentes teorias da inflação e um mesmo texto sem fazer muitas concessões. Por exemplo: ao discutir inflação nos países periféricos em razão dos preços importados, você está associando aumento de preços aos elementos do lado da oferta e não da demanda (como fazem os monetaristas). Apesar dessa minha ressalva, não irei descontar nota em função dessa discussão final. Por fim, fica expresso aqui meu reconhecimento de fazer uma leitura crítica do tema proposto. Apenas se atente às transições e mediações entre os temas.
* Resenha 2: Novos Clássicos                                        :private:
  :PROPERTIES:
  :TAREFA:   Resenha 2
  :OBJETIVO: Atingido totalmente
  :ARGUMENTO: Atingido totalmente
  :CONCEITOS: Atingido totalmente
  :DESENVOLVIMENTO: Atingido totalmente
  :CONCLUSAO: Atingido satisfatoriamente
  :CLAREZA:  Atingido totalmente
  :NOTA:     Atingido totalmente
  :END:

** Comentários individuais

   Foram includos no documento enviado.
* Resenha 3: Novos Keynesianos                                        :private:
:PROPERTIES:
:TAREFA:   Resenha 3
:OBJETIVO: Atingido totalmente
:ARGUMENTO: Atingido totalmente
:CONCEITOS: Atingido totalmente
:DESENVOLVIMENTO: Atingido totalmente
:CONCLUSAO: Atingido totalmente
:CLAREZA:  Atingido totalmente
:NOTA:     Atingido totalmente
:TURNITIN:
:END:

** Comentários individuais

Foram includos no documento enviado.
