#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 255207 - Fernanda Lima Santos
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 255207
#+PROPERTY: NOME "Fernanda Lima Santos"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido satisfatoriamente
  :ARGUMENTO: Atingido parcialmente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido satisfatoriamente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingido satisfatoriamente
  :NOTA:     Atingido parcialmente
  :END:

** Comentários individuais 

Em seu parágrafo de abertura estão alguns dos principais conceitos que compõem o monetarismo (tipo I). No entanto, existem algumas imprecisões. Dentre elas é a de que a política monetária não possui efeitos reais. Sua colocação esta quase correta. O correto seria dizer que a política monetária (e a moeda) não afetam variáveis reais no *longo prazo*. A curto prazo, os distúrbios monetários, defasagens e ilusão monetária afetam o nível de emprego e renda. Foi corretamente apresentada a proposição de regras monetárias fixas. Para ser mais completo, poderia mencionar a TQM, conceito fundamental para chegar a esses resultados.

Ao apresentar a taxa natural de desemprego, foi corretamente pontuado que esta pode se alterar em função de medidas de política econômica do lado da oferta. De modo geral, este parágrafo esta correto. No entanto, ao dizer que na ausência de distúrbios monetários, a taxa de desemprego convergiria a natural (que esta correto), contradiz seu parágrafo anterior ao dizer que a moeda é neutra (sem especificar a temporalidade).

Quando apresentou a curva de Phillips com expectativas, incorreu em uma imprecisão. Seria mais corretor dizer que para cada expectativa existe uma curva de Phillips e não o inverso (como esta na resenha). Mais adiante é mencionado que as flutuações econômicas são resultado de erros expectacionais. Esse ponto esta um pouco incompleto. Tem razão ao dizer que as expectativas geram tais flutuações, mas para os monetaristas tais flutuações são geradas principalmente por distúrbios monetários (que podem fazer com que as expectativas sejam erradas, eis a ilusão monetária).

Ao explicar a curva de Phillips aceleraciosnita, confunde resultado com hipótese. Os monetaristas não partem da hipótese de que é precisa inflação à taxas maiores para que a taxa de desemprego fique abaixo da natural. Isso que descrevi é a implicação (decorrente de um conjunto de outros hipóteses, dentre elas às da TQM).

Ao descrever as recomendações de política econômica, pontua corretamente os pontos contrários a discricionariedade. No entanto, não há menção sobre as regras monetárias propostas. No final da sua resenha é apresentada a TQM. Dada a importância desta teoria e suas hipóteses relacionadas, poderia ter sido antecipada. Note que a partir dela é possível descrever o porquê de variações no estoque de moeda implicam variações na inflação.
