#+TITLE: Referee Report
#+OPTIONS: toc:nil
#+AUTHOR:
#+LATEX_HEADER: \renewcommand{\abstractname}{Overview and Recommendation}
#+LATEX_HEADER: \bibliography{./refs.bib}

#+BEGIN_SRC bib :tangle ./refs.bib :exports none
@article{serrano_long_1995,
	title = {{Long} {Period} {Effective} {Demand} {and} {the} {Sraffian} {Supermultiplier}},
	volume = {14},
	issn = {1464-3588, 0277-5921},
	url = {https://academic.oup.com/cpe/article/428995/LONG},
	doi = {10.1093/oxfordjournals.cpe.a035642},
	language = {en},
	number = {1},
	urldate = {2018-12-20},
	journal = {Contributions to Political Economy},
	author = {Serrano, Franklin},
	year = {1995},
	pages = {67--90}
}

@incollection{duesenberry_investment_1958,
	series = {Economic {Handbook} {Series}},
	title = {Investment in housing},
	booktitle = {Business cycle and economic growth},
	publisher = {McGraw-Hill},
	author = {Duesenberry, James S.},
	year = {1958}
}


@techreport{girardi_autonomous_2015,
	title = {Autonomous demand and economic growth:some empirical evidence},
	shorttitle = {Autonomous demand and economic growth},
	url = {https://ideas.repec.org/p/usi/wpaper/714.html},
	abstract = {According to the Sraffian supermultiplier model, economic growth is driven by the autonomous components of aggregate demand (exports, public spending and autonomous consumption). This paper tests empirically some major implications of the model. For this purpose, we calculate time-series of the autonomous components of aggregate demand and of the supermultiplier for the US, France, Germany, Italy and Spain and describe their patterns in recent decades. We observe that changes in output and in autonomous demand are tightly correlated, both in the long and in the short-run. The supermultiplier is substantially higher and more stable in the US, while in the European countries it is lower and strongly decreasing. Consistently with theory, we find that where the supermultiplier is reasonably stable - i.e., in the US since the 1960s - autonomous demand and output share a common long-run trend (i.e, they are cointegrated). The estimation of a Vector Error-Correction model (VECM) on US data suggests that autonomous demand exerts a long-run effect on GDP, but also that there is simultaneous causality between the two variables. We propose an explanation based on the idea that autonomous demand is socially and historically determined. We then estimate the multiplier of autonomous spending through a panel instrumental-variables approach, finding that a one dollar increase in autonomous demand raises output by 1.6 dollars over four years. A further implication of the model that we test against empirical evidence is that increases in autonomous demand growth tend to be followed by increases in the investment share. Through Granger-causality tests and instrumental variables analysis, we find that this is the case in all five countries. An additional 1\% increase in autonomous demand raises the investment share by 0.57 percentage points of GDP in the long-run},
	language = {en},
	number = {714},
	urldate = {2018-12-20},
	institution = {Department of Economics, University of Siena},
	author = {Girardi, Daniele and Pariboni, Riccardo},
	year = {2015}
}

@article{girardi_long-run_2016,
	title = {Long-run {Effective} {Demand} in the {US} {Economy}: {An} {Empirical} {Test} of the {Sraffian} {Supermultiplier} {Model}},
	volume = {28},
	issn = {0953-8259, 1465-3982},
	shorttitle = {Long-run {Effective} {Demand} in the {US} {Economy}},
	url = {https://www.tandfonline.com/doi/full/10.1080/09538259.2016.1209893},
	doi = {10.1080/09538259.2016.1209893},
	language = {en},
	number = {4},
	urldate = {2019-05-25},
	journal = {Review of Political Economy},
	author = {Girardi, Daniele and Pariboni, Riccardo},
	month = oct,
	year = {2016},
	keywords = {Pendente},
	pages = {523--544}
}



@article{huang_is_2020,
	title = {Is {Housing} the {Business} {Cycle}? {A} {Multiresolution} {Analysis} for {OECD} {Countries}},
	issn = {10511377},
	shorttitle = {Is {Housing} the {Business} {Cycle}?},
	url = {https://linkinghub.elsevier.com/retrieve/pii/S1051137720300280},
	doi = {10.1016/j.jhe.2020.101692},
	language = {en},
	urldate = {2020-07-08},
	journal = {Journal of Housing Economics},
	author = {Huang, Yuting and Li, Qiang and Liow, Kim Hiang and Zhou, Xiaoxia},
	year = {2020},
	pages = {101692}
}


@article{arestis_economic_2019,
	title = {Economic precariousness: {A} new channel in the housing market cycle},
	volume = {24},
	shorttitle = {Economic precariousness},
	url = {https://ideas.repec.org/a/wly/ijfiec/v24y2019i2p1030-1043.html},
	abstract = {Demographic and institutional elements, as important drivers of the housing market, should not be neglected because it is not only financial and monetary elements that matter in the case of the housing market. In this context, one relationship, which still remains unclear, is the relationship between the housing and the labour markets. Some research has been undertaken to support the hypothesis that high rates of homeownership lead to high unemployment via increases in the reservation wage. However, further research is needed to address the possible implications of the institutional settings of the labour market in the dynamics of the housing market. The aim of this paper is to bring some light on the link between both markets. In particular, this contribution explains how the housing cycle could be “amplified” via a new channel, that is, economic precariousness, which is closely related to job insecurity. Subsequently, we provide evidence in the case of five developed economies, Ireland, the Netherlands, Spain, the United Kingdom, and the United States, over the period 1985–2013.},
	language = {en},
	number = {2},
	urldate = {2019-07-16},
	journal = {International Journal of Finance \& Economics},
	author = {Arestis, Philip and Gonzalez‐Martinez, Ana Rosa},
	year = {2019},
	pages = {1030--1043}
}
#+END_SRC

\noindent *Manuscript:* Residential Investment as a Luxemburg-Kalecki External Market in the United States: An Empirical Investigation

#+BEGIN_abstract
The manuscript contributes to the empirical literature on Non-Capacity Creating Autonomous Expenditure (NCCAE, now on). In summary, the author(s) find empirical support for nonlinear relationship between the analyzed variables and conclude that Residential investment leads both the business cycle and the economic trend for the US. This topic is relevant and the proposed method is quite recent and innovative. However, there are a few theoretical drawbacks therefore my recommendation is for *re-submission* of the manuscript.

The paper has four main sections. Section 2 analyzes the empirical literature and points out the macroeconomic relevance of residential investment (RES, now on); section 3 complements the previous one and discuss the theoretical demand-led growth literature and emphasizes the compatibility of RES with the Sraffian Supermultiplier Model (SSM); section 4 presents the data, methodology and empirical strategy in order to evaluate nonlinear causality relationship between RES and GDP in a frequency domain framework. Section 5 presents the results. Since the methodology is well described, I will focus on the links between the empirical sections (4 and 5) with the theoretical ones (2 and 3).
#+END_abstract


1. Section 2 reviews the empirical literature on residential investment and emphasizes its macroeconomic relevance. In this same section, different RES-related topics are discussed without theoretical mediation. For instance, orthodox and heterodox models are discussed altogether.
   - For example, textcite:arestis_economic_2019 is mentioned in the same paragraph with orthodox scholars and there is little mediation between them (page 4).
2. Still in section 2, there are many references to section 3 in which the theoretical model is discussed. It would be better to anticipate this topic to clarify the empirical literature review (section 2).
3. In this same section, there are some incompatibilities between empirical evidence discussed and the hypothesis employed. For example, the author(s) mention \citeauthor*{arestis_economic_2019}'s \citeyear{arestis_economic_2019} result in which the level of RES depends on real disposable income. However, on the following paragraph (page 4), the author(s) state(s) that RES may be considered as a NCCAE.

   - To be fair, there are few works that discuss if RES could be considered as an autonomous expenditure. That been said, it would be interesting to argue a little more about this topic.
   - On page 2, it would be better to explicit NCCAE characteristic of RES in terms of wages (income generated from firms, as textcite:serrano_long_1995 does) instead of arguing that RES moves independently of output.
   - To prevent critiques such as the previous one, the following sentence (page 7) could be anticipated (or even more emphasized): ``we do not try to provide a complete and thorough validation of autonomous demand-led growth models here''.

4. Although the data and empirical strategy are discussed in section 4, there is no mention of why the US was chosen nor the time range adopted (1960-2019:2). Since the empirical review shows that the relevance of the RES is not restricted to the US nor to the Great Recession, the author(s) could elaborate more. Additionally, it would be interesting to present some RES-related stylized facts.

5. Section 3 discusses the theoretical demand-led growth literature and emphasizes the compatibility with SSM model. In this section, the author(s) argues that RES can be treated as NCCAE, but there is no theoretical discussion about this.

   - Additionally, from theoretical literature review, it is not clear that SSM literature investigates long-run (fully-adjusted position) relations. This discussion would clarify why RES could determine the GDP trend and not only the business cycle.

6. A more problematic issue is that there is no further discussion about `Luxemburg-Kalecki external market' despite it being on manuscript title. I recommend a brief discussion about this topic since it is relevant for the research proposal.

7. There is no mention in section 3 about why RES and GDP growth should have a nonlinear structure (which is a relevant assumption for the methodology employed). However, the results presented in section 5 supports this specification, so this is not a problematic issue.

   - textcite:duesenberry_investment_1958, for instance, states that RES should evolve independently of output (/i.e./ is a NCCAE) mainly when investors speculate with real estate. Therefore, there are theoretical foundations for both autonomous and nonlinear relation between RES and GDP. That been said, I recommend a brief discussion on this in section 3.

   - At the very beginning of section 4.4, it is stated that (page 11): ``[E]conomic events, such as changes in the economic environment, changes in monetary and/or fiscal policy, etc., can create room for a nonlinear (rather than linear) relationship between RES and GDP.'' However, there is no such discussion on section 4.3. More precisely, it is mentioned (page 9) that the literature (without citing any scholar) ``has widely recognized that macroeconomic variables and processes have nonlinear structures''. At the end of this same paragraph, it is mentioned that: ``nonlinearity is endemic in the social sciences and that asymmetry is fundamental to the human condition''. This topic is no longer discussed and there is no further mediation to manuscript proposal.

8. Repeating the same quote  of \textcite[p.~71]{serrano_long_1995} (manuscript page 6), the following expenditures are supposed to be considered as autonomous: ``the consumption of capitalists; the discretionary consumption of richer workers that have some accumulated wealth and access to credit; [...]''. Besides controlling for some  NCCAE on the econometric model (section 5), there is no mention of the absence of autonomous consumption.

   - Other scholars, for instance, excluded consumer credit in order to improve the estimation as textcite:girardi_long-run_2016 (reference mentioned in section 2, page 7).

9. Section 4 presents the empirical strategy adopted and discusses the chosen procedures formal and rigorously.  However, there is no mention of the (theoretical) expected parameter values (mentioned on page 18). I recommend a brief discussion about this in section 3.

10. Both sections 4 and 5 do not specify whether RES and GDP are considered level or growth rate variables. On page 7 (section 4), for example, it is unclear if RES is a percent change or a level variable. Table 1 suggests that all variables employed are level terms while Tables 4 and 5 suggest  the opposite (as well as pages 7,21-22).

    - The script provided with this referee (data_checker.py) concludes that variables reported in Table 1 are in level terms. Additionally, this table is not mentioned in the manuscript. It would be interesting to reference this table and emphasize that variables are transformed into logarithms.

11. Section 5 presents the results, but there is no comparison with the empirical evidence presented in section 2. This discussion would be interesting since textcite:huang_is_2020 also employ a frequency-domain framework in orthodox strands and report different results.

12. Finally, a friendly suggestion. In order to emphasize the econometric results and to follow the ``housing tradition'', the manuscript title could be: ``Housing is NOT ONLY the business cycle: a Luxemburg-Kalecki External Market empirical investigation for the United States (1960-2019)''.

    - Of course, this is an optional suggestion in order to explicitly describe what are the conclusions, time range, and theoretical literature adopted.


Considering the items discussed above, I recommend the *re-submission* of the manuscript.

* References
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+LATEX: \printbibliography[heading=none]

