#+TITLE: Recommendation letter after authors' review 
#+OPTIONS: toc:nil
#+AUTHOR: Journal Manuscript No. 2020/63
#+LATEX_HEADER: \renewcommand{\abstractname}{Overview and Recommendation}

\noindent *Report on* "Housing is NOT ONLY the Business Cycle: A Luxemburg-Kalecki External Market Empirical Investigation for the United States" 


#+BEGIN_abstract
As mentioned before, the manuscript contributes to the empirical housing-related literature and reports interesting results based on quite  new methodology.
The authors properly adapted the manuscript as suggested.
However, there are some structural flaws and redundancies therefore my recommendation is to *approve* the manuscript with minor *revisions*.
The following topics are on this direction.
#+END_abstract

1. The new abstract is clearer and more accurate than the previous version.
2. Some paragraphs in the Introduction (Section 1) seems to be more adequate in Section 3 and presents some redundancies.
   - This is the case in paragraph 1, page 2 which is quite similar with paragraph 1 page 8.
   - Since the theoretical model will be presented in section 3, I suggest discussing Luxemburg-Kalecki External Market without going into too much detail in the Sraffian supermultiplier model.
3. Empirical literature review (Section 2) is better organized
   - A suggestion is to present the review in a table. In doing this, it is possible to highlight the empirical, methodological and theoretical gap
   - X-axis in Figure 1 (page 2) is not in standard datetime (month/day/year) format.
   - There are different citation entries for the same paper (Huang et al 2018 and Huang et al 2020).
   - Time span selection and consumer credit exclusion are more explicit now
     - Additionally, I would suggest to explicitly indicate FRED data series code instead of pointing that all the data was retrieved from FRED database. 
   - Table 1 does not have a proper caption. It is not clear that variables are in log. Maybe changing "(see Table 1 for the summary statistics of them)" to the end of the paragraph is enough.
4. Methodology presentation (Section 4, mainly 4.4) is clearer than previous version
   - Section 4.2 is unnecessary. The reference to Table 2 in Section 5 (page 16) seems to be enough.
     + It is worth noting that moving part of methodology discussion to the appendix has improved the reading
5. In Section 5, after pointing out the differences with existing empirical literature, it would be interesting to compare with Huang et al. (2020) conclusion in more detail in order to highlight the theoretical divergences since it is argued that they report that (p. 5) "housing factors [...]   autonomously drive the business cycle in the US"

@@latex:\noindent@@ Considering the items discussed above, I recommend to *approve* the manuscript *with minor revisions*.

