* Capas                                                              :ignore:

#+BEGIN_EXPORT latex
\pretextual
\frenchspacing
	
\frontmatter
\pagenumbering{roman}
\imprimircapa 
\stepcounter{page} % Adicionando a numeração em um. Motivo: folha de rosto possui numeração repetida em relação à capa. https://tex.stackexchange.com/questions/416589/how-to-increment-page-number-by-one
\imprimirfolhaderosto
\nopagebreak
#+END_EXPORT
 
* Ficha Catalográfica                                                :ignore:
#+BEGIN_EXPORT latex
% 2020-09-09: Criando minipage para evitar que uma página em branco seja criada antes e depois da ficha catalográfica. Deve ser incluido um \newpage após minipage para evitar sobreposição.
% Atenção: Ficha catalográfica não aparece no Okular.
\begin{minipage}{\textwidth}
\begin{fichacatalografica}
	\begin{center}
		\includepdf[pagecommand={\thispagestyle{empty}},pages=1]{./figs/Fake_Ficha_Catalografica.pdf}
	\end{center}
\end{fichacatalografica}
\end{minipage}
\newpage
#+END_EXPORT

* Folha de aprovação                                                 :ignore:
#+BEGIN_EXPORT latex
% 2020-09-09: Criando minipage para evitar que uma página em branco seja criada antes e depois da folha de aprovação. Deve ser incluido um \newpage após minipage para evitar sobreposição.
\begin{minipage}{\textwidth}
\begin{folhadeaprovacao}
	\begin{center}
		\includepdf[pagecommand={\thispagestyle{empty}},pages=1]{./figs/Fake_Folha_Aprovacao.pdf}
	\end{center}
\end{folhadeaprovacao}
\end{minipage}
\newpage
#+END_EXPORT

* Dedicatória                                                        :ignore:
#+BEGIN_EXPORT latex
\begin{dedicatoria}
\thispagestyle{empty} % 2020-09-09: Tal como dissertação para homologação
	\vspace*{\fill}
	\centering
	\noindent
	\textit{Pela comunidade, para a comunidade}
	\vspace*{\fill}
\end{dedicatoria}
#+END_EXPORT

* Agradecimentos                                                     :ignore:
#+BEGIN_EXPORT latex
\begin{agradecimentos}
\thispagestyle{empty} % 2020-09-09: Tal como dissertação para homologação
Agradeço a todo mundo
\end{agradecimentos}
#+END_EXPORT

* Resumo e Abstract                                                  :ignore:

#+BEGIN_EXPORT latex
\begin{resumo}
\thispagestyle{empty} % 2020-09-09: Tal como dissertação para homologação
\begin{otherlanguage*}{portuguese}

Esta dissertação investiga a relação entre investimento residencial, inflação de ativos e dinâmica macroeconômica no médio prazo com base no caso americano no pós-desregulamentação financeira (1992-2019).
No primeiro capítulo, é feita uma revisão da literatura dos modelos de crescimento liderados pela demanda, elencando o supermultiplicador sraffiano (SSM) como o mais pertinente para atender os objetivos desta pesquisa.
No capítulo seguinte, avança-se em direção da discussão empírica e é estimado um modelo vetor de correção de erros (VECM) para testar a capacidade explicativa da taxa própria de juros dos imóveis.
No terceiro capítulo, é simulado um modelo \textit{Stock-Flow Consistent} com supermultiplicador sraffiano (SSM-SFC) com inflação de ativos em que se
prioriza a parcimônia de modo a representar uma economia fechada e sem governo com famílias trabalhadoras e capitalistas em que somente estas últimas têm acesso a crédito para financiar tanto o consumo quanto o investimento residencial.
A especificidade deste modelo é a existência do estoque de capital das firmas (criador de capacidade produtiva) e das famílias
cuja participação deste último se reduz dado um aumento na taxa de crescimento do investimento residencial.
Adicionalmente, são introduzidos alguns dados observados para simular ciclos econômicos.
Conclui-se que a taxa própria de juros dos imóveis explica a taxa de crescimento residencial empiricamente e que o modelo SSM-SFC reproduz alguns fatos estilizados da economia norte-americana.



\vspace{\onelineskip}

\noindent\textbf{Palavras-chave}: 
	Supermultiplicador Sraffiano; 
	Investimento residencial; 
	Taxa própria de juros; 
	Modelo Vetor Correção de Erro;
	Consistência entre fluxos e estoques.
\end{otherlanguage*}
\newpage

\begin{otherlanguage*}{english}
	\thispagestyle{empty}
	\begin{center}{\ABNTEXchapterfont\huge Abstract}\end{center}
	
	This thesis investigates the relationship between residential investment, asset inflation, and medium-term macroeconomic dynamics based on the US post-deregulation case  (1992-2019). 
	The first chapter presents a review of demand-led growth models, choosing the Sraffian supermultiplier (SSM) as the best one to achieve the objectives of this research. 
	In the following chapter, we move towards the empirical discussion and estimate a vector error correction model (VECM) to test the explanatory capacity of real interest rate of real estate. 
	In the third chapter, a Sraffian Supermultiplier Stock-Flow Consistent model (SSM-SFC) with asset inflation is simulated prioritizing parsimony to represent a closed and without government economy with working and capitalist households in which only the latter have access to credit to finance both consumption and dwellings. 
	The specificity of this model is the existence of firms' (capacity creating) and households' capital stock  whose participation of the latter is reduced given an increase in the growth rate of residential investment. 
	Additionally, some observed data are introduced to simulate economic cycles. 
 	We conclude that housing own interest rate explains residential investment growth rate empirically and that the SSM-SFC model reproduces some stylized facts of the US economy.
	
	\vspace{\onelineskip}
	
	\noindent\textbf{Keywords}: Sraffian Supermultiplier; real state, own interest rate, Vector Error Correction Model, Stock-Flow Consistent Approach. 
	
\end{otherlanguage*}
\end{resumo}
#+END_EXPORT

* Epígrafe                                                           :ignore:

#+BEGIN_EXPORT latex
\begin{epigrafe}
\thispagestyle{empty} % 2020-09-09: Tal como dissertação para homologação
	\vspace*{\fill}
	\begin{flushright}
		\textit{``Não está ao meu alcance criar uma sociedade ideal. Contudo, está ao meu alcance descrever o que, na sociedade existente, não é ideal para nenhuma espécie de existência humana em sociedade.''\\
			(Florestan Fernandes)}
	\end{flushright}
\end{epigrafe}

\newpage
#+END_EXPORT

* Índice e numeração                                                 :ignore:

#+BEGIN_EXPORT latex
\pdfbookmark[0]{\listfigurename}{lof}
\listoffigures*
\addcontentsline{toc}{chapter}{List of Figures}
\thispagestyle{empty}
\newpage
\pdfbookmark[0]{\listtablename}{lot}
\listoftables*
\addcontentsline{toc}{chapter}{List of Tables}
\thispagestyle{empty}
\newpage
\addcontentsline{toc}{chapter}{List of Variables}
\input{./abnt/list_variables.tex}
\thispagestyle{empty}
\newpage

\tableofcontents*
\thispagestyle{empty}
#+END_EXPORT

* Mainmatter                                                         :ignore:
#+BEGIN_EXPORT latex
\mainmatter
\cleardoublepage
\pagestyle{plain} % restore the plain style
\renewcommand{\thepage}{\arabic{page}}  % Setting the page output to arabic   -- not necessary, unless `book` class and `\frontmatter` is used.
#+END_EXPORT



