* Sraffianismo Tardio
** 2020-07-03: Apresentação Luiz - Supermultiplicador e Thirwall: Convergências
*** Discussão das funções de importação
Apresenta problematização e demostração matemática de Gandolfo (2016). 
Avalia se existe uma trajetória compatível com o modelo de Thirwall.
Adiciona prorção das exportações das importações ($\beta$):

$$
\beta = \frac{X}{M}
$$

É incluida a taxa de variação dos termos de troca ($r$).
Normalmente, supõe-se que $r=0$ e $\beta=1$
Luiz mostra que é possível demonstrar a compatibilidade entre o supermultiplicador e Thirwall dada algumas simplificações.
Além disso, se $g_Z > g_X$, há problema  de balanço de pagamentos enquanto o inverso implica acúmulo de reservas.
*** Problemas
Se não parte do equilíbrio BP, a economia não convergirá para este espaço. 
A literatura (Moreno Bride, 1998) tem indicado que há algum ajustamento exógeno ao BP.
Proposta de ajustamento de Gandolfo:

$$
\dot y = \xi(y^{*} - y_t)
$$ 
É um ajustamento teórico, ou seja, deve existir.
Dito isso, supõe-se que esse ajustamento existe e tenta encontrar uma trajetória desse $\xi$
Conclui que depende de $\pi$ (elasticidade-renda das importações):

- Se $\pi = 1$: O sistema tende para uma constante arbitrária que não permite definir uma trajetória
- Se $\pi < 0$: O sistema possui um braço estável e outro instável (ponto de sela)
  - Neste caso, a Lei de Thirwall se torna apenas um teto e não está relacionado com nenhuma trajetória
- Se $\pi > 1$: O sistema é estável
  - Mas este não é o caso para a maioria dos países

Resolvendo para o equilíbrio de Thirwall e $\beta = 1$


A literatura tem encontrado condições ainda mais restritivas para validade da trajetória do modelo de Thirwall.
Como é o caso de que $\pi = 1$.


*Problemática de Luiz:* É possível que um modelo com mais de um gasto autônomo seja compatível com o modelo de Thirwall.
*** Modelo supermultiplicador com exportadores conspícuos
**** Pressupostos:
     - Dois países: um país pequeno que produz bens simples e bens de capital suficientes para atender a demanda interna
       - Ajustamento do estoque de capital não inclui exportações
     - Importa bens intermediários e bens de luxo
     - Há um ajustamento entre o estoque de capital e a demanda, por meio do princípio acelerador
     - Os capitalistas exportadores podem consumir e importar bens de luxo produzidos externamente (autônomo)
       - $Z = M$
     - Capitalistas exportadores mimetizam consumo das elites do país que produz bens de luxo
     - Não há restrição de mão de obra


** 2020-07-20: Projeto Gabriel - Comentários

*** Introdução e Gerais


*** Ensaio 1

- Hipotecarização não está associado ao preço dos imóveis?
  - Ver Piketty

**** Contexto

**** Objetivo

**** Hipótese

**** Metodologia

*** Ensaio 2
    
- Peter Skott: Processo de bolha seria neutro por que oscila em torno de uma média, logo, não teria efeitos sobre crescimento (cíclico apenas)
  - Contraponto: Bolhas gerariam efeitos não-neutros
- Jordà: Bolhas alavancadas -> Vários tipos de bolhas: Mais severas com bolhas imobiliárias
  - Recessões afetam taxa de crescimento? Altera a média de crescimento?
  - Ligar com a literatura

**** Contexto

**** Objetivo

**** Hipótese

**** Metodologia

*** Ensaio 3

- Analisar relação dívida sobre a renda
- Introduzir heterogeneidade de taxa de juros.
- Inter-relação entre setores
  - Governo crescendo a uma taxa diferente
    - Possibilidade de gerar instabilidade exogenamente por mudanças na política fiscal
  - E investigar endividamento privado
  - Política fiscal geral instabilidade financeira (não apenas emergir das famílias)
- Gastos autônomos crescendo à taxas diferentes
- Ciclo de crédito não é endógeno se a bolha de ativos é exógena
  - Dar menos atenção ao ciclo de crédito endógeno
    - Substituir por racionamento de crédito (Stiglitz)

**** Contexto

**** Objetivo

**** Hipótese

**** Metodologia




* Tese

** 2020-07-04: Discussão projeto fapesp
   - Motivação não é uma questão pessoal
     - Diz respeito a como ela se encaixa na literatura e como contribui
*** Ensaio 3
    - Hipotecarização como algo relevante do sistema bancário
*** Introdução
    - Primeiro parágrafo problemático
    - Tirar motores: importância macroeconomica da consumo
    - Não é que estou propondo um novo conceito.
      - É um conjunto de temas usados esse tema por simplicidade
*** Ensaio 1
    - Países com instituições distintas tem um mesmo fenômeno
*** Ensaio 2
    Falar que vai analisar a inflação de ativos e não a taxa própria no vec

* Artigos

** VECM

*** <2021-03-22 seg> Seção 4
**** Tirar taxa de juros real da figura 6
**** Seção 4.1 mais direta com o ponto
**** Abrir seção 4.2 com as equação 3
***** Mocumentary com cointegração
***** Começar com teste de cointegração antes de apresentar a equação 3
***** Transformação de yeojohson
**** Problema, não esta discutindo especulação e bolhas
**** PDF com todos os gráficos que não foram utilizados para o Franklin
**** Taxa própria parece a taxa própria do Sraffa: deflaciona juros adequado com preço adequado em uma forma funcional mais simples possível
**** Tudo que é estratégia de estimação vai para a 4.2
**** Transformar figura 8 em apêndice
**** Final seção 3 com apenas uma frase
**** Olhar forma dos outros artigos empíricos para estruturar a seção 4.2
**** Testar para o fim de 2019
***** Pós envio ao Franklin
***** Rever data com a quebra estrutural
**** Figura 7 para anexo; informação da figura 8 no texto e figura 9 fora
**** Lucas: fundamentação econômica das defasagens; autonomia da taxa própria em relação ao investimento residencial (Marcar)
**** Mesclar 4.3 com 4.4 e checar se é necessário comparar com a literatura
**** Tirar nome do Franklin
**** Ver interpretação dos coeficientes de longo-prazo
***** Ver Perez-Montiel
**** Citar paper SFC
**** Reduzir notas de rodapé
**** Remover figura 5
