---
title: "VEC"
author: "gpetrini"
date: "19/05/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE,
    warning = FALSE
    )
```

# Pacotes

```{r}
library(dplyr)
```


# Dados

```{r}
df <- read.csv(
    "../data/raw_data.csv", 
    encoding="UTF-8", 
    row.names=1, 
    stringsAsFactors=FALSE
    )
df <- df[,c( # Subset das colunas com ordenação de Choleski
    "Exportações.FOB",
    "Taxa.de.câmbio",
    "Importações.FOB",
    "Índice.da.Produção.Física.Industrial.com.ajuste.sazonal..Média.2012...100.",
    "ICMS.Nominal.milhões.de.reais"
    )]
colnames(df) <- c( # Encurtando nomes
    "Exportacoes",
    "Cambio",
    "Importacoes",
    "Industrial",
    "ICMS"
)
df <- xts::as.xts(df)
df %>% head() %>% knitr::kable()
```

# Estimação

## Ordem do modelo

```{r ordem}
vars::VARselect(
    df %>% log() %>%  diff() %>% na.omit(), 
    lag.max = 15, 
    type = 'const'
    )$selection -> ordem
ordem %>% knitr::kable(col.names = "Ordem do modelo VAR")
```


```{r estimacao}
urca::ca.jo(
    df %>% log(), # fix sistema é computacionalmente singular
    type = "trace", 
    ecdet = "const", 
    K = 4, # Following FPE(n) criteria
    season = 12, 
    spec = "transitory"
) -> z
z %>% urca::cajools() -> modelo
    
modelo %>% summary()
```

## Respolta ao Impulso

```{r}
z %>% vars::vec2var() %>% vars::irf(n.ahead = 20, response = "ICMS",
          ortho = FALSE, runs = 500) %>% plot()
```


## FEVD

```{r}
z %>% vars::vec2var() %>% vars::fevd() %>% plot()
```


# Pós-Estimação


## Resíduos

### Correlograma

```{r}
for (serie in colnames(df)) {
    astsa::acf2(
        residuals(modelo)[,paste0(serie,".d")], 
        main = serie
    )
    forecast::checkresiduals(
        residuals(modelo)[,paste0(serie,".d")], 
        main = serie
        )
}
```

### Autocorrelação

```{r Portmanteau}
vars::serial.test(
    z %>% vars::vec2var(),
    lags.pt = 15,
    type = 'PT.asymptotic'
    )
```


```{r LjungBox}
vars::serial.test(
    z %>% vars::vec2var(),
    lags.pt = 15,
    type = 'PT.adjusted'
    )
```

```{r LM}
vars::serial.test(
    z %>% vars::vec2var(),
    lags.pt = 15,
    type = 'BG'
    )
```

### Normalidade


```{r JBMultivariado}
vars::normality.test(
    z %>% vars::vec2var(),
    multivariate.only = FALSE)
```


# Previsão

```{r}
vars::fanchart(predict(
    z %>% vars::vec2var(),
    n.ahead = 15, 
    ci=0.95
    ))
```


```{r}
predict(
    z %>% vars::vec2var(), 
    n.ahead = 15, 
    ci=0.95
    )$fcst$ICMS %>% plot.ts(
        main = "Previsão ICMS", 
        xlab = "",
        ylab = "R$ Milhões"
    )
```


# Comparação

```{r comparacao}
comparacao <- data.frame(
    matrix(ncol = 5, nrow = 4)
)
colnames(comparacao) <- c(
    "Critérios",
    "Portmanteau_pvalue",
    "LjungBox_pvalue",
    "BG_pvalue",
    "JB_pvalue"
)

comparacao$Critérios <- c(
    "AIC(n)",
    "HQ(n)",
    "SC(n)",
    "FPE(n)"
)
ordem <- ordem[ordem >= 2] # K must be at least K=2.
for (i in 1:length(ordem)) {
    print(paste0("Estimando para VECN(K = ", ordem[i]-1, ")"), quote = FALSE)
    urca::ca.jo(
        df %>% log(), # fix sistema é computacionalmente singular
        type = "trace", 
        ecdet = "const", 
        K = ordem[i] %>% as.numeric(),
        season = 12, 
        spec = "transitory"
    ) -> z
    z %>% urca::cajools() -> modelo
    astsa::acf2(
        residuals(modelo)[,"ICMS.d"], 
        main = "ICMS"
    )
    forecast::checkresiduals(
        residuals(modelo)[,"ICMS.d"], 
        main = "ICMS"
        )
    
    vars::serial.test(
    z %>% vars::vec2var(),
    lags.pt = 15,
    type = 'PT.asymptotic'
    ) -> teste
    comparacao$Portmanteau_pvalue[i]  <- teste$serial$p.value  %>% as.numeric()
    
    vars::serial.test(
    z %>% vars::vec2var(),
    lags.pt = 15,
    type = 'PT.adjusted'
    ) -> teste
    comparacao$LjungBox_pvalue[i]  <- teste$serial$p.value  %>% as.numeric()
    
    vars::serial.test(
    z %>% vars::vec2var(),
    lags.pt = 15,
    type = 'BG'
    ) -> teste
    comparacao$BG_pvalue[i]  <- teste$serial$p.value  %>% as.numeric()
    
    vars::normality.test(z %>% vars::vec2var(),)$jb.mul$JB$p.value -> teste
    comparacao$JB_pvalue[i]  <- teste %>% as.numeric()
     
    rownames(comparacao)[i] <- c(paste0("VECM(K = ", ordem[i]-1 %>% as.numeric(), ")" ))
}
comparacao %>% knitr::kable(digits = 3, align = 'c')
```

