#+OPTIONS: num:nil toc:nil
#+TITLE: Equations
#+AUTHOR: Gabriel Petrini

* Descrição

Neste documento vou comparar as novas equações após os pareceres com a versão submetida do artigo.
As demais equações não serão apresentadas.
Vou indicar qual equação foi gerada pelo /sympy/ e qual rearrumei.

* Mudanças comuns (atendem A apenas)

** Equações dos bancos

#+BEGIN_latex
\begin{equation}
L = L_{f} + L_{k} \Rightarrow L = L_{f}
\end{equation}
#+END_latex

** Equações dos capitalistas

#+BEGIN_latex
\begin{equation}
\Delta L_{k} = C_{k} \Rightarrow \Delta L_{k} = 0
\end{equation}
#+END_latex
#+BEGIN_latex
\begin{equation}
D = MO + L_{k} \Rightarrow D = MO
\end{equation}
#+END_latex
#+BEGIN_latex
\begin{equation}
V_{k} = K_{hd} + M - L_{k} - MO \Rightarrow V_{k} = K_{hd} + M - MO
\end{equation}
#+END_latex
#+BEGIN_latex
\begin{equation}
Z = C_{k} + I_{h} \Rightarrow Z = I_{h}
\end{equation}
#+END_latex
#+BEGIN_latex
\begin{equation}
R = \frac{C_{k}}{Z} \Rightarrow R = \nexists
\end{equation}
#+END_latex

** Corrigindo Lucros

#+BEGIN_latex
\begin{equation}
FT = Y - W = FD + FU + r_{l}\cdot L_{f-1}
\end{equation}
#+END_latex
* Alternativa 1: $C_{k} = c_{k}\cdot YD_{k}$

** Equações dos capitalistas

#+BEGIN_latex
\begin{equation}
C_{k} = (1+g_{Ck})\cdot C_{k, t-1} \equiv I_{h}\frac{R}{1-R} \Rightarrow C_{k} = c_{k}\cdot YD_{hk}
\end{equation}
#+END_latex

A renda disponível dos capitalistas pode ser reescrita da seguinte forma:
#+BEGIN_latex
\begin{equation}
YD_{hk} = FD + r_{m}(M_{t-1} - MO_{t-1})
\end{equation}
#+END_latex
Dado que:
#+begin_export latex
$$
M = MO + L \Rightarrow L_{f} = M - MO
$$
#+end_export

Temos:
#+BEGIN_latex
\begin{equation}
YD_{hk} = FD + r_{m}L_{f-1}
\end{equation}
#+END_latex
Substituindo $FD$ pela equação corrigida dos lucros:
#+BEGIN_latex
$$
YD_{hk} = (1-\gamma_{F})\cdot(FT - r_{m}L_{f-1}) + r_{m}\cdot L_{f-1}
$$

$$
YD_{hk} = (1-\gamma_{F})\cdot FT -  (1-\gamma_{F})\cdot (r_{m}\cdot L_{f-1}) + r_{m}\cdot L_{f-1}
$$

$$
YD_{hk} = FT - \gamma_{F}(FT - r_{m}\cdot L_{f-1})
$$

\begin{equation}
YD_{hk} = FT - FU = FD + r_{m}\cdot L_{f-1}
\end{equation}
#+END_latex

** Equilíbrio de curto prazo

*** Nível do produto python

#+BEGIN_latex
\begin{equation}
Y_{t} = \frac{Z_t - \alpha_k \cdot \gamma_{F} \cdot rm \cdot \left(- \operatorname{M_{h}}{\left(-1 + t \right)} + \operatorname{MO}{\left(-1 + t \right)}\right)}{1 - h_t - \alpha \cdot \omega - \alpha_k \cdot \left(-1 + \gamma_{F}\right) \cdot \left(-1 + \omega\right)}
\end{equation}
#+END_latex

*** Nível do produto rearrumado

#+BEGIN_latex
\begin{equation}
Y_{t} = \frac{Z_t + \alpha_k \cdot \gamma_{F} \cdot rm \cdot \left(M_{t-1} - MO_{t-1}\right)}{1 - h_t - \alpha \cdot \omega - \alpha_k \cdot \left(1- \gamma_{F}\right) \cdot \left(1 - \omega\right)} \equiv \frac{Z_t + \alpha_k \cdot \gamma_{F} \cdot rm \cdot \left(L_{f,t-1}\right)}{1 - h_t - \alpha \cdot \omega - \alpha_k \cdot \left(1- \gamma_{F}\right) \cdot \left(1 - \omega\right)}
\end{equation}
#+END_latex
*** Grau de utilização python

#+BEGIN_latex
\begin{equation}
u_{t} = \frac{v \cdot \left(Z_t - \alpha_{k} \cdot \gamma_{F} \cdot rm \cdot \left(- \operatorname{M_{h}}{\left(-1 + t \right)} + \operatorname{MO}{\left(-1 + t \right)}\right)\right)}{K_t \cdot \left(-1 + k_t\right) \cdot \left(-1 + h_t + \alpha \cdot \omega + \alpha_{k} \cdot \left(-1 + \gamma_{F}\right) \cdot \left(-1 + \omega\right)\right)}
\end{equation}
#+END_latex


*** Grau de utilização rearrumado

#+BEGIN_latex
\begin{equation}
u_{t} = \frac{v \cdot \left(Z_t + \alpha_{k} \cdot \gamma_{F} \cdot rm \cdot \left(M_{t-1} - MO_{t-1}\right)\right)}{K_t \cdot \left(1-k_{t}\right) \cdot \left(1 - h_t - \alpha \cdot \omega - \alpha_{k} \cdot \left(1 - \gamma_{F}\right) \cdot \left(1 - \omega\right)\right)} \equiv \frac{Y}{K_{t}}\cdot\frac{v}{(1-k_{t})}
\end{equation}
#+END_latex
como nosso numerador não é apenas $I_{h}$, não podemos usar o artifício do artigo para deixar em termos das diferenças das taxas de crescimento dos gastos autônomos e estoque de capital de um jeito elegante.
Seja $\lambda$ o grau de alavancagem das firmas definido como:
#+BEGIN_latex
\begin{equation}
\lambda = \frac{L_{f}}{K_{f}} = \frac{L_{f}}{(1-k)\cdot K_{t}}
\end{equation}
#+END_latex

Sendo assim, seja $\mu$ o novo multiplicador para facilitar, podemos decompor da seguinte maneira:
#+BEGIN_latex
\begin{equation}
u_{t} = \frac{v}{(1-k_{t})K_{t}}\frac{Y}{\mu} = \frac{v}{(1-k_{t})K_{t}}\frac{I_{h} + c_{k}\gamma_{F}\cdot rm (L_{f})}{\mu}
\end{equation}
#+END_latex
continuando:
#+BEGIN_latex
\begin{equation}
u_{t} = \frac{v}{\mu}\frac{I_{h} + c_{k}\gamma_{F}(L_{f})}{(1-k_{t})K_{t}} = \frac{v}{\mu}\left(\frac{I_{h}}{K_{t}(1-k)} + \frac{c_{k}\gamma_{F}\cdot rm \cdot L_{f}}{K_{t}(1-k)}\right)
\end{equation}
#+END_latex

Se não errei em alguma passagem, temos que o grau de utilização é (usando $g_{I_{h}}$ por questões de espaço apenas):
#+BEGIN_latex
\begin{equation}
u_{t} =  \frac{v}{\mu}\left(\frac{I_{h_{t-1}}}{K_{f_{t-1}}}\frac{(1+g_{I_{h}})}{(1+g_{K_{t-1}})} + c_{k}\gamma_{F}\cdot rm \lambda\right)
\end{equation}
#+END_latex

*** Razão entre estoques de capital (k)

#+BEGIN_latex
\begin{equation}
k = \frac{(1-R)\cdot (1-h_t - \omega)}{h_t + (1-R)\cdot (1-h_t - \omega)} \Rightarrow \frac{(1-h_t - \omega -\alpha_k(1-\gamma_F)(1-\omega))}{h_t + (1-h_t - \omega -\alpha_k(1-\gamma_F)(1-\omega))}
\end{equation}
#+END_latex
logo, o novo $k$ é:

#+BEGIN_latex
\begin{equation}
k = \frac{(1-h_t - \omega -\alpha_k(1-\gamma_F)(1-\omega))}{1 - \omega -\alpha_k(1-\gamma_F)(1-\omega))} = 1 - \frac{h_t}{1 - \omega - \alpha_k(1-\gamma_F)(1- \omega)}
\end{equation}
#+END_latex

** Equilíbrio de longo prazo

*** Taxa de crescimento

Não tenho certeza quanto a essa equação, mas me parece razoavel:

#+BEGIN_latex
\begin{equation}
g_t = g_{Z} + \frac{\Delta h}{1 - \omega - h_{t}} \Rightarrow g_{I_{h}} + \frac{\Delta h}{1 - \omega - h_{t} - c_{k}(1-\gamma_{F})(1-\omega)}

\end{equation}
#+END_latex

*** Nível do produto

#+BEGIN_latex
\begin{equation}
Y^{\star} = \frac{I_h}{\left(1-R\right)\left(1 - \alpha\cdot\omega - g_{I_h}^{\star}\cdot \frac{v}{u^{\star}\right)}} \Rightarrow Y^{\star} = \frac{I_h + c_{k}\cdot\gamma_{F}\cdot rm(M + MO)}{\left(1 - \alpha\cdot\omega - g_{I_h}^{\star}\cdot \frac{v}{u^{\star}} - c_{k}(1-\gamma_{F})(1-\omega)\right)}
\end{equation}
#+END_latex

Para explicitar que o consumo a partir da riqueza não é autônomo, é preciso incluir a norma dívida das firmas-renda ($\ell^{\star}_{Y}$):
#+BEGIN_latex
$$
\ell^{\star} = \frac{L_{f}^{\star}}{K_{f}^{\star}}\frac{K_{f}^{\star}}{K_{f}^{\star}}\frac{Y^{\star}}{Y^{\star}} = \ell^{\star}_{Y}\cdot\frac{Y^{\star}}{K_{f}\star}
$$
#+END_latex
#+BEGIN_latex
\begin{equation}
\ell^{\star} = \ell_{Y}^{\star}\frac{u^{\star}}{v} \Rightarrow \ell^{\star}_{Y} = \ell^{\star}\frac{v}{u^{\star}}
\end{equation}
#+END_latex

Supondo que este norma é calculável e denominando o multiplicador como $\mu$:
#+BEGIN_latex
$$
Y^{\star} = \frac{I_{h}}{\mu} + \frac{c_{k}\gamma_{F}\cdot rm \cdot L_{f}\frac{Y^{\star}}{Y^{\star}}}{\mu}
$$
\begin{equation}
Y^{\star} = \frac{I_{h}}{\mu} + \frac{c_{k}\gamma_{F}\cdot rm \cdot \ell^{\star}_{Y}\cdot Y^{\star}}{\mu}
\end{equation}
#+END_latex

Com isso, é possível prosseguir isolando $Y^{\star}$.
O resultado do *python* é:

#+BEGIN_latex
\begin{equation}
Y^{\star} = \frac{Z_t}{1 - h^\star_t - \alpha \cdot \omega - \alpha_{k} \cdot \left(1 - \omega + \gamma_{F} \cdot \left(-1 + \omega + \ell^\star_Y \cdot rm\right)\right)}
\end{equation}
#+END_latex
rearranjando:
#+BEGIN_latex
\begin{equation}
Y^{\star} = \frac{Z_t}{1 - h^\star_t - \alpha \cdot \omega - \alpha_{k} \cdot \left(1 - \omega - \gamma_{F} \cdot \left(1 - \omega - \ell^\star_Y \cdot rm\right)\right)}
\end{equation}
#+END_latex


** Normas

*** Dívida das firmas-estoque de capital ($\ell^{\star}$)

Como não alteramos nada das firmas, imagino que se mantem igual.
De todo modo, segue como saiu no *python*:

#+BEGIN_latex
\begin{equation}
\ell^{\star}_{f} = \frac{g^\star \cdot v + \gamma_{F} \cdot u_{N} \cdot \left(\omega - 1\right)}{v \cdot \left(g^\star - \gamma_{F} \cdot rm\right)}
\end{equation}
#+END_latex

A partir disso, podemos calcular $\ell^{\star}_{Y}$ e deixar somente o investmento residencial autônomo na equação do nível do produto.
Reescrevendo a equaçoã gerada no /python/:
#+BEGIN_latex
\begin{equation}
\ell^{\star}_{f} = \frac{g^\star \cdot v}{v \cdot \left(g^\star - \gamma_{F} \cdot rm\right)} - \frac{\gamma_{F} \cdot u^{\star} \cdot \left(1- \omega\right)}{v \cdot \left(g^\star - \gamma_{F} \cdot rm\right)}
\end{equation}
#+END_latex
Partindo da equação $\ell^{\star}_{Y}$, e lembrando que multiplicar por $v/u^{\star}$ equivale, no /steady state/ a $h^{\star}/g^{\star}$
#+BEGIN_latex
\begin{equation}
\ell_{Y}\star = \left(\frac{g^{\star}}{g^{\star} - \gamma_{F}\cdot rm} - \frac{\gamma_{F}(1-\omega)}{g^{\star} - \gamma_{F}\cdot rm}\frac{u^{\star}}{v}\right)\cdot\frac{h^{\star}}{g^{\star}}
\end{equation}
#+END_latex
Temos:
#+BEGIN_latex
\begin{equation}
\ell^{\star}_{Y} = \frac{h^{\star} - \gamma_{F}(1-\omega)}{g^{\star} - \gamma_{F}\cdot rm}
\end{equation}
#+END_latex

Substituindo essa equação no nível do produto, temos (*python*):
#+BEGIN_latex
\begin{equation}
Y^{\star} = \frac{Z}{- \alpha \cdot \omega - \alpha_{k} \cdot \left(\gamma_{F} \cdot \left(\omega + \frac{rm \cdot \left(g^\star \cdot v + \gamma_{F} \cdot u^\star \cdot \left(\omega - 1\right)\right)}{u^\star \cdot \left(g^\star - \gamma_{F} \cdot rm\right)} - 1\right) - \omega + 1\right) - h + 1}
\end{equation}
#+END_latex
rearranjando:
#+BEGIN_latex
\begin{equation}
Y^{\star} =
\end{equation}
#+END_latex

*** Dívida de consumo dos capitalistas-estoque de casas

#+BEGIN_latex
\begin{equation}
\ell_{k} = \frac{R}{1 - R} \Rightarrow 0
\end{equation}
#+END_latex

*** Hipotecas-estoque de casas

Não se altera ($mo^{\star} = 1$, como esperado).

*** Depósitos sobre estoque de capital total

$$
\frac{M}{K} = \frac{MO}{K_{HD}}\cdot \frac{K_{HD}}{K} +  \frac{L_k}{K_{HD}}\cdot \frac{K_{HD}}{K} +  \frac{L_f}{K_{f}}\cdot \frac{K_{f}}{K} \Rightarrow
\frac{MO}{K_{HD}}\cdot \frac{K_{HD}}{K} +  \frac{L}{K_{f}}\cdot \frac{K_{f}}{K}
$$

#+BEGIN_latex
\begin{equation}
m^{\star} = mo^{\star}\cdot k^{\star} + \ell^{\star}_{k}\cdot k^{\star} + \ell^{\star}_{f}\cdot (1-k^{\star}) \Rightarrow  mo^{\star}\cdot k^{\star} + \ell^{\star}_{f}\cdot (1-k^{\star})
\end{equation}
#+END_latex

* Alternativa 2: $C_{k} = c_{k}\cdot FD + c_{kw}\cdot NFW_{k}$

Acho que reescrever as equações do artigo submetido não ajudam muito agora.
Se entendi bem, a segunda tentativa parte de uma função de consumo capitalista a partir dos lucros recebidos e da riqueza financeira líquida.

** Equações dos capitalistas

#+BEGIN_latex
\begin{equation}
C_{k} = c_{k} \cdot FD + c_{kw}(M_{t-1} - MO_{t-1})
\end{equation}
#+END_latex
em que (por falta de uma variável melhor), $c_{kw}$ é a propensão marginal a consumir a partir da riqueza financeira líquida.
Sendo assim, se $c_{kw} = 0$ retornamos a alternativa anterior.

** Equilíbrio de curto prazo

*** Nível do produto python


#+BEGIN_latex
\begin{equation}
Y_{t} = \frac{Z_t + \left(\alpha_{kv} + \alpha_{k} \cdot rm \cdot \left(-1 + \gamma_{F}\right)\right) \cdot \operatorname{Lf}{\left(-1 + t \right)}}{1 - h_t - \alpha \cdot \omega - \alpha_{k} \cdot \left(-1 + \gamma_{F}\right) \cdot \left(-1 + \omega\right)}
\end{equation}
#+END_latex

*** Nível do produto rearrumado


#+BEGIN_latex
\begin{equation}
Y_{t} = \frac{Z_t + \left(\alpha_{kv} - \alpha_{k} \cdot rm \cdot \left(1 - \gamma_{F}\right)\right) \cdot L_{f_{t-1}}}{1 - h_t - \alpha \cdot \omega - \alpha_{k} \cdot \left(1 - \gamma_{F}\right) \cdot \left(1 - \omega\right)}
\end{equation}
#+END_latex

*** Grau de utilização python


#+BEGIN_latex
\begin{equation}
u_{t} = \frac{v \cdot \left(Z_t + \left(\alpha_{kv} + \alpha_{k} \cdot rm \cdot \left(-1 + \gamma_{F}\right)\right) \cdot \operatorname{Lf}{\left(-1 + t \right)}\right)}{K_t \cdot \left(-1 + k_t\right) \cdot \left(-1 + h_t + \alpha \cdot \omega + \alpha_{k} \cdot \left(-1 + \gamma_{F}\right) \cdot \left(-1 + \omega\right)\right)}
\end{equation}
#+END_latex

*** Grau de utilização rearrumado


*** Razão entre estoques de capital (k)



** Equilíbrio de longo prazo

*** Taxa de crescimento

*** Nível do produto

** Normas

Neste novo caso, as normas não devem mudar.
A principal diferença é na utilização dessas normas para eliminar os gastos que não são autônomos no numerador do nível de produto no longo prazo.



* Alternativa 3: Ratchet effect

** Equações dos bancos

** Equações dos capitalistas

** Equilíbrio de curto prazo

** Equilíbrio de longo prazo

** Normas
