#+OPTIONS: num:nil toc:nil
#+TITLE: Histórico de versões artigo SFC
#+AUTHOR: Gabriel Petrini
#+DATE: 2020
#+LANG: pt_BR
#+LATEX_HEADER: \addbibresource{../refs.bib}

* Configs                                                          :noexport:

bibliography:../refs.bib

* Versão <2020-10-16 sex>

** Introdução

Não alterei nada do texto que estava na versão anterior. Apenas adicionei dois parágrafos (preliminares) em que tenho fazer uma mini revisão da literatura. Acho que não é muito interessante aumentar mais ainda a introdução. Digo isso porque a maioria dos textos citados na antiga revisão da literatura não eram sobre investimento residencial, mas sim sobre gastos autônomos. A discussão sobre investimento residencial ali era minúscula.

** Seção dos fatos estilizados

Não alterei nada do texto. Apenas substitui o gráfico do preço dos imóveis x endividamento (em número índice) pela curva de concentração. Estou pensando em como deixar esse gráfico mais /printer-friendly/ (talvez deixar os as curvas como linhas cheias e tracejadas).

** Revisão da literatura
   
Não alterei nada dessa seção. Apenas pedi para não compilar (dado que optamos por tirá-la).

** Modelo 

Não houve nenhuma mudança radical. Fiz as correções que sugeriu. Mais no fim dessa seção reorganizei a ordem das equações de um jeito que fizesse mais sentido. Para isso fiz pequenas adaptações no texto. Também removi (comentei) a parte que igualava a oferta à demanda por imóveis. Não parecem ser equações essenciais. Se achar necessário, desfaço isso. De todo modo, achei que estavam jogadas ali. Seria o caso de repensar onde incluí-las.

Dentre as perfumarias (estão nas minhas respostas aos seus comentários), ainda estou pensando em qual letra usar no lugar de taxa de lucro bruta e líquida.

** Solução analítica

Fiz um meio termo entre as suas equações e as minhas anteriores. Em um primeiro momento, priorizei aquelas equações que me enviou no PDF. Apenas rearranjei a posição de algumas variáveis. Se achar melhor, deixo da forma que me enviou. Corrigi e atualizei a equação do $k$. Estava faltando o termo $(1-R)$.

Adicionei a discussão da /traverse/ partindo relação entre $g$ e $g_K$ expressa na sua equação do grau de utilização. Inclui uma nota de rodapé pontuando a diferença entre a traverse e o /medium-run/ do Freitas e Serrano. Poderia dar uma olhada nesta nota de rodapé? não estou contente com o resultado.

Na subseção da /fully-adjusted position/, apenas retirei as equações desnecessárias e adaptei para ficar de uma forma mais elegante que o /output/ do /python/. Deixei registrado as etapas até chegar nos /stock-flow ratio/ porque pensamos em mudar isso para o apêndice. Nesta versão, as variáveis ainda estão normalizadas pelo estoque de capital das firmas ou de casas. Ainda não alterei para a normalização pela renda porque não sei se aquelas notas que te envie estavam certas.

** Simulações

Essa foi a seção que teve mais mudança no texto. Acho que a principal coisa para nos preocuparmos aqui é se faz sentido aquele "novo paradoxo" sumir a partir do valor dos parâmetros. Ainda acho que esse resultado pode ter sumido antes e eu não vi por conta do efeito de escala no gráfico anterior. O mais estranho é que os parâmetros que estão diferentes em relação à dissertação não aparecem nas derivadas parciais do documento que te enviei. Outro possível problema é que esse paradoxo era bem pequeno na dissertação. Ainda assim, acho estranho mudar de direção.

Algumas observações em relação aos gráficos: 
- Na figura 6 (página 19), desconsidere o segundo gráfico da primeira linha e o primeiro da segunda ($u$ e $Z/Y$). Estão com os títulos e a linha tracejada trocados. Consigo arrumar isso rápido, mas quero resolver outras questões antes (essa simulação leva mais tempo para rodar também)
- Pretendo incluir identificadores (A, B, C e D) nos gráficos para mencionar no texto com mais facilidade.
- Dadas as dicas do Rochon, estou pensando em formas de deixar os gráficos mais /printer-friendly/, mas ainda sim legíveis.
  - Na maioria dos gráficos, consigo diferenciar cada linha em termos de estilo do tracejado. No entanto, isso é mais difícil no gráfico de ciclos (primeiro gráfico figura 5).
    - No gráfico com os dados reais, isso já não é um problema já que é uma única série
** Conclusões
Não alterei nada
** Apêndice A

Vi nos seus comentários que a nossa diferença com Freitas e Serrano não é tão importante. Dito isso, optei por comentar toda aquela discussão da estabilidade (é a mesma que a deles com a diferença de que $own < \frac{\phi_0}{\phi_1}$). Comecei esse apêndice a partir do trecho em que você indicou ser outro apêndice. Nesta nova versão, existem várias equações tal como saídas do /python/. Não comecei a melhorá-las porque está em aberto se vamos priorizar a normalização pelo capital ou pela renda. De todo modo, imagino que as derivadas do $k$ não devem mudar muito (já está com o $k$ corrigido). Também achei melhor tirar as derivadas do estoque de moeda (uma vez que é resíduo, não tem muita importância para nós).

** Apêndice B

Talvez essa tabela mude na medida que forem usados outros valores dos parâmetros. Uma vez encerradas as alterações no modelo, rodo o comando para gerar essa tabela. Ainda não descobri como formatar melhor pelo python. Essa é uma das poucas coisas que acho melhor manter o mais próximo do /output/ do computador. Se um parecerista pedir o /script/, ele deve chegar nesse mesmo lugar. Além disso, imagino que esse processo de formatação seja função do journal e não nossa.

** Apêndice C (em construção)

Eu tinha iniciado (faz um tempo) um código para retornar uma tabela de análise de sensibilidade similar à do Fazzari. Esse é um código que leva um certo tempo para rodar porque faço vários /nested for loops/ (a.k.a simulo um porrilhão de cenários rs). No final das contas acabei deixando de lado. Havendo tempo, penso em retornar a isso. Imagino que se desse certo, seria bastante interessante mas também acho que não esta entre as nossas prioridades. Talvez pudesse trabalhar nisso enquanto o artigo estivesse sendo revisado na expectativa de que algum parecerista peça. Por fim, esse apêndice inexistente é um dos motivos de ter tantos /hashs/ ("lixos") no fim do apêndice B.

* Versão <2020-11-03 ter>

** Seção empírica

- Feitas algumas pequenas correções no inglês
- Incluídas discussões empíricas (Green, Leamer e Fiebiger)
  - O mesmo foi feito para artigos econometricos
- Dividida em duas subseções
- Ajustadas proporções e qualidade dos gráficos
- Gráficos foram adaptados para escala de cinza
- Foram incluídas algumas referências empíricas
- Foram deixadas marcas de edição para inclusão posterior da taxa própria (sugestão)
- Incluída explicação da curva de concentração
- Testado gráfico das curvas de concentração em diferentes axis
- Algumas padronizações dos gráficos (tamanho da legenda e dos eixos)


** Modelo

- [ ] Corrigidas referências quebradas (estavam com ??) desta seção

** Analítica

- [ ] Corrigidas referências quebradas (estavam com ??) desta seção

** Simulações

- Gráficos foram adaptados para escala de cinza
- Foram adicionados identificadores aos gráficos (A, B, C e D)
- Correções de legenda nos gráficos
- Gráfico das simulações com dados reais corrigido
- Corrigida exportação para latex no Apêndice B
- Retomado apêndice C
- Corrigidas referências quebradas (estavam com ??) desta seção
- [ ] Reduzido espaçamento entre título e o gráfico
- Valor de $\alpha$ alterado para 1.0 e $\omega = 0.25$ (igual a $\alpha\cdot \omega$ do Fazzari)

* Versão <2020-11-06 sex>

** Introdução

Inalterada em relação à versão anterior

** Seção Empírica

Inalterada em relação à versão anterior

** Modelo

*** Equações gerais

- Feitas as correções sugeridas. Cabe pontuar
  - Sraffian Strands $\Rightarrow$ Sraffian literature
  - /while capitalists earn what they expend/ mantido

*** Firmas
- Feitas as correções sugeridas. Vale pontuar
  - Não foram incluídas as equações da taxa de crescimento do investimento das firmas
    - Conforme discutido via Telegram
  - /To do so/ (p. 9) $\Rightarrow$ /For this mechanism to take place/
*** Bancos
- Feitas as correções sugeridas. Vale pontuar
  - Não foi alterada a letra que representa taxa de juros
    - *Motivo:* Falta de ideias/pragmatismo (rs)
  - Concordo que as duas frases sobre ter taxas de juros específicas estavam contraditórias (p. 10 do pdf comentado). Alterei para

#+BEGIN_QUOTE
For simplicity, we assume null bank spreads ($\sigma_{mo} = \sigma_l = 0$) so interest rate on mortgages ($r_{mo}$) and on loans ($r_{l}$)
are the same as on deposits ($r_{m}$) which is  exogenously determined by banks.
#+END_QUOTE


*** Trabalhadores
- Feitas as correções sugeridas. Nada a comentar
*** Capitalistas
- Feitas as correções sugeridas. Vale pontuar
  - Dívida total dos capitalistas ($D$) definida
  - Funções da taxa própria movidas para a seção empírica. Função da taxa de crescimento to investimento residencial mantida
  - Adicionadas referências sobre tendência do mercado imobiliário e institucionalidade das hipotecas (ao descrever $\phi_0$)
    - Citar orientando do Lavoie? cite:gowans_introducing_2014
      - Discussão sobre determinantes demográficos da taxa de crescimento do investimento residencial. Resumidamente, argumenta por ai do porquê investimento residencial é NCC.
      - [[https://ruor.uottawa.ca/bitstream/10393/32013/1/Gowans_Dylan_2014_researchpaper.pdf][Link]]
  - Trecho sobre $\phi_1$ na equação da taxa de crescimento do investimento residencial alterado para

#+BEGIN_QUOTE
$\phi_1$ captures the demand for housing arising from expectations of capital gains resulting from speculation with flow of new houses. 
#+END_QUOTE

** Solução analítica
*** Short-run

- Feitas correções sugeridas. Vale pontuar
  - Não foi adicionada discussão sobre os efeitos de mudanças na taxa de crescimento do investimento residencial em $k$
    - Anteriormente estava no fim da seção seguinte

*** Analitical Traverse

- Unida com a subseção seguinte e renomeada para /Traverse and long-run Equilibrium/
  - Nota de rodapé pontuando a diferença com textcite:freitas_growth_2015 esta ok?
- Mantidas etapas para obter os /stock ratios/
  - *Motivo:* Caso fossem movidas para um apêndice, faria sentido apresentar as etapas em maiores detalhes. Acho que não temos tanto espaço sobrando assim
- Conforme mencionado, parágrafo final que tratada dos impactos de $g_{I_h}$ em $k$ foi removido
** Simulações
Inalterada em relação à versão anterior
** Conclusão
Inalterada em relação à versão anterior
** Apêndice A

- Resultados do python para $k^\star$ e $\ell_f^\star$ foram rearranjados
  - Mantidas versões antigas para comparação
- Documento Endividamentos.pdf corrigido em <2020-11-04 qua>
  - Já enviado

* Versão <2020-11-11 qua>

** Introdução

Não alterado.

** Fatos estilizados

Não alterado.

** Modelo

Não alterado.

** Solução analítica

- Algumas correções pequenas
  - $l_f^\star \Rightarrow \ell_f^\star$
  - $l^\star \Rightarrow \ell_k^\star$
- Razão $\ell_f^\star$ rearranjada. Passos

#+BEGIN_EXPORT latex
  \begin{equation}
    \tag{Original}
    \ell_f^\star = \frac{g^\star\cdot v - \gamma_F\cdot u^\star (1-\omega)}{v\cdot (g^\star - \gamma_F\cdot r_m)}
  \end{equation}
#+END_EXPORT

Lembrando a definição de taxa de lucro bruta e simplificando por $v$:

#+BEGIN_EXPORT latex
  \begin{equation}
    \ell_f^\star = \frac{g^\star - \gamma_Fr_g^\star}{g^\star - \gamma_F\cdot r_m}
  \end{equation}
#+END_EXPORT


Somando e subtraindo $\gamma_F\cdot r_m$ do numerador e simplificando

#+BEGIN_EXPORT latex
  \begin{equation}
    \ell_f^\star = 1 - \gamma_F\frac{r_g^\star - r_m}{g^\star - \gamma_F\cdot r_m}
  \end{equation}
#+END_EXPORT


Relembrando a equação da taxa de lucro líquida e fazendo $r_l = r_m$,

#+BEGIN_EXPORT latex
  \begin{equation}
    r_n^\star = r_g - r_m\cdot \ell_f^\star
  \end{equation}
#+END_EXPORT


Desse modo, se $\ell_f^\star$ reduz, taxa de lucro bruta e líquida se aproximam.

Deixei a equação original enquanto etapa para chegar nessa nova equação e adicionei uma para a taxa de lucro líquida em função de $\ell_f^\star$ para referenciar nas simulações.

** Simulações

- Para manter consistência entre as equações e simulações, será plotada a razão dívida dos capitalistas/imóveis. O que acha?
- Tabela com resumo dos resultados corrigida
  - $k \Rightarrow K_k$
  - Ajustada equação endividamento



*** Introdução

Feitas as correções sugeridas.

*** Choque na taxa de salários

- Primeira frase alterada para

#+BEGIN_QUOTE
A wage-share decrease has permanent negative impact on output level --- due to changes on the supermultiplier --- and temporary negative effects on degree of capacity utilization (see Figure 5 A).
#+END_QUOTE

- Lower $\Rightarrow$ smaller
- Expenditure -> Expenditures
- This result stem from the $\Rightarrow$ This result is explained by
- Figuras das simulações (e a primeira com dados reais) voltaram a ser coloridas
  - Tanto da seção dos fatos estilizados quanto os demais graficos da simulação com dados reais continuam em escala de cinza
- Conforme falei por menssagem, não temos mais o paradoxo nessa seção. Em função disso, comentei as frases que descrevem esse resultado.
- Corrigi /oan-to-profit ratio/ para /loan-to-capital ratio/
*** Aumento da inflação de imóveis

Feitas as correções sugeridas. Vale destacar que o último parágrafo foi alterado para

#+BEGIN_QUOTE
The most distinct result is real houses share decreases on total capital stock as a result of residential investment growth rate increase.
Although counterintuitive, this result is similar to the conventional paradox of debt.
This is the case since houses are always equivalent to  mortgage debt.
Additionally, this result is in line with SSM literature.
Firms investment follows capital stock adjustment principle, so a higher firms investment growth rate implies that
GDP grows faster than residential investment.
Thus, both residential investment share on GDP and degree of capacity  utilization decrease.
In other words, both autonomous expenditures share on GDP and houses share on real assets (see Equation X)[fn::Não consigo referenciar as equações do paper nesse documento.] decline as a result of the already described non-residential investment positive reaction.
#+END_QUOTE


A seguinte frase foi removida: Besides the usual SSM results, we report some particularities regarding real assets composition.

- Pareceu muito genérica e pouco descritiva.

  
*** Aumento da taxa de juros
- This result stem from the $\Rightarrow$ This effect is a result of the

*** Dados reais

- Mencionei a seção dos fatos estilizados
- Deixei explícito que a taxa de crescimento do consumo dos capitalistas passou a ser

#+BEGIN_EXPORT latex
  \begin{equation}
    \label{gck_real}
    g_{C_k} = \frac{1}{N} \sum_{t=1992}^{2019} g_{I_{h_{t}}}
  \end{equation}
#+END_EXPORT

- Não alterei os fatos estilizados itemizados porque a seção de motivação empírica ainda está em aberto
- Deixei a marca de edição que não replicamos a maior volatilidade do investimento residencial
- Primeiro gráfico desta simulação passou a ser colorido
  - Note que o investimento das firmas é o mais volátil
- Removi a seguinte frase: /Since the analyzed period does not correspond to the fully-adjusted position, discrepancies between actual and normal capacity utilization rate are adjusted through changes in marginal propensity to invest/
  - Além de estar confusa (como apontado), o texto pareceu mais fluido depois que tirei.

* Versão <2020-11-18 qua>

** Introdução

- /try/ removido
- demand-led agenda $\Rightarrow$ demand-led growth theory research agenda
- Trecho sobre taxa própria alterado para

#+BEGIN_QUOTE
One way to do this is through houses' own rate of interest.
Originally introduced by textcite:Sraffa_Own_1932 and applied to the US case by textcite:teixeira_crescimento_2015, this concept allows to connect asset bubble with residential investment.
#+END_QUOTE

- Ainda não entendi o porquê do trecho estar sublinhado. Imagino que possa parecer jogado. Deixei inalterado porque não consegui pensar uma forma de reescrever sem deixar de citar o Serrano e o Freitas
  - A princípio pensei em apagar, mas aí sairia essas citações.

** Seção empírica

- Corrigido problema com as aspas
- Trecho mencionando paper econométrico que testa o cite:leamer_housing_2007 logo após cite:fiebiger_semi-autonomous_2018 e cite:fiebiger_trend_2017

#+BEGIN_QUOTE
Alternatively, textcite:huang_is_2020 estimate a Structural Vector Autoregressive (SVEC) model in a time-scale framework for the OECD countries to assess both prediction and causality relations stated by textcite:leamer_housing_2007.
They report that residential investment predicts the US  macroeconomic fluctuation and housing related variables (house prices, real mortgage rate --- deflated by a general price index --- and bank spread) lead the business cycle in all G7 countries.
#+END_QUOTE

- /In this paper, we argue that besides this growing body of literature that recognizes the macroeconomic importance of residential investment, little progress has been made in understanding its theoretical determinants./ $\Rightarrow$ /In this paper, we argue that besides this growing body of literature that recognizes the macroeconomic importance of residential investment, little progress has been made in connecting asset bubbles with its macroeconomics consequences./
- Na página 4, alterei: /higher growth rate/ $\Rightarrow$ /higher residential investment growth rate/
- Alterei a frase seguinte de /Following the Sraffian supermultiplier growth model, we conclude that increase of non-residential investment is the result of capital stock adjustment principle/ $\Rightarrow$ /Accordingly to the Sraffian Supermultiplier model, we can interpret subsequent non-residential investment increase as a result of capital stock adjustment principle/
  - Não entendi muito bem a sua sugestão. Fiquei em dúvida se era para alterar apenas a frase em amarelo ou juntar com a seguinte
- Supondo que o seguinte trecho sublinhado estava jogdo (p.4): /Additionally, some key aspects of recent housing developments have not been dealt with in depth. More specifically, there has been little discussion on popularization of primary houses and concentration of secondary ones/, alterei para /Turning now to some key aspects of housing distribution, we point out that  there has been little discussion on popularization of primary houses and concentration of secondary ones/
- Após as curvas de concentração: /suggests an increase in the demand for properties in the expectation of capital gains/ $\Rightarrow$ /suggests other purposes, such as rental income, speculation, etc/
  - O que achou da explicação das curvas de concentração? sugestões?
- Iniciei subseção da taxa própria da seguinte forma:

#+BEGIN_QUOTE
Housing macroeconometric literature usually defines real mortgage interest rate as the nominal one deflated by a general prince index.
For example, this is the case for textcites:goodhart_house_2008,arestis_economic_2019,huang_is_2020.
In a prominent econometric model for the US economy, textcite:fair_macroeconometric_2013 reports that conventional real mortgage interest rate is statistically insignificant to describe residential investment and starts using mortgage rate in nominal terms.

[Achei melhor parar o parágrafo anterior ai e iniciar a discussão da taxa própria no próximo]

Alternatively, textcite:teixeira_crescimento_2015 proposes the so-called houses own rate of interest ($own$) in order to analyze the relation between residential investment, real estate inflation and interest rates during the U.S. housing bubble episode.
#+END_QUOTE


Segui sua sugestão e achei que essa forma de organizar o argumento ficou melhor e menos repetitiva. Porém, acho que falta explicar melhor o porquê usar uma taxa de juros real das hipotecas diferente. Digo isso porque o parecerista pode achar estranho irmos nessa direção sendo que a literatura empírica aponta o oposto. Resumindo, acho que precisamos conectar melhor a discussão do Fair com a da sua tese. Sugestões?



** Modelo

Nenhuma alteração

** Solução analítica

Nenhuma alteração
** Simulações

Nenhuma alteração

** Conclusão

Nenhuma alteração

** Apêndices

Nenhuma alteração

* Versão <2020-12-11 sex>


- [X] Média geométrica nas simulações reais
- [X] Atualizar bibliografias
  + cite:girardi_autonomous_2015
  + cite:haluska_growth_2019
- [X] Gráfico da taxa própria com tracejados
- [X] Checar subescritos
- [X] Remover apêndice A e referências
- [ ] Atualizar agradecimentos
- [ ] Pente fino inglês

* Referências
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+LaTeX: \printbibliography[heading=none]


