#+TITLE: Referee Report
#+OPTIONS: toc:nil
#+AUTHOR:
#+LATEX_HEADER: \renewcommand{\abstractname}{Overview and Recommendation}


\noindent *Manuscript:* Residential Investment as a Luxemburg-Kalecki External Market in the United States: An Empirical Investigation

#+BEGIN_abstract
The manuscript aims to contribute to the empirical literature on Non-Capacity Creating Autonomous Expenditure (NCCAE, now on). SUMMARY. This topic is relevant and the proposed methodology is NEW. However, there are a few drawbacks in the paper so my recommendation is for *acceptance* of the manuscript *upon revision*.

The paper has four main sections. Section 2 is a review of the empirical literature and points out the macroeconomic relevance of residential investment (RES, now on); section 3 complements the previous one and reviews the theoretical demand-led growth literature and emphasizes the compability of RES with the Sraffian Supermultiplier Model (SSM); section 4 presents the data, methodology and empirical strategy in which PROPOSTA DO ARTIGO and is followed by the results (section 5). Since the empirical strategy is well DOCUMENTADA, I will focus on the links between the empirical sections (4 and 5) whith the theoretical ones (2 and 3).
#+END_abstract


1. Section 2 reviews the empirical literature (both orthodox and heterodox estimations) in which emphasizes the macroeconomic relevance of residential investment. However, in this same section different residential investment-related topics are discussed without futher mediation. For instance, volume (level), price and growth implications of RES are discussed while the paper aims to evaluate the relationship between RES and GDP *growth*.

2. In this same section, there are some incompabilities between empirical evidence discussed and the adopted hypothesis. For example, the author(s) mention ARESTIS result in which RES (level) depends on real disposable income. However, on the following paragraph, the author(s) state(s) that RES may be considered as a NCCAE.

   - To be fair, there are few works that discuss if RES in particular could be considered as an autonomous expenditure. That been said, it would be interesting to argue a little more about this topic.

3. Although the data and empiricial strategy are discussed in section 4, there is no mention of why the US was chosen as a case study nor the time range adopted (1960-2019:2). The author(s) could elaborate more on this since the empirical review shows that the relevance of the RES is not restricted to the US.

4. Section 3 discuss the theoretical demand-led growth literature and emphasizes models that explicitly includes NCCAE such as the SSM model. In this section, the author(s) argues that RES can be treated as NCCAE, but there is little theoretical discussion about this.

5. In respect to the links between theoretical and empirical sections, there is no mention in section 3 about why RES and GDP growth should have a nonlinear structure (which is relevant assumption for methodology employed). However, the results presented in section 5 supports this nonlinear specification, so this is not a problematic issue.

   - DUESENBERRY, for instance, concludes that RES should evolve independently from output (/i.e./ is a NCCAE) when investors speculates with real estate. So, there is theoretical foundations for both autonomous and nonlinear relation between RES and GDP. That been said, I recommend a brief discussion on this in section 3.

6. Accodoring to the same quote  of SERRANO, the following expenditures are supposed to be considered as autonomous: ``the consumption of capitalists; the discretionary consumption of richer workers that have some accumulated wealth and access to credit; [...]''. Besides controling for some  NCCAE on the econometric model (section 5), there is no mention of the absence of autonomous consumption.

   - Other scholars, for instance, REMOVED this same expenditure in order to improve the estimation as GIRARDI AND PARIBONI does (mentioned in section 2).

7. Section 4 presents the empirical strategy adopted and discuss the chosen procedures formal and rigorously.  However, there is no mention of the (theoretical) expected parameter values (page 18). Moreover, parameter $\pi$ had not been defined along the manuscript. 

8. Além disso, nessa mesma seção poderia ser mais claro que as variáveis em questão estão em taxa de crescimento

9. Na seção seguinte, os resultados obtidos não são comparados com os da literature. Isso seria interessante uma vez que HUANG usa uma metodologia comparável

10. Finally, a friendly suggestion. In order to emphasize the econometric results and to follow the ``housing tradition'', the manuscript title could be: ``Housing is NOT ONLY the business cycle: a Luxemburg-Kalecki External Market empirical investigation for the United States (1960-2019)''




Considering the items discussed above, I recommend *acceptance* of the manuscript *after review*.
