#+AUTHOR: Gabriel Petrini
#+LANG: en
#+EXCLUDE_TAGS: noexport

* Technical setup :noexport:

* Dúvidas :noexport:
** TODO Qual a necessidade de um mark-up variável?
** TODO Se o markup variar, é preciso deflacionar o consumo?
** TODO Dadas as hipóteses até então, qual é o determinante do market-share efetivo?
*** TODO Concessão de crédito pelos bancos?
** TODO Incluir investimento de reposição?
** TODO É preciso discutir fragilidade financeira das firmas?
** TODO É necessário supor heterogeinidade de vida útil do capital?
* Ideias :noexport:


* Main text :ignore:


** Review of theoretical literature :ignore:

In this section, we present the conceptual model that will be simulated later in section SEÇÃO.
This model represent an economy as simple as possible with heterogeneous firms while all the other institutional sectors are aggregated.
At odds with conventional AB literature, we assume no thecnological progress to keep it simple[fn::For an detailed description of innovations and thecnological change in AB models, see DOSI whom we refer to as a benchmark model.].
All other auxiliary assumption will follow AB literature as long as does not generate incompatibility with SSM closure.

Before moving further to the description of every institutional sectors, we will present the hypothesis of this simplified economy.
For simplicity, there is only one productive sector, no labor supply restriction, government nor external sector.
As a consequence of the previous assumptions, the economy is composed by $N$ homogeneous households and $F$ heterogeneous firms[fn::Aggregates variables will be represented by subscript $N$ for households and $F$ for firms.].



#+LATEX: \begin{table*}\centering
#+LATEX: \caption{Expected results accordingly to Standard Sraffian supermultiplier model: transience compared to baseline}
#+LATEX: \label{Tab_exp_resul_trans:ch_super}
#+latex: \resizebox{\textwidth}{!}{%
|----------------------------------------+-----------------+----------------------+------------------+--------------------+----------------------+--------------|
| *Shock*                                  | *Economic growth* | *Capacity utilization* | *Investment share* | *Firms indebtedness* | *Firms entry and exit* | *Market share* |
| <l>                                    |       <c>       |        <c10>         |      <c10>       |        <c>         |         <c5>         |     <c5>     |
|----------------------------------------+-----------------+----------------------+------------------+--------------------+----------------------+--------------|
| Autonomous growth rate increase        |       $+$       |         $+$          |       $+$        |        $-$         |          ?           |      ?       |
| Wage share increase                    |       $+$       |         $+$          |       $+$        |                    |          ?           |      ?       |
| Higher profit distribution rate        |                 |                      |                  |        $+$         |          ?           |      ?       |
| Higher policy rate                     |       $-$       |         $-$          |       $-$        |        $+$         |          ?           |              |
| Market price increase                  |                 |                      |                  |                    |          ?           |      ?       |
| Higher expectational persistence ($\delta$) |        ?        |          ?           |        ?         |         ?          |          ?           |      ?       |
|----------------------------------------+-----------------+----------------------+------------------+--------------------+----------------------+--------------|
#+latex: %
#+latex: }
#+LATEX: \caption*{\textbf{Source:} Authors' elaboration}
#+LATEX: \end{table*}



#+LATEX: \begin{table*}\centering
#+LATEX: \caption{Expected results accordingly to Standard Sraffian supermultiplier model: fulled adjusted compared to baseline}
#+LATEX: \label{Tab_exp_resul_long:ch_super}
#+latex: \resizebox{\textwidth}{!}{%
|----------------------------------------+-----------------+----------------------+------------------+--------------------+----------------------+--------------|
| *Shock*                                  | *Economic growth* | *Capacity utilization* | *Investment share* | *Firms indebtedness* | *Firms entry and exit* | *Market share* |
| <l>                                    |       <c>       |        <c10>         |      <c10>       |        <c>         |         <c5>         |     <c5>     |
|----------------------------------------+-----------------+----------------------+------------------+--------------------+----------------------+--------------|
| Autonomous growth rate increase        |       $+$       |         $0$          |       $+$        |        $-$         |          ?           |      ?       |
| Wage share increase                    |       $0$       |         $0$          |       $0$        |                    |          ?           |      ?       |
| Higher profit distribution rate        |       $0$       |         $0$          |       $0$        |        $+$         |          ?           |      ?       |
| Higher policy rate                     |       $0$       |         $0$          |       $0$        |        $+$         |          ?           |              |
| Market price increase                  |                 |                      |                  |                    |          ?           |      ?       |
| Higher expectational persistence ($\delta$) |        ?        |          ?           |        ?         |         ?          |          ?           |      ?       |
|----------------------------------------+-----------------+----------------------+------------------+--------------------+----------------------+--------------|
#+latex: %
#+latex: }
#+LATEX: \caption*{\textbf{Source:} Authors' elaboration}
#+LATEX: \end{table*}

** Sequence of events



** Production and distribution


*** Firms production plans

Each firm ($f$) investment plan ($Y_{f,t}$, Equation ref:EQ_Yf) is defined accordingly to its expected real sales level ($S^{e}_{f,t}$) and a desired inventories to sales ratio $(\iota^{T} \in [0,1])$ -- exogenous defined and equal across firms -- to attend unexpected demand boosts as usual in $K+S$ models.

#+BEGIN_latex
\begin{equation}
\label{Ch_super_EQ_Yf}
Y_{f,t} = (1+\iota^{T})\cdot S^{e}_{f,t} - INV_{f,t-1}
\end{equation}
#+END_latex
in which $INV_{f,t-1}$ is the firm's inventories.
In baseline scenario, we assume naïve expectational procedure in which expected sales level is equal to its lagged value.
Alternatives expectational procedures will be discussed in section ref:sec:switching.
After defining an production plan, firms calculates its desired capacitiy utilization rate ($u^{d}_{f}$, Equation) as follows:

#+BEGIN_latex
\begin{equation}
u^{d}_{f} = \max\left[ 0, \min\left[ \frac{Y_{f,t}}{Y_{f,t}^{FC}}, 1 \right] \right]
\end{equation}
#+END_latex
in which $Y_{f,t}^{FC}$ is the firm's current output at the full capacity.
Since we assume no labor restriction, full capacity output is define by its existing capital stock ($K_{f,t-1}$) given a maximum capital to output ratio ($\nu$) constant, exogenous and equal across firms:

#+BEGIN_latex
\begin{equation}
Y_{f,t}^{FC} = \frac{K_{f,t-1}}{\nu}
\end{equation}
#+END_latex
Consequently, current firm's capacity utilization ratio is constrained do be equal or less than one since production is limited by physical capital.



*** Capital stock


Since there is no thecnological progress nor innovation in the current version of this model, firms' capital stock only differs according to it lifetime ($\kappa$).
Consequently, total capital stock is defined as the sum of different capital good vintage ($k_{f}$) as follows:

#+BEGIN_latex
\begin{equation}
K_{f} = \sum_{j=1}^{\kappa < \infty} k_{f,t-j}
\end{equation}
#+END_latex
For simplicity, we assume no use depreciation, so each capital good will be replaced only if achieve its maximum lifetime.

*** Labor demand and wage bill

In order to produce, firms use a Leontieff-type technology with a fixed combination between labor and physical capital.
Given no a fixed labor productivity equally defined across workers, labor demand is a function ($N^{d}_{f,t}$) of each firm production plan at current capacity utilization level:

#+BEGIN_latex
\begin{equation}
N^{d}_{f,t} = u_{f,t}\cdot Y^{FC}_{f,t}
\end{equation}
#+END_latex

Since our main purpose with this model is to evaluate emergence of firm's behavior, we assume single nominal wage for all workers ($w_{t}$) exogenously defined.
Thus, each firm wage bill ($W_{f}$) is:
#+BEGIN_latex
\begin{equation}
W_{f,t} = N^{d}\cdot w_{f,t}
\end{equation}
#+END_latex
In order to prevent asymptotic null induced consumption levels, we assume that at each time nominal wage is updated accordingly to previous inflation rate ($\pi_{t-t}$) which is the market-share weighted market price mean (Equation ref:EQ_Infla)

#+BEGIN_latex
\begin{equation}
w_{t} = w_{t-1}\cdot(1+\pi_{t-1})
\end{equation}
#+END_latex
#+BEGIN_latex
\begin{equation}
\label{Ch_super_EQ_Infla}
\pi_{t} = \sum_{f=1}^{F} ms_{f,t}\cdot p_{f,t}
\end{equation}
#+END_latex
in which $ms_{f}$ and $p_{f,t}$ stands for firm's $f$ market share and price respectively.



*** Pricing

We assume a simple pricing mechanism as possible which is defined as a mark-up ($\theta_{f}$) over direct unit labor costs (in this case, $w_{t}$):
#+BEGIN_latex
\begin{equation}
p_{f,t} = (1+\theta_{f})\cdot w_{t}
\end{equation}
#+END_latex
At odds with $K+S$ model, and a a result of our simplifying assumptions, there is no need to specify a mark-up law of motion equation[fn::This is the case for $K+S$ models because unit labor costs are not under firms strict control. Once we assume no technological progress nor innovation, uncertainty regarding labor productivity level is vanished.].
As we will further explore in section ref:sec:switching, expected market-share levels play a prominent role in investment decision and not in pricing as usual.



*** Household demand


In order to investigate the consequences of heterogeneous investment decisions in a Sraffian supermultiplier friendly framework, we a assume that household's consumption ($C_{N}$) is composed both by an induced ($W_{N,t}$) and by an autonomous component ($Z_{t}$)[fn::As discussed before, there is a multitude of non-capacitiy creating autonomous expenditures. Autonomous households consumption component was selected only to reduce the complexity of this model.][fn::Following textcite:serrano_1995_Long, we consider $Z_{t}$ as an non-capacitiy creating autonomous expenditure because it does not depends on firms' production decisions. Additionally, since banking credit is endogenous, consumption loans does not affect credit availability for other sectors.]:

#+BEGIN_latex
\begin{equation}
C_{N} = c_{w}\cdot W_{N,t} + c_{p}\cdot FD_{t} + Z_{t}
\end{equation}
#+END_latex
in which $1 \geq c_{w} > c_{p} > 0$ are households marginal propensity to consume out of wages and out of distributed profits ($FD$, discussed in Section ref:sec:banking) respectively while autonomous expenditure is given by its exogenously defined growth rate ($g_{Z}$):
#+BEGIN_latex
\begin{equation}
Z_{t} = (1+g_{Z})\cdot Z_{t-1}
\end{equation}
#+END_latex
in which is financed either by financial wealth and by banking credit.

Since we assume no households heterogeinity, consumption loans restriction has no economic meaning at the aggregate level.
Differently from firms, we impose that households are not credit constrained[fn::We are aware of the simplifications of these assumption, but our main propose here is to elaborate a simple model to discuss heterogeneity in the Sraffian Supermultiplier macroeconomic model.].
Implicitly, we assume that banking evaluation of households default probability ($pr^{D}_{N,t}$) is null.

*** Distribution of demand


Considering previous assumptions, total demand of this economy ($Y$) is the sum of aggregate household consumption ($C_{N}$) and total firms' investment ($I_{F}$) which is the sum of individual firms investment decisions ($I_{f}$).
#+BEGIN_latex
\begin{equation}
\label{Ch_super_EQ_GDP_D}
Y = C_{N} + \sum_{f}^{F} I_{f}
\end{equation}
#+END_latex
As usual in AB models, distribution of total demand depends on relative competitiveness.
Since there is no price diversity, we assume that firms relative competitiveness depends only on the level of unfilled demand ($l_{f,t}$), normalised to the whole sector’s weighted averages ($\overline{l}_{f,t-1}$):

#+BEGIN_latex
\begin{equation}
E_{f,t} = -\beta \frac{l_{f}}{\overline{l}_{f,t-1}}
\end{equation}
#+END_latex
Following SILVERBERG E DOSI, effective market-share is defined accordingly to a quasi-replicator mechanism (Equation ) in which firms that were not able to fulfill its demand level will have a lower market-share:
#+BEGIN_latex
\begin{equation}
\label{Ch_super_EQ_Replicator}
ms_{f,t} = ms_{f,t-1}\cdot \left(1+\chi \frac{E_{f,t} - \overline{E}_{t}}{\overline{E}_{t}}\right)
\end{equation}
#+END_latex
in which $\chi$ is a positive exogenous parameter and $\overline{E}_{t}$ is the average competitiveness of the whole sector:
#+BEGIN_latex
\begin{equation}
\overline{E}_{t} = \sum_{f=1}^{F}E_{f,t}\cdot ms_{f,t-1}
\end{equation}
#+END_latex

As will be discussed in section ref:sec:switching, effective market-share depends both on expected mark-share and effective investment decision, each one explained separately.
Thus, investment emergence patterns depends on how firms adapts its expectations and changes (or not) its investment functions.

** Banking sector, credit and financial implications
:PROPERTIES:
     :CUSTOM_ID: sec:banking
     :END:

*** Firms' credit

*** Household credit

*** Profits and dividends

*** Interest rate and profit

** Switching mechanism
:PROPERTIES:
     :CUSTOM_ID: sec:switching
     :END:

This section provides the description for both expectational and investment decisions switching mechanism.
In order to do so, we implement the same algorithm as textcite:dosi_2020_RATIONAL,reissl_2021_Heterogeneousa which is inspired in AUTORES empirical work.
The idea of this mechanism is to evaluate if a expectational rule or an investment function dominates the others and which pattern emerges at the macroeconomic level.
Thus, Section ref:sec:switching_invest describe the expectational mechanism while Section ref:sec:switching_invest applies this same principle to investment decisions.

*** Expectations
:PROPERTIES:
     :CUSTOM_ID: sec:switching_expec
     :END:

The expectational switching mechanism employed in this model is the same as textcite:dosi_2020_RATIONAL,reissl_2021_Heterogeneousa.
Basically, firms alternates between expectational rules based on mean squared forecast errors ($MSFE$) values.
Thus, this "Ecological Heuristics Expectational Rule" (EHER) allows us to evaluate how chances at the firm level have macroeconomic consequences in terms of economic stability, long-term growth and survival conditions for each firm.
Considering the expectation of variable $X$ ($X^{e}$), firms choose among the following alternatives rules:

 - Naïve (/naïve/) :: $X^{e}_{na\text{\"{i}}ve,t} = X_{t-1}$
 - Adaptative (/ada/) :: $X^{e}_{ada,t} = X^{e}_{t-1} + \phi_{ada}\cdot (X_{t-1} - X^{e}_{t-1})$
 - Weak trend expectation (/wtr/) :: $X^{e}_{wtr,t} = X_{t-1} + \phi_{wtr}\cdot (X_{t-1} - X_{t-2})$
 - Strong trend expectation (/str/) :: $X^{e}_{str,t} = X_{t-1} + \phi_{str}\cdot (X_{t-1} - X_{t-2})$
 - Anchor and Adjustment (/aa/) :: $X^{e}_{aa,t} = \phi_{aa}\cdot Anch + (1-\phi_{aa})\cdot X_{t-1} + (X_{t-1} - X_{t-2})$

in which $0 < \phi_{ada} < 1$, $0 < \phi_{wtr} < \phi_{str}$ adjustment are parameters exgonously defined while $Anch$ is expectational anchor which is the moving average of $X$ as in textcite:reissl_2021_Heterogeneousa.

At each period, firms compute it expectational variables and evaluate whether or not to change it accordingly to the last forecast error of $X$ ($U_{rule,t}, rule \in {na\text{\"i}ve}, ada, wtr, str, aa$):
#+BEGIN_latex
\begin{equation}
\label{Ch_super_EQ_LFE}
U_{rule,t} = - \left(\frac{X_{t-1} - X^{e}_{rule,t-1}}{X^{e}_{rule,t-1}}\right)^{2} + \eta\cdot U_{rule,t-1}
\end{equation}
#+END_latex
where $0 \leq \eta \leq 1$ is a memory parameter which measures weight of past errors.
As in textcite:dosi_2020_RATIONAL, firms update the expectation rule with the probability $n_{rule,t}$ in each period as follows:
#+BEGIN_latex
\begin{equation}
\label{Ch_super_EQ_rule_prob}
n_{rule,t} = \delta\cdot n_{rule,t-1} + (1-\delta)\cdot \frac{\exp{\gamma\cdot U_{rule,t}}}{\sum_{rule}^{RULE}\exp{\gamma\cdot U_{rule,t}}}
\end{equation}
#+END_latex
with $\gamma \geq 0, \delta \leq 1$.
The rationale behind Equation ref:EQ_rule_prob is that the probability to change the expecational rule depends on the persistence of the currently employed rule ($\delta$) and on the impact of the past performance ($\gamma$).

Thus, as discussed before, this expecational switching mechanism allows us to explore the consequences of heterogenoeus firms computing different market-share expectations.
In terms of the implementation of a microfounded Sraffian supermultiplier model, this rather simple procedure triggers different investment expenditures even though firms decide to invest using the same functional specification.
Formally,


#+BEGIN_latex
\begin{equation}
I_{f,t} = h_{f,t} \cdot \left(ms^{e}_{rule,f,t} \sum_{f=1}^{F}Y_{f,t}\right)
\end{equation}
#+END_latex
which is firm-level equivalent to the standard Sraffian supermultiplier model with only one firm ($ms^{e}_{F} = ms_{F} = 1$).
Next, on Section REF, this microeconomic specification will compared with the only-one-firm (oof) contrafactual.
Before moving to the model's validation, the next subsection will present the switching mechanism regarding investment decions.

*** Investment decisions
:PROPERTIES:
     :CUSTOM_ID: sec:switching_invest
     :END:

Similarly to the previous subsection, firms follow some heuristic rules in order to choose the specification of the investment function.
The main divergence is that instead of computing the mean squared expectational forecast errors, firms evaluate its decision regarding unfilled demand.
The rationale behind this rule is that firms investment decision depends on the divergences between effective and normal capacity utilization rate in order to attend unexpected demand STEINDL.
Additionally, firms intend to achieve normal capacity utilization rate to reduce unnecessary costs as described by CICCONE.
Before moving further, it is important to note that there is no consensus in the demand-led macroeconomic growth literature if normal capacity utilization is achieved[fn::For a discussion about this, see REF].
However, it is unclear what is the macroeconomic emergence of different firm-level strategies regarding to reduce the discrepancies between effective and normal capacity utilization rate.

The switching mechanism present in this subsection is relevant because it allows us to explore some opened questions:
    (i) the aggregate investment function is a mirror of firm-level behavior or there are any properties that emerges?
    (ii) is there a dominant investment decision strategy?
    (iii) what are the consequences regarding desired capacity utilization rate in the presence of heterogeneous firms?
In order to answer them, we implement the following investment decisions functions inspired by the current demand-led macroeconomic growth literature:

- Standard neo-Kaleckian  (/NK/) :: $I_{NK,t} = \left(\overline{\beta}_{0} + \beta_{1}(u - u_{N})\right)\cdot K_{f,t-1}$
- neo-Kaleckian supermultiplier (/KSM/) :: $I_{KSM,t} = \left(\beta'_{0,t} + \beta_{1}(u - u_{N})\right)\cdot K_{f,t-1}$
- Sraffian supermultiplier (/SSM/) :: $I_{SSM,t} = h_{f,t}\cdot \left(ms^{e}_{t}\cdot \sum_{f=1}^{F}Y_{f}\right)$
where $\overline{\beta}_{0}$ is investment autonomous component which represents animals spirits, $\beta_{1}$ is investment induced component, $h_{f,t}$ is the marginal propensity to invest which evolves accordingly to discrepancies between effective and normal capacity utilization rate cite:serrano_1995_Long,serrano_2017_Sraffianc:
#+BEGIN_latex
\begin{equation}
\Delta h_{f,t} = \beta_{u}(u_{t} - u_{N})\cdot h_{f,t-1}
\end{equation}
#+END_latex
in which $\beta_{u}$ is an adjustment parameter while $\beta'_{0}$ is flexible autonomous component proposed by textcite:allain_2015_Tacklinga.
Adapting it in order do express commom elements across alternatives:
#+BEGIN_latex
\begin{equation}
\Delta \beta'_{0,t} = \beta_{u}\cdot\beta_{1}(u - u_{N})\cdot \beta'_{0,t-1}
\end{equation}
#+END_latex


At each period, firms revise whether or not to change the current investment function.
This procedure is based on the level of unfilled demand which is updated similarly to expectational performance ($U^{D}_{inv,t}, inv \in [NK, KSM, SSM]$):
#+BEGIN_latex
\begin{equation}
U^{D}_{inv,t} = - (l_{f,t-1})^{2} + \eta_{I}\cdot U^{D}_{inv,t-1}
\end{equation}
#+END_latex
where $\eta_{I}$ is a memory parameter as in Equation ref:EQ_LFE.
Additionally, an alternative investment function is choosen with the probability $n_{inv,t}$:


#+BEGIN_latex
\begin{equation}
\label{Ch_super_EQ_inv_prob}
n_{inv,t} = \delta_{I}\cdot n_{inv,t-1} + (1-\delta_{I})\cdot \frac{\exp{\gamma_{I}\cdot U_{inv,t}}}{\sum_{inv}^{INV}\exp{\gamma_{I}\cdot U_{inv,t}}}
\end{equation}
#+END_latex
in which parameters $\delta_{I}, \gamma_{I}$ have the same meaning as in Equation ref:EQ_rule_prob.

** Aggregating and closing the model

*** Entry and exit of firms
*** Closing the accounting
