#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 158425 - Tales Alonso
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 158425
#+PROPERTY: NOME "Tales Alonso"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END
  
* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido totalmente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido totalmente
  :DESENVOLVIMENTO: Atingindo minimamente
  :CONCLUSAO: Atingindo minimamente
  :CLAREZA:  Atingido satisfatoriamente
  :NOTA:     Atingido parcialmente
  :END:

** Comentários individuais 

Você corretamente posiciona o monetarismo enquanto contraponto ao paradigma precedente assim como destaca a importância da retomada da TQM. Na descrição da TQM, não foi mencionada a hipótese de estabilidade da velocidade de circulação de moeda, hipótese essa importante para explicar a instabilidade macroeconômica. Adiante, corretamente pontua que a moeda é tratada como um ativo como qualquer outro, mas poderia ter relacionado melhor as ideias. Meu ponto é: o resgate da TQM é feito por meio de seu tratamento enquanto uma função de demanda por moeda. Sendo a moeda um ativo como outro qualquer e a velocidade de circulação constante, aí sim é possível associar a expansão monetária ao nível de preços. Em resumo, o que você escreveu esta correto, mas poderia melhor no encadeamento do raciocínio.

Em seguida, é apresentada a curva de Phillips e sua versão aceleracionista. No entanto, esta discussão é feita sem uma mediação com a anterior. Você corretamente pontua a relação entre estabilidade de preços e de nível de emprego (compatível com o desemprego natural). Apesar disso, o conceito de curva de Phillips vertical esta desconectada com o resto do parágrafo. Adiante, corretamente relacionada ilusão monetária com curva de Phillips aceleracionista. Mais adiante, são colocadas as recomendações de política econômica que vão além da simples regra de expansão monetária. O mesmo vale para a discussão das defasagens temporais. Ao discutir as regras monetárias, é dada muita ênfase aos elementos expectacionais da teoria. No entanto, como você mesmo coloca ao discutir a TQM, a estabilidade de preços só seria possível se os agregados monetários crescerem à uma mesma taxa que o nível de produto. Portanto, o argumento vai além de facilitar previsão dos agentes.

Por fim, a discussão da função consumo e sua relação com a hipótese de velocidade de circulação da moeda constante está desassociada do restante do texto (``jogada''). 


* Resenha 3: Novos Keynesianos
:PROPERTIES:
:TAREFA:   Resenha 3
:OBJETIVO: Atingido parcialmente
:ARGUMENTO: Atingido parcialmente
:CONCEITOS: Atingido parcialmente
:DESENVOLVIMENTO: Atingido parcialmente
:CONCLUSAO: Atingindo minimamente
:CLAREZA:  Atingido satisfatoriamente
:NOTA:     Atingido parcialmente
  :END:
