#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 199967 - Jonas Pereira Cintra
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 199967
#+PROPERTY: NOME "Jonas Pereira Cintra"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido satisfatoriamente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido satisfatoriamente
  :CONCLUSAO: Atingido totalmente
  :CLAREZA:  Atingido satisfatoriamente
  :NOTA:     Atingido satisfatoriamente
  :END:

** Comentários individuais 

No início de sua resenha, apontou corretamente a principal implicação econômica do monetarismo: metas monetárias. Uma pequena correção: se você explicar os fundamentos teóricos e hipóteses associadas a ela, não é um axioma. Adiante, descreveu corretamente o conceito de taxa natural de desemprego. Vale destacar também que tal taxa pode ser alterada por medidas econômicas do lado da oferta sem que seja necessário afetar as preferências dos agentes. Outro elemento importante para que a taxa natural de desemprego seja atingida é a estabilidade do sistema econômico que é fundamentada pela TQM. Adiante, faz uma reconstrução histórica das diferentes versões da curva de Phillips e pontua a inclusão das expectativas para a formulação da versão aceleracionista. No parágrafo seguinte apresenta a ilusão monetária. Da forma que esta, parece um pouco confusa. Mais precisamente, os trabalhadores percebem ganhos nominais nos salários tal como se fossem ganhos reais. Em sua resenha, foi afirmado que os trabalhadores não percebem que a elevação dos salários nominais compensa a inflação. Isso não precisa ocorrer para que ocorra a ilusão monetária. Normalmente é o oposto, os trabalhadores acham que os ganhos salarias (nominais) são reais e, por conta disso, ofertam mais trabalho. Logo em seguida é afirmado corretamente que flutuações econômicas são resultado de inflações-surpresa. No entanto, faltou descrever qual a origem da inflação (variações nos agregados monetários diferentes (e maiores) que a taxa de crescimento da economia). Adiante, pontuou corretamente que o trade-off entre inflação e desemprego é temporário bem como os outros argumentos contra a discricionaridade. Mais a frente, é afirmado que a moeda é neutra no longo prazo. Esta correto, mas a construção desse resultado requereria uma discussão da TQM. Além disso, é dito que a taxa de juros se iguala a natural. É preciso tomar cuidado nesse ponto uma vez que a oferta de moeda é exógena e, por consequência, a taxa de juros é endógena. Nada impede que, mesmo sendo endógena, a taxa de juros se iguale a natural, mas é necessário alongar o argumento e explicar o porquê (não é o objetivo da resenha). Em seguida, faz um contraponto entre monetaristas e keynesianos ortodoxos. Adiante, pontua corretamente a dicotomia clássica ao expôr a TQM. Por fim, cabe aqui a menção que dada a importância da TQM para a teoria monetarista, poderia ter antecipado este debate.

