#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 213549 - Beatriz Helena Toledo Pastre
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 213549
#+PROPERTY: NOME "Beatriz Helena Toledo Pastre"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido parcialmente
  :ARGUMENTO: Atingindo minimamente
  :CONCEITOS: Atingindo minimamente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingindo minimamente
  :NOTA:     Atingindo minimamente
  :END:

** Comentários individuais 

Corretamente aponta que a regra monetária é a principal proposição do monetarismo, mas isso não implica na definição de metas de inflação, mas sim regras de expansão da base monetária. Adiante, corretamente coloca que a expansão (desregulada) da base monetária implica inflação. No entanto, cabe algumas correções. Este é um resultado e não um pressuposto do modelo. Além disso, expansão desregulada é um pouco impreciso. Mais exatamente, se a oferta de moeda crescer a uma taxa diferente da economia, haveria inflação ou deflação. Adiante, é pontuado que a moeda pode ser neutra se não houver variações no estoque de moeda. Incorreto. A moeda é neutra no longo prazo mesmo se o estoque de moeda variar no curto prazo (e não persistentemente). Adiante, afirma que partindo dos conceitos de taxa natural de desemprego e das diferentes versões da curva de Phillips é possível chegar à conclusão de que a moeda é neutra. Isso esta correto, mas não é apresentado o porquê desse resultado em sua resenha (os conceitos não estão sendo utilizados, apenas apresentados). Sendo assim, não é possível concluir (de seu texto) o porquê se deve adotar regras monetárias. Além disso, seria necessário apresentar as hipóteses e implicações relacionadas a TQM. A descrição da ilusão monetária também esta incompleta. Em seguida, quanto apresenta a TQM, incorre em algumas incompreensões. Tal como Friedman a resgata, passa a ser uma teoria da demanda por moeda. Como resultados das hipóteses associadas a ela, a demanda por moeda é estável. Além disso, o produto ser formado pelo uso dos fatores de produção não é exclusivo nem fundamental a TQM. Ao fim, quando elencas as recomendações de política econômica, não há nenhuma menção da regra monetária: estoque de moeda deve crescer a uma mesma taxa que a economia.
