#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 237534 - João Mateus Rodrigues da Silva
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 237534
#+PROPERTY: NOME "Joao Mateus Rodrigues da Silva"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingindo minimamente
  :ARGUMENTO: Atingido parcialmente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingindo minimamente
  :CONCLUSAO: Atingindo minimamente
  :CLAREZA:  Atingido parcialmente
  :NOTA:     Atingindo minimamente
  :END:

** Comentários individuais 

Sua resenha não possui introdução. Inicia apresentando a taxa de desemprego natural. Adiante a problematiza pela ausência da taxa de desemprego involuntário. Adiante, é dito que a taxa de desemprego natural seria um estabilizador econômico. Não é muito preciso. Essa taxa seria um ponto atrator. O que garantiria que a economia convergisse para lá é a ausência de instabilidades. Eis o porquê da TQM (ainda não mencionada) ser relevante. Em seguida, é corretamente pontuado que a taxa de desemprego natural não é imutável. Poderia apenas ter sido mais claro sobre o que pode fazer com que ela se altere (que tipo de políticas econômicas e "ações humanas"?). Adiante, faz uma reconstituição histórica das versões da curva de Phillips, mas não deixa claro que há uma relação *negativa e estável* entre inflação e desemprego. Na curva de Phillips aceleracionista, tal relação estável é negada no longo prazo. Em seguida é descrita a ilusão monetária. Em seguida, é dito que tal conclusão tem como base o embate entre discricionariedade e ativismo da política monetária. Mais precisamente, é o inverso. Tal conclusão recomenda as regras monetárias em detrimento do ativismo. Ao fim, é destacada a retomada da TQM, mas não há menção de que é reinterpretada enquanto uma teoria da demanda por moeda cujas hipóteses implicam estabilidade.
Vale destacar que não é discutido a proposição de regras monetárias em função dos conceitos anteriormente discutidos na resenha.
