#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 237856 - João Vitor Dos Santos Rodrigues
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 237856
#+PROPERTY: NOME "João Vitor Dos Santos Rodrigues"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido satisfatoriamente
  :ARGUMENTO: Atingido parcialmente
  :CONCEITOS: Atingindo minimamente
  :DESENVOLVIMENTO: Atingido satisfatoriamente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingido parcialmente
  :NOTA:     Atingido parcialmente
  :END:

** Comentários individuais 

No parágrafo de abertura situa a proposição de regras monetárias com a compreensão da inflação enquanto um fenômeno monetário. Adiante, pontua dois principais pontos do monetarismo, mas não há menção à TQM. Em seguida, descreve corretamente o conceito de taxa de desemprego natural. No entanto, existem algumas menções à teoria clássica que podem não ser compatíveis com a escola monetarista (notadamente a teoria valor-trabalho). Corretamente pontua a ausência do desemprego involuntário. Adiante, destaca que a taxa natural de desemprego não é imutável, mas atribui tal possibilidade de mudança à política monetária e fiscal. Mais precisamente, a taxa natural de desemprego só pode ser alterada em função de políticas do lado da oferta. Adiante, faz uma contextualização das diferentes versões da curva de Phillips. No entanto, da forma que escreve faz entender que a necessidade de incluir as expectativas inflacionárias decorrem da necessidade de antecipar a inflação somente. Para Friedman, a ausência de tal variável implica supor agentes não racionais/maximizadores. Adiante, é associado a taxa de desemprego efetiva abaixo da natural como pleno-emprego. Para os monetaristas, a taxa de desemprego natural era considerada como a de pleno-emprego (todos os que gostariam de trabalhar, dado o nível de salários, estão trabalhando. Lembrando que não é considerado desemprego involuntário). Adiante, é dito que a ilusão monetária afeta a taxa natural de desemprego. Incorreto. Afeta a taxa efetiva de desemprego uma vez que os trabalhadores ofertam mais trabalho dado que compreendem aumentos nominais tal como se fossem reais. Adiante, é destacado que a política monetária afeta a economia no curto prazo apenas. Vale destacar que até então não são explicitados os determinantes da inflação (dica: TQM tem um papel importante nisso). A seguir é afirmado que uma redução no estoque de moeda gera inflação. Incorreto. É justamente o oposto (taxa de crescimento dos estoques monetários maior que a taxa de crescimento do PIB real). Adiante, é relacionada a necessidade de gerar estabilidade para a garantia de sistemas sócios econômicos. Entendi o que quis dizer, mas esta bastante impreciso. Que tipos de sistemas sócio-econômicos? Adiante, os monetaristas são contrapostos aos keynesianos ortodoxos. A inflação é corretamente associada à mudanças no estoque de moeda via TQM. Poderia ter se aprofundado mais nas hipóteses associadas a essa teoria e suas implicações (demanda por moeda estável). A frase final foi pouco clara. Além disso, não é explicitada a proposição de regras monetárias e como elas devem ser seguidas (isto é, agregados monetários devem crescer a que taxa?).
* Resenha 2: Novos Clássicos                                        :private:
  :PROPERTIES:
  :TAREFA:   Resenha 2
  :OBJETIVO: Atingido parcialmente
  :ARGUMENTO: Atingido satisfatoriamente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido satisfatoriamente
  :CONCLUSAO: Atingido parcialmente
  :CLAREZA:  Atingido parcialmente
  :NOTA:     Atingido parcialmente
  :END:

** Comentários individuais

   Foram includos no documento enviado.

* Resenha 4: Regime de Metas para Inflação                                        :private:
:PROPERTIES:
:TAREFA:   Resenha 4
:OBJETIVO: Atingido parcialmente
:ARGUMENTO: Atingido satisfatoriamente
:CONCEITOS: Atingido satisfatoriamente
:DESENVOLVIMENTO: Atingido satisfatoriamente
:CONCLUSAO: Atingido parcialmente
:CLAREZA:  Atingido satisfatoriamente
:NOTA:     Atingido satisfatoriamente
:TURNITIN:
:END:

** Comentários individuais

Foram includos no documento enviado. 
