#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 242328 - Natalia Kimberlle Tavares Imperiano
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 242328
#+PROPERTY: NOME "Natalia Kimberlle Tavares Imperiano"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END
* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido satisfatoriamente
  :ARGUMENTO: Atingido parcialmente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingido totalmente
  :CLAREZA:  Atingindo minimamente
  :NOTA:     Atingido parcialmente
  :END:

** Comentários individuais 

Em seus parágrafos iniciais, contextualizou bem o texto a ser resenhado. Ao apresentar o conceito da taxa natural de desemprego,  mistura definição com implicação. Em outras palavras, parece que se perdeu um pouco ao apresentar o que compõe tal taxa enquanto descrevia o significado econômica de sua existência. Em seguida é dito como o papel das expectativas mudou desde a curva de Phillips. O que foi dito esta correto, mas pouco claro. As expectativas sempre tiveram um papel importante. A diferença é como elas foram incorporadas e quais as implicações dessas modificações. De todo modo, entendi o que quis dizer. Em seguida, foi pouco precisa ao pontuar as implicações da curva de Phillips aceleracionista. Dizer que "mudou gráficos" é insuficiente. Mais precisamente, poderia ter colocado que a inclusão das expectativas fez com que o trade-off entre inflação e desemprego fosse inexistente no longo prazo da a convergência da taxa de desemprego efetiva à natural. A descrição da ilusão monetária foi pouco clara. Uma forma de contornar essa questão pode ser por meio de uma organização dos encadeamentos teóricos ou por um encurtamento das frases. Percebi que compreendeu o conceito, mas não basta compreendê-lo, é preciso também apresentá-lo de forma compreensível. Em seguida, é destacada a questão da temporalidade da implementação de determinada política econômica e a defesa da discricionariedade. Adiante é mencionado que variações no estoque de moeda causa inflação. Para tal conclusão, seria necessário ter apresentado a TQM e suas hipóteses e implicações como a sua releitura enquanto uma teoria da demanda por moeda. Em seguida, é feito um contraponto das proposições monetaristas às keynesianas. Ao fim, descreve corretamente a proposição das regras monetárias a partir da TQM. Tendo isso em mente, sugere-se que tal discussão fosse antecipada para que os argumentos fossem melhor articulados. Note que a partir deste constructo teórico, é possível pontuar as origens da inflação e a proposição de política econômica. Fica aqui o registro de que associou a TQM enquanto uma teoria da demanda por moeda. Tal colocação esta correta. Poderia apenas estar mais articulada ao texto.

* Resenha 2: Novos Clássicos                                        :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido totalmente
  :ARGUMENTO: Atingido totalmente
  :CONCEITOS: Atingido parcialmente
  :DESENVOLVIMENTO: Atingido totalmente
  :CONCLUSAO: Atingido satisfatoriamente
  :CLAREZA:  Atingido totalmente
  :NOTA:     Atingido satisfatoriamente
  :END:

** Comentários individuais

   Foram includos no documento enviado.

* Resenha 3: Novos Keynesianos                                        :private:
:PROPERTIES:
:TAREFA:   Resenha 3
:OBJETIVO: Atingido parcialmente
:ARGUMENTO: Atingido satisfatoriamente
:CONCEITOS: Atingido parcialmente
:DESENVOLVIMENTO: Atingido parcialmente
:CONCLUSAO: Atingido parcialmente
:CLAREZA:  Atingido parcialmente
:NOTA:     Atingido parcialmente
:TURNITIN:
:END:

** Comentários individuais

Foram includos no documento enviado.
