#+OPTIONS: toc:nil num:nil tags:nil
#+TITLE: 257748 - Breno Rivelino Fima Castro
#+AUTHOR: Gabriel Petrini (PED)
#+PROPERTY: RA 257748
#+PROPERTY: NOME "Breno Rivelino Fima Castro"
#+INCLUDE_TAGS: private
#+PROPERTY: COLUMNS %TAREFA(Tarefa) %OBJETIVO(Objetivo) %CONCEITOS(Conceito) %ARGUMENTO(Argumento) %DESENVOLVIMENTO(Desenvolvimento) %CLAREZA(Clareza) %NOTA(Nota)
#+PROPERTY: TAREFA_ALL "Resenha 1" "Resenha 2" "Resenha 3" "Resenha 4" "Resenha 5" "Prova" "Seminário"
#+PROPERTY: OBJETIVO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCEITOS_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: ARGUMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: DESENVOLVIMENTO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CONCLUSAO_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: CLAREZA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"
#+PROPERTY: NOTA_ALL "Atingido totalmente" "Atingido satisfatoriamente" "Atingido parcialmente" "Atingindo minimamente" "Não atingido"


* Notas :private:

  #+BEGIN: columnview :maxlevel 3 :id global
  #+END

* Resenha 1: Monetaristas                                           :private:
  :PROPERTIES:
  :TAREFA:   Resenha 1
  :OBJETIVO: Atingido parcialmente
  :ARGUMENTO: Atingido parcialmente
  :CONCEITOS: Atingindo minimamente
  :DESENVOLVIMENTO: Atingido parcialmente
  :CONCLUSAO: Atingindo minimamente
  :CLAREZA:  Atingido parcialmente
  :NOTA:     Atingido parcialmente
  :END:

** Comentários individuais 

Em seu parágrafo de abertura, pontua que os monetaristas recomendam regras monetárias. No entanto, pelo que apresentou até então, não está claro o porquê desta recomendação de política econômica. Adiante, corretamente foi posicionado o monetarismo enquanto contraponto à escola precedente.

Adiante, aparecem algumas imprecisões quando discute o monetarismo enquanto uma antítese ao Keynesianismo. Em especial, é afirmado que há uma inversão na interpretação das variáveis macroeconômicas. Mais precisamente, pode-se dizer que há uma reversão de causalidade. Exemplo disso é que convergência ao nível de desemprego natural, estabilidade do setor privado e etc, são implicações e não hipótese dessa escola. Sendo um pouco menos abstrato, há convergência do nível de desemprego efetivo ao natural na ausência (por exemplo) de ilusão monetária. Na ausência desta ilusão, porquê haveria convergência? Porque os agentes são otimizadores, racionais, velocidade de circulação da moeda é estável e assim por diante. Em resumo, alguns dos pontos que foram colocados como hipóteses (inversão na interpretação) são implicações.

Em seguida, coloca que a recomendação de regras monetárias se dá pela tentativa de controlar o /trade-off/ entre inflação e desemprego. Alguns pontos a se considerarem aqui. Primeiro, um /trade-off/ pode existir independentemente das medidas de política econômica. O ponto é tentar fazer com que os /policy-makers/ evitem objetivar taxas menores de desemprego às custas de taxa de inflação persistentes. Além disso, da forma em que conduziu a sua resenha, não está claro porquê essa regra monetária evitaria uma taxa de crescimento da inflação insustentável. Nesse mesmo parágrafo, você corretamente pontuou que tal /trade-off/ existe apenas no curto prazo. No entanto, não avançou muito na explicação desse resultado. Em seguida, é mencionada a TQM enquanto embasamento teórico da relação de causalidade que parte da expansão monetária ao nível de preços. Porém, nada foi dito em relação às suas hipóteses (como velocidade de circulação da moeda constante, substitutibulidade da moeda por outros ativos e por ai vai).

Ao fim, quando discute as implicações do monetarismo, pontua a neutralidade da moeda no longo prazo, mas nada é dito a respeito do porquê deste resultado. Além disso, o monetarismo não implica impossibilidade do ativismo da política econômica. A principal recomendação é que a expansão monetária deve ser igual a taxa de crescimento da economia para que a taxa de inflação não seja persistentemente crescente. Dentre as recomendações de ativismo da política econômica, tem-se a ênfase em fatores do lado da oferta tal como desregulamentação, reestruturação de alguns mercados e etc. Não há, de um ponto de vista teórico, algo que impeça gastos sociais desde que seja compatível com as regras de expansão monetárias. Os tipos de gasto que você elencou são sim pouco indicados por esses autores, mas por outros motivos (ontológicos e metodológicos (individualismo principalmente)). 

No parágrafo final, é corretamente colocada recomendação de política econômica dessa escola. No entanto, a partir de sua resenha não estão claros os encadeamentos lógicos e teóricos para se obter este resultado.

* Resenha 3: Novos Keynesianos                                        :private:
:PROPERTIES:
:TAREFA:   Resenha 3
:OBJETIVO: Atingido parcialmente
:ARGUMENTO: Atingido parcialmente
:CONCEITOS: Atingido parcialmente
:DESENVOLVIMENTO: Atingido parcialmente
:CONCLUSAO: Atingido parcialmente
:CLAREZA:  Atingido parcialmente
:NOTA:     Atingido parcialmente
:TURNITIN:
:END:

** Comentários individuais

Foram includos no documento enviado.

* Resenha 4: Regime de Metas para Inflação                                        :private:
:PROPERTIES:
:TAREFA:   Resenha 4
:OBJETIVO: Atingido parcialmente
:ARGUMENTO: Atingido parcialmente
:CONCEITOS: Atingido satisfatoriamente
:DESENVOLVIMENTO: Atingido satisfatoriamente
:CONCLUSAO: Atingido satisfatoriamente
:CLAREZA:  Atingido parcialmente
:NOTA:     Atingido satisfatoriamente
:TURNITIN:
:END:

** Comentários individuais

Foram includos no documento enviado. 
