# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cjr/dev/qca/acq/kirq.ui'
#
# Created: Mon May 26 13:25:36 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Kirq(object):
    def setupUi(self, Kirq):
        Kirq.setObjectName(_fromUtf8("Kirq"))
        Kirq.resize(587, 926)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Kirq.sizePolicy().hasHeightForWidth())
        Kirq.setSizePolicy(sizePolicy)
        Kirq.setMinimumSize(QtCore.QSize(0, 400))
        self.centralwidget = QtGui.QWidget(Kirq)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.centralPlace = QtGui.QWidget(self.centralwidget)
        self.centralPlace.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralPlace.sizePolicy().hasHeightForWidth())
        self.centralPlace.setSizePolicy(sizePolicy)
        self.centralPlace.setMinimumSize(QtCore.QSize(0, 0))
        self.centralPlace.setObjectName(_fromUtf8("centralPlace"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.centralPlace)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.centralLayout = QtGui.QHBoxLayout()
        self.centralLayout.setObjectName(_fromUtf8("centralLayout"))
        self.horizontalLayout_16.addLayout(self.centralLayout)
        self.horizontalLayout_5.addWidget(self.centralPlace)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.historySearchComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historySearchComboBox.sizePolicy().hasHeightForWidth())
        self.historySearchComboBox.setSizePolicy(sizePolicy)
        self.historySearchComboBox.setEditable(True)
        self.historySearchComboBox.setFrame(True)
        self.historySearchComboBox.setObjectName(_fromUtf8("historySearchComboBox"))
        self.horizontalLayout.addWidget(self.historySearchComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.historyLayout = QtGui.QVBoxLayout()
        self.historyLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.historyLayout.setObjectName(_fromUtf8("historyLayout"))
        self.verticalLayout.addLayout(self.historyLayout)
        self.KirqTabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KirqTabWidget.sizePolicy().hasHeightForWidth())
        self.KirqTabWidget.setSizePolicy(sizePolicy)
        self.KirqTabWidget.setMinimumSize(QtCore.QSize(140, 208))
        self.KirqTabWidget.setToolTip(_fromUtf8(""))
        self.KirqTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.KirqTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.KirqTabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.KirqTabWidget.setMovable(True)
        self.KirqTabWidget.setObjectName(_fromUtf8("KirqTabWidget"))
        self.NecessityWidget = QtGui.QWidget()
        self.NecessityWidget.setObjectName(_fromUtf8("NecessityWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.NecessityWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.NecessityWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.necConsistSlider = QtGui.QSlider(self.NecessityWidget)
        self.necConsistSlider.setMaximum(100)
        self.necConsistSlider.setSingleStep(1)
        self.necConsistSlider.setPageStep(1)
        self.necConsistSlider.setProperty("value", 90)
        self.necConsistSlider.setOrientation(QtCore.Qt.Horizontal)
        self.necConsistSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.necConsistSlider.setTickInterval(10)
        self.necConsistSlider.setObjectName(_fromUtf8("necConsistSlider"))
        self.horizontalLayout_2.addWidget(self.necConsistSlider)
        self.necConsistSpinBox = QtGui.QDoubleSpinBox(self.NecessityWidget)
        self.necConsistSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.necConsistSpinBox.setAccelerated(False)
        self.necConsistSpinBox.setPrefix(_fromUtf8(""))
        self.necConsistSpinBox.setSuffix(_fromUtf8(""))
        self.necConsistSpinBox.setMaximum(1.0)
        self.necConsistSpinBox.setSingleStep(0.01)
        self.necConsistSpinBox.setProperty("value", 0.9)
        self.necConsistSpinBox.setObjectName(_fromUtf8("necConsistSpinBox"))
        self.horizontalLayout_2.addWidget(self.necConsistSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.NecessityWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.necCoverageSlider = QtGui.QSlider(self.NecessityWidget)
        self.necCoverageSlider.setMaximum(100)
        self.necCoverageSlider.setPageStep(1)
        self.necCoverageSlider.setProperty("value", 50)
        self.necCoverageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.necCoverageSlider.setObjectName(_fromUtf8("necCoverageSlider"))
        self.horizontalLayout_7.addWidget(self.necCoverageSlider)
        self.necCoverageSpinBox = QtGui.QDoubleSpinBox(self.NecessityWidget)
        self.necCoverageSpinBox.setPrefix(_fromUtf8(""))
        self.necCoverageSpinBox.setSuffix(_fromUtf8(""))
        self.necCoverageSpinBox.setMaximum(1.0)
        self.necCoverageSpinBox.setSingleStep(0.01)
        self.necCoverageSpinBox.setProperty("value", 0.5)
        self.necCoverageSpinBox.setObjectName(_fromUtf8("necCoverageSpinBox"))
        self.horizontalLayout_7.addWidget(self.necCoverageSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.necReduceButton = QtGui.QPushButton(self.NecessityWidget)
        self.necReduceButton.setEnabled(True)
        self.necReduceButton.setObjectName(_fromUtf8("necReduceButton"))
        self.horizontalLayout_4.addWidget(self.necReduceButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.KirqTabWidget.addTab(self.NecessityWidget, _fromUtf8(""))
        self.SufficiencyWidget = QtGui.QWidget()
        self.SufficiencyWidget.setObjectName(_fromUtf8("SufficiencyWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.SufficiencyWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.SufficiencyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 15))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem4 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.sufReduceToComboBox = QtGui.QComboBox(self.SufficiencyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sufReduceToComboBox.sizePolicy().hasHeightForWidth())
        self.sufReduceToComboBox.setSizePolicy(sizePolicy)
        self.sufReduceToComboBox.setMaxVisibleItems(4)
        self.sufReduceToComboBox.setMaxCount(4)
        self.sufReduceToComboBox.setObjectName(_fromUtf8("sufReduceToComboBox"))
        self.horizontalLayout_9.addWidget(self.sufReduceToComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.SufficiencyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 15))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem5 = QtGui.QSpacerItem(18, 15, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.sufFrequencySpinBox = QtGui.QSpinBox(self.SufficiencyWidget)
        self.sufFrequencySpinBox.setMinimum(1)
        self.sufFrequencySpinBox.setMaximum(999999999)
        self.sufFrequencySpinBox.setObjectName(_fromUtf8("sufFrequencySpinBox"))
        self.horizontalLayout_8.addWidget(self.sufFrequencySpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_5 = QtGui.QLabel(self.SufficiencyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 14))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_15.addWidget(self.label_5)
        spacerItem6 = QtGui.QSpacerItem(40, 15, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.sufConsistencySlider = QtGui.QSlider(self.SufficiencyWidget)
        self.sufConsistencySlider.setMinimum(50)
        self.sufConsistencySlider.setMaximum(100)
        self.sufConsistencySlider.setProperty("value", 90)
        self.sufConsistencySlider.setOrientation(QtCore.Qt.Horizontal)
        self.sufConsistencySlider.setObjectName(_fromUtf8("sufConsistencySlider"))
        self.horizontalLayout_10.addWidget(self.sufConsistencySlider)
        self.sufConsistencySpinBox = QtGui.QDoubleSpinBox(self.SufficiencyWidget)
        self.sufConsistencySpinBox.setMinimum(0.5)
        self.sufConsistencySpinBox.setMaximum(1.0)
        self.sufConsistencySpinBox.setSingleStep(0.01)
        self.sufConsistencySpinBox.setProperty("value", 0.9)
        self.sufConsistencySpinBox.setObjectName(_fromUtf8("sufConsistencySpinBox"))
        self.horizontalLayout_10.addWidget(self.sufConsistencySpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_6 = QtGui.QLabel(self.SufficiencyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 15))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_12.addWidget(self.label_6)
        spacerItem7 = QtGui.QSpacerItem(40, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.sufProportionSlider = QtGui.QSlider(self.SufficiencyWidget)
        self.sufProportionSlider.setMaximum(100)
        self.sufProportionSlider.setProperty("value", 100)
        self.sufProportionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sufProportionSlider.setObjectName(_fromUtf8("sufProportionSlider"))
        self.horizontalLayout_13.addWidget(self.sufProportionSlider)
        self.sufProportionSpinBox = QtGui.QDoubleSpinBox(self.SufficiencyWidget)
        self.sufProportionSpinBox.setMaximum(1.0)
        self.sufProportionSpinBox.setSingleStep(0.01)
        self.sufProportionSpinBox.setProperty("value", 1.0)
        self.sufProportionSpinBox.setObjectName(_fromUtf8("sufProportionSpinBox"))
        self.horizontalLayout_13.addWidget(self.sufProportionSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem8 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.sufGenerateGttButton = QtGui.QPushButton(self.SufficiencyWidget)
        self.sufGenerateGttButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sufGenerateGttButton.sizePolicy().hasHeightForWidth())
        self.sufGenerateGttButton.setSizePolicy(sizePolicy)
        self.sufGenerateGttButton.setMinimumSize(QtCore.QSize(0, 23))
        self.sufGenerateGttButton.setObjectName(_fromUtf8("sufGenerateGttButton"))
        self.horizontalLayout_14.addWidget(self.sufGenerateGttButton)
        self.sufReduceButton = QtGui.QPushButton(self.SufficiencyWidget)
        self.sufReduceButton.setMinimumSize(QtCore.QSize(0, 23))
        self.sufReduceButton.setObjectName(_fromUtf8("sufReduceButton"))
        self.horizontalLayout_14.addWidget(self.sufReduceButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.KirqTabWidget.addTab(self.SufficiencyWidget, _fromUtf8(""))
        self.verticalLayout.addWidget(self.KirqTabWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        Kirq.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(Kirq)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        Kirq.setStatusBar(self.statusBar)
        self.menubar = QtGui.QMenuBar(Kirq)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName(_fromUtf8("menuOption"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        Kirq.setMenuBar(self.menubar)
        self.toolbar = QtGui.QToolBar(Kirq)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar.sizePolicy().hasHeightForWidth())
        self.toolbar.setSizePolicy(sizePolicy)
        self.toolbar.setMinimumSize(QtCore.QSize(0, 50))
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        Kirq.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.actionDocumentation = QtGui.QAction(Kirq)
        self.actionDocumentation.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/help-contents.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentation.setIcon(icon)
        self.actionDocumentation.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionAbout = QtGui.QAction(Kirq)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/help-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpenDataSet = QtGui.QAction(Kirq)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenDataSet.setIcon(icon2)
        self.actionOpenDataSet.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionOpenDataSet.setObjectName(_fromUtf8("actionOpenDataSet"))
        self.actionClose = QtGui.QAction(Kirq)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionSave = QtGui.QAction(Kirq)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(Kirq)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionFilterDlg = QtGui.QAction(Kirq)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/edit-find-project.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilterDlg.setIcon(icon4)
        self.actionFilterDlg.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionFilterDlg.setObjectName(_fromUtf8("actionFilterDlg"))
        self.actionShow_these_tables_by_default = QtGui.QAction(Kirq)
        self.actionShow_these_tables_by_default.setObjectName(_fromUtf8("actionShow_these_tables_by_default"))
        self.actionSimplification_level_0 = QtGui.QAction(Kirq)
        self.actionSimplification_level_0.setCheckable(True)
        self.actionSimplification_level_0.setObjectName(_fromUtf8("actionSimplification_level_0"))
        self.actionSimplification_level_1 = QtGui.QAction(Kirq)
        self.actionSimplification_level_1.setCheckable(True)
        self.actionSimplification_level_1.setObjectName(_fromUtf8("actionSimplification_level_1"))
        self.actionSimplification_level_2 = QtGui.QAction(Kirq)
        self.actionSimplification_level_2.setCheckable(True)
        self.actionSimplification_level_2.setChecked(True)
        self.actionSimplification_level_2.setObjectName(_fromUtf8("actionSimplification_level_2"))
        self.actionSimplification_level_3 = QtGui.QAction(Kirq)
        self.actionSimplification_level_3.setCheckable(True)
        self.actionSimplification_level_3.setObjectName(_fromUtf8("actionSimplification_level_3"))
        self.actionMultiSort = QtGui.QAction(Kirq)
        self.actionMultiSort.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/view-sort-ascending.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMultiSort.setIcon(icon5)
        self.actionMultiSort.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionMultiSort.setObjectName(_fromUtf8("actionMultiSort"))
        self.actionSaveSession = QtGui.QAction(Kirq)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/document-export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveSession.setIcon(icon6)
        self.actionSaveSession.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSaveSession.setObjectName(_fromUtf8("actionSaveSession"))
        self.actionLoadSession = QtGui.QAction(Kirq)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/document-import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadSession.setIcon(icon7)
        self.actionLoadSession.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionLoadSession.setObjectName(_fromUtf8("actionLoadSession"))
        self.actionClearSession = QtGui.QAction(Kirq)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/document-close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearSession.setIcon(icon8)
        self.actionClearSession.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionClearSession.setObjectName(_fromUtf8("actionClearSession"))
        self.actionExportTable = QtGui.QAction(Kirq)
        self.actionExportTable.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportTable.setIcon(icon9)
        self.actionExportTable.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionExportTable.setObjectName(_fromUtf8("actionExportTable"))
        self.actionPreferences = QtGui.QAction(Kirq)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/preferences-other.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon10)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionPrintTable = QtGui.QAction(Kirq)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/22x22/printer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrintTable.setIcon(icon11)
        self.actionPrintTable.setObjectName(_fromUtf8("actionPrintTable"))
        self.menuFile.addAction(self.actionOpenDataSet)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveSession)
        self.menuFile.addAction(self.actionLoadSession)
        self.menuFile.addAction(self.actionClearSession)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportTable)
        self.menuFile.addAction(self.actionPrintTable)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOption.addAction(self.actionMultiSort)
        self.menuOption.addAction(self.actionFilterDlg)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Kirq)
        self.KirqTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Kirq)

    def retranslateUi(self, Kirq):
        Kirq.setWindowTitle(_translate("Kirq", "Kirq", None))
        self.label_2.setText(_translate("Kirq", "Session:", None))
        self.historySearchComboBox.setToolTip(_translate("Kirq", "Search through history", None))
        self.historySearchComboBox.setStatusTip(_translate("Kirq", "Search through history", None))
        self.KirqTabWidget.setStatusTip(_translate("Kirq", "Modify sufficiency reduction aggression", None))
        self.KirqTabWidget.setWhatsThis(_translate("Kirq", "Modify sufficiency reduction aggression", None))
        self.label.setText(_translate("Kirq", "Consistency Threshold", None))
        self.necConsistSlider.setToolTip(_translate("Kirq", "Modify consistency threshold", None))
        self.necConsistSlider.setStatusTip(_translate("Kirq", "Modify consistency threshold", None))
        self.necConsistSpinBox.setToolTip(_translate("Kirq", "Modify consistency threshold", None))
        self.necConsistSpinBox.setStatusTip(_translate("Kirq", "Modify consistency threshold", None))
        self.label_3.setText(_translate("Kirq", "Coverage Threshold", None))
        self.necCoverageSlider.setToolTip(_translate("Kirq", "Modify coverage threshold", None))
        self.necCoverageSlider.setStatusTip(_translate("Kirq", "Modify coverage threshold", None))
        self.necCoverageSpinBox.setToolTip(_translate("Kirq", "Modify coverage threshold", None))
        self.necCoverageSpinBox.setStatusTip(_translate("Kirq", "Modify coverage threshold", None))
        self.necReduceButton.setToolTip(_translate("Kirq", "Perform necessity analysis on current data set", None))
        self.necReduceButton.setStatusTip(_translate("Kirq", "Perform necessity analysis on current data set", None))
        self.necReduceButton.setText(_translate("Kirq", "Analyze", None))
        self.KirqTabWidget.setTabText(self.KirqTabWidget.indexOf(self.NecessityWidget), _translate("Kirq", "Necessity", None))
        self.KirqTabWidget.setTabToolTip(self.KirqTabWidget.indexOf(self.NecessityWidget), _translate("Kirq", "Perform a Necessity Analysis", None))
        self.label_7.setText(_translate("Kirq", "Reduce to", None))
        self.sufReduceToComboBox.setToolTip(_translate("Kirq", "Modify sufficiency reduction aggression", None))
        self.sufReduceToComboBox.setStatusTip(_translate("Kirq", "Modify sufficiency reduction aggression", None))
        self.label_4.setText(_translate("Kirq", "Frequency Threshold", None))
        self.sufFrequencySpinBox.setToolTip(_translate("Kirq", "modify frequency threshold", None))
        self.sufFrequencySpinBox.setStatusTip(_translate("Kirq", "modify frequency threshold", None))
        self.label_5.setText(_translate("Kirq", "Consistency Threshold", None))
        self.sufConsistencySlider.setToolTip(_translate("Kirq", "Modify consistency threshold", None))
        self.sufConsistencySlider.setStatusTip(_translate("Kirq", "Modify consistency threshold", None))
        self.sufConsistencySpinBox.setToolTip(_translate("Kirq", "Modify consistency threshold", None))
        self.sufConsistencySpinBox.setStatusTip(_translate("Kirq", "Modify consistency threshold", None))
        self.label_6.setText(_translate("Kirq", "Proportion Threshold", None))
        self.sufProportionSlider.setToolTip(_translate("Kirq", "Modify proportion threshold", None))
        self.sufProportionSlider.setStatusTip(_translate("Kirq", "Modify proportion threshold", None))
        self.sufProportionSpinBox.setToolTip(_translate("Kirq", "Modify proportion threshold", None))
        self.sufProportionSpinBox.setStatusTip(_translate("Kirq", "Modify proportion threshold", None))
        self.sufGenerateGttButton.setToolTip(_translate("Kirq", "Reduce data set to truth table", None))
        self.sufGenerateGttButton.setStatusTip(_translate("Kirq", "Reduce data set to truth table", None))
        self.sufGenerateGttButton.setText(_translate("Kirq", "TruthTable", None))
        self.sufReduceButton.setToolTip(_translate("Kirq", "Reduce data set or truth table to sufficiency analysis", None))
        self.sufReduceButton.setStatusTip(_translate("Kirq", "Reduce data set or truth table to sufficiency analysis", None))
        self.sufReduceButton.setText(_translate("Kirq", "Reduce", None))
        self.KirqTabWidget.setTabText(self.KirqTabWidget.indexOf(self.SufficiencyWidget), _translate("Kirq", "Sufficiency", None))
        self.KirqTabWidget.setTabToolTip(self.KirqTabWidget.indexOf(self.SufficiencyWidget), _translate("Kirq", "Perform a sufficiency analysis", None))
        self.menuFile.setTitle(_translate("Kirq", "File", None))
        self.menuOption.setTitle(_translate("Kirq", "Options", None))
        self.menuHelp.setTitle(_translate("Kirq", "Help", None))
        self.toolbar.setWindowTitle(_translate("Kirq", "toolBar", None))
        self.actionDocumentation.setText(_translate("Kirq", "Documentation", None))
        self.actionDocumentation.setToolTip(_translate("Kirq", "View online documentation", None))
        self.actionDocumentation.setStatusTip(_translate("Kirq", "View online documentation.", None))
        self.actionDocumentation.setShortcut(_translate("Kirq", "Ctrl+H", None))
        self.actionAbout.setText(_translate("Kirq", "About", None))
        self.actionAbout.setToolTip(_translate("Kirq", "View copyright information", None))
        self.actionAbout.setStatusTip(_translate("Kirq", "View copyright information.", None))
        self.actionAbout.setShortcut(_translate("Kirq", "Ctrl+A", None))
        self.actionOpenDataSet.setText(_translate("Kirq", "Import Data", None))
        self.actionOpenDataSet.setStatusTip(_translate("Kirq", "Open a data set file.", None))
        self.actionOpenDataSet.setShortcut(_translate("Kirq", "Ctrl+O", None))
        self.actionClose.setText(_translate("Kirq", "Close", None))
        self.actionSave.setText(_translate("Kirq", "Save", None))
        self.actionExit.setText(_translate("Kirq", "Exit", None))
        self.actionExit.setStatusTip(_translate("Kirq", "Close Kirq application.", None))
        self.actionExit.setShortcut(_translate("Kirq", "Ctrl+Q", None))
        self.actionFilterDlg.setText(_translate("Kirq", "Filter", None))
        self.actionFilterDlg.setToolTip(_translate("Kirq", "Open filter dialog", None))
        self.actionFilterDlg.setStatusTip(_translate("Kirq", "Open filter dialog.", None))
        self.actionFilterDlg.setShortcut(_translate("Kirq", "Ctrl+F", None))
        self.actionShow_these_tables_by_default.setText(_translate("Kirq", "Show these tables by default", None))
        self.actionSimplification_level_0.setText(_translate("Kirq", "Simplification level 0", None))
        self.actionSimplification_level_1.setText(_translate("Kirq", "Simplification level 1", None))
        self.actionSimplification_level_2.setText(_translate("Kirq", "Simplification level 2", None))
        self.actionSimplification_level_3.setText(_translate("Kirq", "Simplification level 3", None))
        self.actionMultiSort.setText(_translate("Kirq", "Multi-sort", None))
        self.actionMultiSort.setToolTip(_translate("Kirq", "Sort by multiple columns.", None))
        self.actionMultiSort.setStatusTip(_translate("Kirq", "Sort by multiple columns.", None))
        self.actionMultiSort.setShortcut(_translate("Kirq", "Ctrl+M", None))
        self.actionSaveSession.setText(_translate("Kirq", "Save Session", None))
        self.actionSaveSession.setStatusTip(_translate("Kirq", "Save this session to .kirq file.", None))
        self.actionSaveSession.setShortcut(_translate("Kirq", "Ctrl+S", None))
        self.actionLoadSession.setText(_translate("Kirq", "Load Session", None))
        self.actionLoadSession.setStatusTip(_translate("Kirq", "Load a .kirq session file.", None))
        self.actionLoadSession.setShortcut(_translate("Kirq", "Ctrl+L", None))
        self.actionClearSession.setText(_translate("Kirq", "Clear Session", None))
        self.actionClearSession.setStatusTip(_translate("Kirq", "Clear all session history.", None))
        self.actionClearSession.setShortcut(_translate("Kirq", "Ctrl+C", None))
        self.actionExportTable.setText(_translate("Kirq", "Export Table", None))
        self.actionExportTable.setStatusTip(_translate("Kirq", "Export table to plain text.", None))
        self.actionExportTable.setShortcut(_translate("Kirq", "Ctrl+E", None))
        self.actionPreferences.setText(_translate("Kirq", "Preferences", None))
        self.actionPrintTable.setText(_translate("Kirq", "Print Table", None))
        self.actionPrintTable.setStatusTip(_translate("Kirq", "Print table.", None))
        self.actionPrintTable.setShortcut(_translate("Kirq", "Ctrl+P", None))

import kirq_resources_rc
