
* Conclusion TODOs                                                 :noexport:

* Concluding Remarks                                                 :ignore:



This paper contributes to demand-led growth agenda, taking in consideration recent efforts of embedding it in a SFC framework.
Our novelty is twofold: (i) inclusion of residential investment and (ii) determination of its growth rate by houses' own interest rate.
Residential investment was included due to recent empirical works showing its relevance for macroeconomic dynamics.
Houses' own interest rate allowed us to include asset bubbles in a Sraffian strand.
As far as we know, none works have described this expenditure with this particular real interest rate.

Our model reports standard results of Sraffian supermultiplier:
    (i) utilization rate converges to the normal one through changes on firms' marginal propensity to invest;
    (ii) GDP growth rate converges to NCC autonomous expenditure growth rate and;
    (iii) income distribution affects growth rate only during the traverse.
A particular feature of our model is the dual composition of capital stock: firms' capacity creating and real estate.
The most distinct result is the decrease of houses share on capital stock due to the increase of residential investment growth rate.
Although counterintuitive, this occurs because firms react to the discrepancies between actual and desired utilization rates.
In other words, for capacity utilization converges to the normal one,  firms' investment needs to grow temporarily faster than residential investment, changing the ratio between houses and total capital stock at the fully adjusted position.

Finally, it worth noting that this is a first step of a wider research agenda on the role of residential investment for economic growth and business cycles. 
Future research should increase the complexity of this model in order to understand some recent dynamics (such as increases of mortgages share on banks' balance sheet). 
In regarding residential investment, some extensions are: exploring other determinants of its growth rate and  its effects on banks' net financial wealth.
This emerging ``housing agenda'' should also moves towards institutional grounds[fn:Lucas].
For example, future research could assess which institutional arrangements allow/inhibit the connection between asset bubble, credit granting/rationing and financial instability.


[fn:Lucas] *OBS:* Optei por dar pistas do capítulo do QCA invés do modelo AB-SFC. Fiz isso porque acho mais fácil alguém `agentizar' nosso SFC (transformar em ABM) do que pensar no QCA. Acha que é uma boa estratégia ou acha melhor a gente demarcar que estamos com AB-SFC nos nossos planos? 

