
* Conclusion TODOs                                                 :noexport:

* Concluding Remarks                                                 :ignore:



This paper contributes to demand-led growth agenda, taking in consideration recent efforts of embedding it in a SFC framework.
Our novelty is the introduction of residential investment determined by houses own rate of interest in a SSM-SFC model.
Residential investment has beeen included due to recent empirical works showing its relevance for macroeconomic dynamics.
Houses' own rate of interest allowed us to connect asset bubbles with aggregate demand in a rather parsimonious way.

Our model reports standard results of Sraffian Supermultiplier:
    (i) utilization rate converges to the normal one through changes on firms' marginal propensity to invest;
    (ii) GDP growth rate converges to NCC autonomous expenditure growth rate and;
    (iii) income distribution affects growth rate only during the traverse.
A particular feature of our model is the dual composition of capital stock: firms' capacity creating and real estate.
The most distinct result is the decrease of houses share on capital stock due to the increase of residential investment growth rate.
Although counterintuitive, this occurs because firms react to the discrepancies between actual and desired utilization rates.
In other words, for capacity utilization converges to the normal one,  firms' investment needs to grow temporarily faster than residential investment, changing the ratio between houses and total capital stock at the fully adjusted position.

Future research should increase the complexity of this model in order to understand other consequences of residential investment.
Some extensions could be exploring other determinants of its growth rate and  its effects on banks' net financial wealth.
This emerging ``housing agenda'' should also moves towards institutional grounds.
For example, future research could assess which institutional arrangements allow/inhibit the connection between asset bubble, credit granting/rationing and financial instability.
Nevertheless, this is a first step in a wider research agenda on the role of residential investment for economic growth and business cycles. 


