* Model TODOs                                                      :noexport:
bibliography:refs.bib

* A Sraffian supermultiplier SFC model with residential investment   :ignore:

** General equations

Our model is the most parsimonious as possible: a closed capitalist economy without government sector. Output ($Y$) is determined by  a fixed combination of a homogeneous labor input with homogeneous fixed business capital ($K_f$).
For simplicity, we put technological progress, depreciation and goods inflation aside so investment is presented in net terms and all variables --- except for houses --- are measured in real terms.
Assuming a Leontief production function (Equation ref:_Leontieff) and that growth is not constrained by labor scarcity, full capacity output ($Y_{FC}$) is
determined by firms' capital stock (Equation ref:_YFC):

#+begin_export latex
\begin{equation}
\label{_YFC}
    \myRed{Y_{K}} = \frac{K_{f_{-1}}}{v}
\end{equation}
%\begin{equation}
% \label{_Leontieff}
%     \myRed{Y_{FC} = \min (Y_L, Y_K)}
%\end{equation}
\begin{equation}
\label{_u}
    u = \frac{Y}{\myRed{Y_{K}}}
\end{equation}
#+end_export
where  $v$ is exogenous capital-output ratio and $u$ is rate of capacity utilization.

We further assume a social structure composed by both workers (denoted by subscript $w$) and capitalists (denoted by subscript $k$) households.
Thus, demand determined output level ($Y$, Equation ref:_Y)  is the sum of workers and capitalists consumption ($C_w$ and $C_k$ respectively) and both households and firms investment ($I_h$ and $I_f$ respectively) and only the latter creates capacity to the business sector of the economy:

#+begin_export latex
\begin{equation}
\label{_Ct}
    C = C_w + C_k
\end{equation}
\begin{equation}
\label{_It}
    I_t = I_f + I_h
\end{equation}
\begin{equation}
\label{_Y}
    Y = \overbrace{[C_w + \underbrace{C_k + I_h}_{\text{Capitalists}}]}^{\text{Households}} + \overbrace{[I_f]}^{\text{Firms}}
\end{equation}
#+end_export

In other words, from a institutional sectors perspective, household expenditures have two components (consumption and residential investment) and firms just one (non-residential investment).
So, the novelty of this model is the inclusion of a second investment component all made by household sector and held by capitalists households for simplicity. 
Therefore, this economy produces two types of real assets: firms productive capital ($K_f$) and households houses ($K_h$):

#+begin_export latex
\begin{equation}
    \label{_K}
    K = K_f + K_h
\end{equation}
#+end_export

Denoting the houses share in total real assets as $k$ (Equation ref:_k), we can rewrite equation \ref{_K} as:

#+begin_export latex
\begin{equation}
\label{_k}
    k = \frac{K_h}{K}
\end{equation}
#+end_export

Following Sraffian literature, functional income distribution is determined by \myRed{historical and institutional} factors and class struggle.
As consequence, wage-share ($\omega$) is considered exogenous to our model and define total wages as ($W$, Eq. ref:_W):

#+begin_export latex
\begin{equation}
\label{_W}
    W = \omega\cdot Y
\end{equation}
#+end_export

Table \ref{Matriz_Estoques} presents the balance sheet matrix for all institutional sectors. 
Capitalists households hold financial wealth as bank deposits ($M$) and residential investment is financed by mortgages ($MO$).
Capitalists' total net wealth ($NW_{k}$) is the sum of their net financial wealth ($V_{k}$) and real assets (\textit{i.e.} houses, $K_h$).
Table  \ref{Matriz_Fluxos} presents both transactions flows and the flow of funds matrix. 
This table shows all economic relations between institutional sectors ensuring that there is no  ``black holes''
so all financial and real transaction are explicitly defined cite:godley_monetary_2007,macedo_e_silva_peering_2011.

In this model, \myRed{capitalist consumption ($C_{k}$) depends on its disposable income ($YD_{hk}$)} while workers consumption ($C_w$) is fully induced by their wages.
We assume that workers expend what they earn while capitalists earn what they expend, so workers financial and real wealth are both null.
Firms finance their investment primarily by undistributed profits ($FU$) and the residual by bank loans ($L_f$) --- thus they do not hold deposits. 
Banks create credit /ex nihilo/ and then collect the deposits, paying the same interest rate that they charge.
On the following subsections, we will present the equations of each of those institutional sectors.

#+begin_export latex
\begin{table}[H]
\centering
\caption{Balance Sheet matrix}
\label{Matriz_Estoques}
\begin{tabular}{lccccc}
\hline
\hline
                          & Workers & Capitalists      & Firms        & Banks  &    $\sum$ \\ \hline

Deposits & & $+M$ & & $-M$ & 0\\
Loans& & $ $ &$-L_f$& $\myRed{+L_{f}}$ & 0\\
Mortages & &$-MO$&  & $+MO$ & 0\\\hline
$\sum$ Net Financial Wealth &$\myRed{0}$ &$V_{k}$&$V_f$&$\myRed{0}$& $0$\\\hline
Capital & & &$+K_f$&  & $+K_f$\\
Houses & &$+K_{hd}$& &   & $+K_h$\\\hline
$\sum$ Net Wealth &$\myRed{0}$&$NW_{k}$&$NW_f$&$\myRed{0}$& $+K$\\
\hline
\hline
\end{tabular}%
\caption*{\textbf{Source:} Authors' Elaboration}
\end{table}
#+end_export

#+begin_export latex
\begin{table}[H]
\centering
\caption{Transactions flow matrix and flow of funds}
\label{Matriz_Fluxos}
\resizebox{\textwidth}{!}{%
\begin{tabular}{lccccccc}
\hline
\hline
& Workers
& \multicolumn{2}{c}{Capitalists}
& \multicolumn{2}{c}{Firms}
& Banks       & Total    \\ \cline{3-4}\cline{5-6}
& &
Current & Capital &
Current & Capital     &
&       $\sum$ \\
Consumption                       &$-Cw$&$-C_k$& & $+C$& & & 0\\
Non-residential Investment                   & & & &$+I_f$&$-I_f$ & & 0\\
Residential Investment       &  & &$-I_h$&$+I_h$& & & 0\\
\textbf{{[}Output{]}}   & & & &{[}$Y${]}& & & {[}$Y${]}\\
Wages                        &$+W$&& &$-W$& & & 0\\
Profits                      & &$+FD$& &$-FT$&$+FU$& & 0\\
Deposits interest rate         & &$+r_m\cdot M_{-1}$& && &$-r_m\cdot M_{-1}$& 0\\
Loans interest rate         & & & &$-r_l\cdot L_{f_{-1}}$& &$\myRed{+r_l\cdot L_{f_{-1}}}$& 0\\

Mortages interest rates         & &$-r_{mo}\cdot MO_{-1}$& && &$+r_{mo}\cdot MO_{-1}$& 0\\\hline
\textbf{Subtotal}           &$\myRed{0}$&$+S_h$&$-I_h$& $\myRed{0}$ &$+NFW_f$&$\myRed{0}$& 0\\\hline
Change in deposits     & &$-\Delta M$& & & &$+\Delta M$& 0\\
Change in mortgages     & & &$+ \Delta MO$& & &$-\Delta MO$& 0\\
Change in loans     & & &&& $\myRed{+\Delta L_{f}}$ &$\myRed{-\Delta L_{f}}$& 0\\
\textbf{Total} & $\myRed{0}$& 0 & 0 & 0  & 0  & 0  & 0\\
\hline
\hline
\end{tabular}%
}
\caption*{\textbf{Source:} Authors' Elaboration}
\end{table}
#+end_export


** Firms

In order to produce, firms purchase capital goods ($-I_f$ in capital account) and hire workers, whom total remuneration is the economy wage bill. 
Firms total profits ($FT$, Equation ref:_FT) are a residual between sales ($Y$) and total wages ($W$).
Firms retain part ($\gamma_F$) of profits net of interest payments ($FU$, Equation ref:_FU) --- to reinvest --- and distribute the remainder to capitalists ($FD$, Equation ref:_FD):

#+begin_export latex
\begin{equation}
\label{_FT}
    FT = Y - W = FD + FU + r_{l}\cdot L_{f_{-1}}
\end{equation}
\begin{equation}
\label{_FU}
    FU = \gamma_F\cdot (FT - r_l\cdot L_{f_{-1}})
\end{equation}
\begin{equation}
\label{_FD}
    FD = (1-\gamma_F)\cdot (FT - r_l\cdot L_{f_{-1}})
\end{equation}
#+end_export

Firms (non-residential) investment is fully induced by the level of effective demand (Eq. ref:_If), and its growth rate changes accordingly to the capital stock adjustment principle cite:freitas_growth_2015.
Equation ref:_h is a simple way to describe this mechanism.
According to it, the marginal propensity to invest ($h$) endogenously adjust to discrepancies between actual and normal utilization rates ($u$ and $u_N$, respectively). 
For this mechanism to take place, the adjustment parameter ($\gamma_u$) must be sufficiently small and non-negative[fn:: The size of this parameter guards a fundamental relation to the stability of the model, as shown by textcite:freitas_growth_2015.]. 
As a consequence, productive capacity gradually adjusts to effective demand.

#+begin_export latex
\begin{equation}
\label{_If}
    I_f = h_{t-1}\cdot Y
\end{equation}
\begin{equation}
\label{_h}
    \Delta h = h_{t-1}\cdot \gamma_u\cdot (u - u_N)
\end{equation}
\begin{equation}
    \Delta K_f = I_f
\end{equation}
#+end_export

Firms finance investment that exceeds undistributed profits by bank loans, paying an interest rate on it ($r_l$) charged by the banks.
We assume an elastic supply of credit for investment. 
Moreover, tables \ref{Matriz_Estoques} and \ref{Matriz_Fluxos} show firms net wealth ($NW_f$) and net financial balance ($NFW_f$) explicitly:

#+begin_export latex
\begin{equation}
\label{_Lf}
    \Delta L_f = I_f - FU
\end{equation}
\begin{equation}
    NFW_f = FU - I_f
\end{equation}
\begin{equation}
    NW_f = K_f - L_f
\end{equation}
\begin{equation}
\label{_rg}
r_g = \frac{(1-\omega)\cdot u}{v}
\end{equation}
\begin{equation}
\label{_rn}
r_n = r_g - r_l\cdot\frac{L_{f_{-1}}}{K_f}
\end{equation}
\begin{equation}
\myRed{r_n = r_g - r_l\cdot\left(\ell - \frac{NFW_f}{K_{f}})}
\end{equation}
#+end_export
where $r_g$ and $r_n$ denotes gross and net profit rate respectively \myRed{while $\ell$ denotes firms' loans to capital stock ratio}.

** Banks

As in most part of SFC literature, banks do not have an active role in this model.
They create money as credit is demanded and just after they collect deposits cite:le_bourva_money_1992. 
Firms finance part of their investment with credit ($L_f$) and capitalists households finance all their residential investment by mortgages ($MO$), as already mentioned.
For simplicity, we assume null bank spreads ($\sigma_{mo} = \sigma_l = 0$) so interest rate on mortgages ($r_{mo}$) and on loans ($r_{l}$)
are the same as on deposits ($r_{m}$) which is  exogenously determined by banks.
Banks net balances ($NFW_b$) are defined by interests received net of interests payments. 
As those interests are the same, banks net wealth is necessarily zero (see table \ref{Matriz_Estoques}) and deposits are residuum:

#+begin_export latex
\begin{equation}
L = L_f
\end{equation}
\begin{equation}
    r_l = (1+\sigma_l)\cdot r_m
\end{equation}
\begin{equation}
    r_{mo} = (1+\sigma_{mo})\cdot r_m
\end{equation}
\begin{equation}
    r_m = \overline r_m
\end{equation}
\begin{equation}
    NFW_b = r_{mo}\cdot MO_{-1} + r_l\cdot L_{-1} - r_m\cdot M_{-1}
\end{equation}
$$
NFW_b = \Delta MO + \Delta L - \Delta M
$$
\begin{equation}
    NW_b = V_b \equiv 0
\end{equation}
\begin{equation}
\label{_M}
    \Delta M = \Delta L + \Delta MO
\end{equation}
#+end_export

** Households

*** Workers

As mentioned before, we assume that workers expend ($C_w$) what they earn ($W$). 
For simplicity, we consider that wages are the only source of workers' disposable income ($YD_{w}$) and do not have access to consumption loans, so worker' saving ($S_{hw}$) are null.
Therefore, accordingly to our hypothesis, workers do not hold both net financial ($NFW_{w}$) nor total wealth ($V_{w}$).

#+begin_export latex
\begin{equation}
C_w = W
\end{equation}
% \begin{equation}
% YD_w = W
% \end{equation}
% \begin{equation}
% S_{w} = YD_w - C_w
% \end{equation}
% $$
% S_{w} = 0
% $$
% \begin{equation}
% NFW_{w} = S_{w} = 0
% \end{equation}
% \begin{equation}
% V_{w} = 0
% \end{equation}
#+end_export

*** Capitalists

This is the most complex institutional sector of our model. 
We assume \myRed{that} consumption ($C_k$) \myRed{depends on disposable income ($YD_k$) which is the sum of distributed profits and received interests on deposits, net of interests payments on mortgages}.
Capitalists savings ($S_{k}$) are disposable income net of consumption.
At odds with SFC literature, savings are not equal to net balance ($NFW_{k}$, Equation ref:NFWh) since we have included residential investment.

#+begin_export latex
\begin{equation}
\label{_Ck}
\Delta L_{k} = C_{k}
% C_k = \alpha_{k}\cdot YD_{k}
\end{equation}
\begin{equation}
    \label{EqYD}
    YD_k = FD + \overline r_m\cdot M_{-1} - r_{mo}\cdot MO_{-1}
\end{equation}
\begin{equation}
    \label{EqSh}
    S_{k} = YD_k - C_k
\end{equation}
\begin{equation}
\label{NFWh}
    NFW_{k} = S_{k} - I_h
\end{equation}
#+end_export
# \myRed{in which, $\alpha_{k}$ is the capitalists' marginal propensity to consume out of disposable income.}
As mentioned before, capitalist households are the only institutional sector investing in houses which are financed by mortgages as in equation ref:EqMO.
# Thus, capitalists' total debt stock ($D$) is the sum of mortgage and consumption loans (Equation ref:k_D)

#+BEGIN_EXPORT latex
  \begin{equation}
    \label{EqMO}
    \Delta MO = I_h
  \end{equation}
  % \begin{equation}
  %   \label{k_D}
  %   D =  MO + L_k
  % \end{equation}
#+END_EXPORT



Next, we present residential investment growth rate ($g_{I_h}$) as determined by houses own rate of interest ($own$, equation \ref{_own}) as introduced by textcite:teixeira_crescimento_2015 and discussed in section ref:sec:empirical.


#+begin_export latex
\begin{equation}
	I_h = (1 + g_{I_h})\cdot I_{h_{-1}}
\end{equation}
\begin{equation}
	\label{g_Z_own}
	g_{I_h} = \phi_0 - \phi_1\cdot own
\end{equation}
#+end_export

where  $\phi_0$ represents long-term determinants of residential investment (/e.g./ demographic factors, housing and credit policies, etc.)[fn::For an early discussion about long-term determinants of residential investment see textcite:grebler_capital_1956. For a historical-institutional discussing of mortgage markets, see textcite:green_american_2005.] while $\phi_1$ captures houses own rate of interest as described in Section ref:sec_own.

Accordingly to our hypothesis, nominal ($V_{nk}$) and real net wealth ($V_{k}$) are distinguished only by the inclusion of house price ($p_h$) and are defined as follows:

#+begin_export latex
\begin{equation}
V_{k} = K_{hd} + M - MO
\end{equation}
\begin{equation}
V_{nk} = K_{hd}\cdot p_h + M - MO
\end{equation}
#+end_export


Finally,  we can describe NCC autonomous expenditure growth rate as follows:
#+begin_export latex
\begin{equation}
\label{g_Z}
g_{Z} = g_{I_{h}} = \phi_{0} - \phi_{1}\cdot own
\end{equation}
#+end_export


In this section, we presented a fully-specified parsimonious model to connect house bubbles with aggregate demand.
In the next Section, we analyze the dynamics from short- to long-run equilibria.
