#+TITLE: Long-run effective demand and residential investment: a Sraffian supermultiplier based analysis
#+AUTHOR: Gabriel Petrini, Lucas Teixeira
#+EMAIL: gpetrinidasilveira@gmail.com, lucas.teixeira@unicamp.br
#+OPTIONS: toc:nil
#+LATEX_HEADER: \addbibresource{refs.bib}
#+LATEX_HEADER: \usepackage{svg, caption, multirow}
#+LATEX_HEADER: \usepackage[english]{babel}

#+BEGIN_abstract
In this paper, we build a fully specified parsimonious Sraffian supermultiplier stock-flow consistent model (SSM-SFC) with two non-capacity creating autonomous expenditure: residential investment and debt-financed consumption.
Our model represents a closed and without government economy with workers and capitalist households and only the latter are not not credit constrained.
The introduction of residential investment implies that our SSM-SFC model has two real assets: firms' productive capital and households' real estate.
The numerical simulation experiments report the main standard Sraffian supermultiplier growth models results: 
    (i) income distribution affects growth rate only during the traverse;
    (ii) autonomous expenditures alone affects long-term growth rate and;
    (iii)  utilization rate moves towards the normal one.
As a particular result, an increase of residential investment growth rate increase implies a decrease of real estate share in total real assets.
Therefore, this model introduces both housing and asset bubbles	on Sraffian supermultiplier agenda and extends the range of autonomous expenditures alternatives.
	
#+LATEX: \noindent \textbf{Keywords:} Residential Investment; Sraffian supermultiplier; Asset bubble;  Stock-Flow Consistent approach.
#+END_abstract


* General TODOs                                                    :noexport:

** DONE [#B] Corrigir referências das seções
   CLOSED: [2020-08-03 seg 12:07]
 
   Deve-se ter um espaço depois do comando latex
** TODO [#B] Padronizar: Housing, Residential Investiment
   - [ ] Residential investment


* Introduction
#+LATEX: \label{sec:introduction}
#+INCLUDE: "Introduction.org"



* Empirical Motivation
#+LATEX: \label{sec:empirical}
#+INCLUDE: "Empirical.org"


* The absence of residential investment in demand-led growth models
#+LATEX: \label{sec:Review}
#+INCLUDE: "Review.org"


* A Sraffian supermultiplier SFC model with residential investment
#+LATEX: \label{sec:Model}
#+INCLUDE: "Model.org"



* Short and long-run equilibria
#+LATEX: \label{sec:runs}
#+INCLUDE: "Analytical.org"


* Numerical Simulations
#+LATEX: \label{sec:Experiments}
#+INCLUDE: "Simulation.org"



* Concluding Remarks
#+LATEX: \label{sec:Conclusion}
#+INCLUDE: "Conclusion.org"


* Acknowledgments
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+LATEX: \noindent We  are  grateful  to  Lídia  Brochier,  Carolina  Baltar,  Franklin  Serrano  for  discussions,  as  well  as  comments  by  the participants of Cecon/Unicamp and UFRJ Political Economy research seminars and the participants of XII AKB meeting, 20th FMM forum, and 46th EEA Annual Conference. Any remaining errors are, of course, our own.

* Disclosure statement
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
No potential conflict of interest was reported by the authors.

* References
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+LaTeX: \printbibliography[heading=none]


#+Latex: \appendix

* Analytical TODOs                                                 :noexport:

* Analytical Solution
#+LATEX: \label{append:Solution}


In this appendix, we present both analytical solution of our model and some relations between variables and parameters.
To do so, some equations will be turned into their continuous time equivalent to express it in terms of partial derivatives[fn:Script_Sol].
In our no-government closed economic system, real output growth rate is defined by:

[fn:Script_Sol] Script is available under request. The experiments in Section \ref{sec:Experiments} are simulated in discrete time.


\begin{equation}
\label{gLP}
    g = g\cdot \omega + \dot h + g\cdot h + g_Z\cdot \frac{Z}{Y}
\end{equation}
and (endogenous) fully-adjusted position marginal propensity to invest will be:
\begin{equation}
\label{hLP}
h^{\star} = g_Z\frac{\overline v}{u_N}
\end{equation}

Next, replacing equation \ref{gLP} in \ref{hLP} and \ref{_u} in order to build a bi-dimensional system of equation


\begin{cases}
\dot u = \left(\frac{\dot h}{1 - \omega - h} + g_z - \frac{h_t u_t}{v}\right) u_t\\
\dot h = \gamma_{u} \left(- u_N + u_t\right) h_t
\end{cases}

and assess its stability condition (evaluated at the equilibrium point):

$$
J = 
\left[\begin{matrix}
\frac{\partial \dot h}{\partial h} & \frac{\partial \dot h}{\partial u}\\
\frac{\partial \dot u}{\partial h} & \frac{\partial \dot u}{\partial u}
\end{matrix}\right]
$$

\begin{equation}
J = 
\label{Jacobiano}
\left[\begin{matrix}0 & \frac{g_Z \gamma_{u} v}{u_N}\\- \frac{u_N^{2}}{v} & - g_Z\end{matrix}\right]
\end{equation}

As \textcite{gandolfo_economic_2010} demonstrates, a positive determinant and a negative trace are both necessary and sufficient stability condition for a bi-dimensional system of differential equation:

$$
Det(J) = g_Z \gamma_{u} u_N > 0
$$

$$
Tr(J) = -g_Z < 0
$$
As both $\gamma_u$ and $u_N$ are strictly positive values, we just need to check positive trace condition.
Differently from textcite:freitas_growth_2015, we do not assume this condition initially.
Thus, our system is stable (near the fully-adjusted position) only if houses own interest rate (Equation ref:g_Z_own) meets the following inequality:
$$
g_{I_h} = g_Z = \phi_0 - \phi_1\cdot own > 0
$$
\begin{equation}
own < \frac{\phi_0}{\phi_1}
\end{equation}


Next, we show that houses share on total capital stock depends positively on deposits interest rate (Eq. \ref{partial_rm}) and negatively both on autonomous component of residential investment growth rate (equation \ref{partial_phi0}), real estate inflation (equation \ref{partial_pi}) and wage-share (equation \ref{partial_omega}):
\begin{equation}
%TODO Checar solução analítica
\label{partial_rm}
\frac{\partial k}{\partial rm} = - \frac{\phi_{1} v \left(\sigma_{mo} + 1\right)}{u_N \left(\pi + 1\right) \left(\omega - 1\right)} > 0
\end{equation}
\begin{equation}
\label{partial_phi0}
\frac{\partial k}{\partial \phi_0} = \frac{v}{u_N \left(\omega - 1\right)} < 0
\end{equation}
\begin{equation}
\label{partial_pi}
\frac{\partial k}{\partial \pi} = \frac{\phi_{1} v \left(rm\cdot(1+\sigma_{mo}) + 1\right)}{u_N \left(\pi + 1\right)^{2} \left(\omega - 1\right)} < 0
\end{equation}
\begin{equation}
\label{partial_omega}
\frac{\partial k}{\partial \omega} = - \frac{v \left(\phi_{0} \left(\pi + 1\right) - \phi_{1} \left(- \pi + rm\cdot(1 + \sigma_{mo})\right)\right)}{u_N \left(\pi + 1\right) \left(\omega - 1\right)^{2}} < 0
\end{equation}


Since capitalists' loans and mortgage to house ratios ($\ell^{\star}_{k}$ and $mo^{\star}$, respectively) depend only on parameters not analyzed on our experiments, we repeat this  procedure to firms' loans to capacity generating capital stock ($\ell^{\star}_f$):


#+BEGIN_SRC ipython :tangle ./codes/Solution.py :async t :session Solution :results verbatim drawer :exports results
from sympy.simplify.radsimp import collect_const
dicts = {
g_: "g^\star",
    k_: "k^\star",
    un : "u^{\star}",
    infla: '\pi'
               }


new_own = sp.Function('own')(rm,infla)

def printer(symbol, equation, var, replace_g = True):

    num = '\\frac{\partial ' + symbol + '^{\star}}'
    
    if replace_g == True:
        express = equation.subs(g_, g_Z).subs(_own(t), own).subs(_rmo(t), rm)
    else:
        express = equation.factor().cancel()

    result = sp.Derivative(express,  var).doit()    
    result = result.cancel().expand().cancel().factor()
    result = sp.factor(result.simplify())
    result = collect_const(result)
    #result = result.collect(1+rm).collect(phi_0).collect(phi_1).collect(1+infla).collect(1-omega).collect(un).collect(gamma_F).collect(R)
    #result = result.collect(v).collect(phi_0).collect(phi_1).subs(phi_0 - phi_1*((1+rm)/(1+infla) - 1), g_)
    #result = sp.factor(result.simplify().cancel())
    numerical = replacer(result)

    if numerical > 0:
        numerical = '> 0'
    elif numerical == 0:
        numerical = '= 0'
    else:
        numerical = '< 0'
    
    print(
            sp.latex(
                num + '{\partial ' + f"{sp.latex(var, symbol_names = dicts)}" + '} = ' + f"{sp.latex(result, symbol_names = dicts)}"  + f" {numerical}",
                mul_symbol = 'dot',
                symbol_names = dicts,
                mode = 'equation'
            )
        )
#+END_SRC

#+RESULTS:
:results:
2 - 1f19708b-7460-47b9-a5d3-9c2d83e1522a <output> <interrupt>
:end:

#+BEGIN_SRC ipython :tangle ./codes/Solution.py :async t :session Solution :results verbatim drawer :exports results
printer(symbol =  '\ell_{f}', equation = lfstar, var = rm)
printer(symbol =  '\ell_{f}', equation = lfstar, var = phi_0)
printer(symbol =  '\ell_{f}', equation = lfstar, var = infla)
printer(symbol =  '\ell_{f}', equation = lfstar, var = omega, replace_g = False)
#+END_SRC

#+RESULTS:
:results:
1 - 453c6f1d-a870-42db-be58-b238cfac88dc <output> <interrupt>
:end:

and mortgage to total capital stock ratio ($m^{\star}$):

#+BEGIN_SRC ipython :tangle ./codes/Solution.py :async t :session Solution :results verbatim drawer :exports results
printer(symbol =  'm', equation = m, var = rm)
printer(symbol =  'm', equation = m, var = phi_0)
printer(symbol =  'm', equation = m, var = infla)
printer(symbol =  'm', equation = m, var = omega, replace_g = False)
#+END_SRC

#+RESULTS:
:results:
2 - e16d543e-36f7-48e9-b5d9-32a986ee534c <output> <interrupt>
:end:




* Numerical Appendix
 #+LATEX: \label{append:Data}

#+BEGIN_SRC latex
\begin{table}[H]
\caption{Parameters of variables}
\centering
\label{tab:param}
\input{./tabs/parameters.tex}
\caption*{\textbf{Source:} Authors' elaboration}
\end{table}
#+END_SRC

#+RESULTS:
#+begin_export latex
\begin{table}[H]
\caption{Parameters of variables}
\centering
\label{tab:param}
\input{./tabs/parameters.tex}
\caption*{\textbf{Source:} Authors' elaboration}
\end{table}
#+end_export


#+BEGIN_SRC ipython :tangle ./codes/Sobol.py :async t :session Sobol :results verbatim drawer :exports results
#!pip install pysolve3
import sys

sys.path.insert(1, './codes/')
from SFC_Setup import *

base = model()
df = SolveSFC(base, time=1000)

parameters = [
    'gamma_u',
    'omega',
    'gamma_F',
    'alpha',
    'spread_mo',
    'phi_0',
    'phi_1',
    'infla',
    'R',
]
#+END_SRC

#+RESULTS:
:results:
# Out [44]: 
:end:


#+BEGIN_SRC ipython  :tangle ./codes/Sobol.py :async t :session Sobol :results verbatim drawer :exports results
def sensibility(
    parameters,
    bound = np.linspace(0,1,101),
    time = 10,
    skip = 10,
    var = "u"
):
    bound = bound
    df = pd.DataFrame()
    empty_list = [i for i in range(len(bound))]  
    report_dict = {}
    
    for param in parameters:
        for i in range(len(bound)):
            base = model()
            base.set_values({param:bound[i]})
            try:
                empty_list[i] = np.log(SolveSFC(base,time=time+skip)[var][skip:].std())
            except Exception as e:
                empty_list[i] = np.nan
                pass
        df[param] = empty_list ################### Replace here
############################### End #####################################################
    df.index = bound
    
    return df
#+END_SRC

#+RESULTS:
:results:
# Out [45]: 
:end:


#+BEGIN_SRC ipython  :tangle ./codes/Sobol.py :async t :session Sobol :results verbatim drawer :exports none
df = sensibility(time=400, parameters=parameters)

report = pd.DataFrame(
    {parameter : df[parameter].dropna().index[-1] for parameter in df.columns},
    index=[0]
    )
#report.columns = [sp.Symbol(i) for i in report.columns] # Turn into latex
print(df)
report
#+END_SRC

#+RESULTS:
:results:
# Out [46]: 
# output
       gamma_u     omega   gamma_F     alpha  spread_mo     phi_0     phi_1  \
0.00 -2.530464 -2.087674 -2.698257 -2.087646  -2.698247 -3.018613 -2.691682   
0.01 -2.711678 -2.095959 -2.698256 -2.095936  -2.698288 -1.967421 -2.692559   
0.02 -2.694301 -2.104348 -2.698260 -2.104328  -2.698331 -2.635810 -2.693389   
0.03 -2.709234 -2.112844 -2.698255 -2.112824  -2.698374 -2.627593 -2.694172   
0.04 -2.718127 -2.121447 -2.698251 -2.121426  -2.698412 -2.389913 -2.694906   
...        ...       ...       ...       ...        ...       ...       ...   
0.96       NaN -3.816070 -2.698230 -3.815963  -2.699445       NaN -2.470601   
0.97       NaN -3.785307 -2.698232 -3.785165  -2.699429       NaN -2.464600   
0.98       NaN -3.749482 -2.698234 -3.749338  -2.699412       NaN -2.458528   
0.99       NaN -3.709475 -2.698236 -3.709410  -2.699395       NaN -2.452386   
1.00       NaN -3.666369 -2.698235 -3.666278  -2.699377       NaN -2.446172   

         infla         R  
0.00 -2.698247 -1.092702  
0.01 -2.691682 -1.100112  
0.02 -2.680788 -1.107645  
0.03 -2.666582 -1.115304  
0.04 -2.649931 -1.123094  
...        ...       ...  
0.96 -1.831873       NaN  
0.97 -1.829003       NaN  
0.98 -1.826174       NaN  
0.99 -1.823388       NaN  
1.00 -1.820641       NaN  

[101 rows x 9 columns]

# text/plain
:    gamma_u  omega  gamma_F  alpha  spread_mo  phi_0  phi_1  infla     R
: 0     0.65    1.0      1.0    1.0        1.0   0.32    1.0    1.0  0.91

[[file:/tmp/ob-ipython-htmlHHlPzz.html]]
:end:

#+BEGIN_SRC ipython  :tangle ./codes/Sobol.py :async t :session Sobol :results verbatim drawer :exports results
results = report.copy()
df_ = df.copy()
long_string = "Value that induces instability"
results["Value"] = [long_string]
results.set_index("Value", inplace=True)
results.index.name = 'Parameter'
results = results.transpose().copy()
results["Effect of increase on stability"] = df.diff().median() >= 0
translate = {
    True: "Destabilizing",
    False: "Stabilizing"
}
results["Effect of increase on stability"] = results["Effect of increase on stability"].map(translate)

for i in range(len(results[long_string])):
    val = results[long_string][i]
    if val >= 1.0:
        results[long_string].iloc[i] = "Does not induces instability"

latex = {
    "gamma_u": "$\gamma_u$", "omega": "\omega", "gamma_F" : "$\gamma_F$",
    "phi_0" : "$\phi_0", "phi_1" : "$\phi_1$",
    "infla" : "$\pi$", "spread_mo" : "$\sigma_{mo}$", "alpha" : "$\\alpha$",
    "R" : "$R$",
}
results["Description"] = [i for i in results.index]
desc = {
    "gamma_u": "Adjustment speed",
    "omega": "wage-share",
    "gamma_F" : "Profit distribution policy",
    "phi_0" : "$g_{I_Z}$ autonomous component",
    "phi_1" : "own interest rate parameter",
    "infla" : "real estate inflation",
    "spread_mo" : "Mortgage spread",
    "alpha" : "Marginal propensity to consume",
    "R" : "Autonomous consumption share on $Z$",
}
results["Description"] = results["Description"].map(desc)
results["Parameter"] = results.index.map(latex)
results.set_index("Parameter", inplace=True)
results.index.name = ''
results  = results[[ # Reorder columns
    "Description",
    long_string,
    "Effect of increase on stability"
]]
print(results.to_latex(
    caption = "Effect of individual parameters on model stability",
    label = "tab:sensibility",
    escape = False,
))
#+END_SRC

#+RESULTS:
:results:
# Out [108]: 
# output
\begin{table}
\centering
\caption{Effect of individual parameters on model stability}
\label{tab:sensibility}
\begin{tabular}{llll}
\toprule
Parameter &                          Description & Value that induces instability & Effect of increase on stability \\
              &                                      &                                &                                 \\
\midrule
$\gamma_u$    &                     Adjustment speed &                           0.65 &                   Destabilizing \\
\omega        &                           wage-share &   Does not induces instability &                     Stabilizing \\
$\gamma_F$    &           Profit distribution policy &   Does not induces instability &                   Destabilizing \\
$\alpha$      &       Marginal propensity to consume &   Does not induces instability &                     Stabilizing \\
$\sigma_{mo}$ &                      Mortgage spread &   Does not induces instability &                     Stabilizing \\
$\phi_0       &       $g_{I_Z}$ autonomous component &                           0.32 &                   Destabilizing \\
$\phi_1$      &          own interest rate parameter &   Does not induces instability &                   Destabilizing \\
$\pi$         &                real estate inflation &   Does not induces instability &                   Destabilizing \\
$R$           &  Autonomous consumption share on $Z$ &                           0.91 &                     Stabilizing \\
\bottomrule
\end{tabular}
\end{table}


:end:


#+BEGIN_SRC ipython  :tangle ./codes/Sobol.py :async t :session Sobol :results verbatim drawer :exports results

#+END_SRC

* Particular experiments results                                   :noexport:
#+LATEX: \label{append:Single}


#+RESULTS:
#+begin_export latex
\begin{figure}[H]
    \centering
    \caption{Wage-share decrease}
    \label{fig:shock_2}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_2}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Wage-share decrease}
    \label{fig:shock_2norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_2Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Real estate inflation increase}
    \label{fig:shock_4}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_4}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Real estate inflation increase}
    \label{fig:shock_4norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_4Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Interest rate increase}
    \label{fig:shock_3}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_3}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Interest rate increase}
    \label{fig:shock_3norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_3Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}
#+end_export

#+BEGIN_SRC latex
\begin{figure}[H]
    \centering
    \caption{Wage-share decrease}
    \label{fig:shock_2}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_2}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Wage-share decrease}
    \label{fig:shock_2norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_2Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Real estate inflation increase}
    \label{fig:shock_4}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_4}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Real estate inflation increase}
    \label{fig:shock_4norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_4Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Interest rate increase}
    \label{fig:shock_3}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_3}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Interest rate increase}
    \label{fig:shock_3norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_3Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}
#+END_SRC

#+RESULTS:
#+begin_export latex
\begin{figure}[H]
    \centering
    \caption{Wage-share decrease}
    \label{fig:shock_2}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_2}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Wage-share decrease}
    \label{fig:shock_2norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_2Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Real estate inflation increase}
    \label{fig:shock_4}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_4}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Real estate inflation increase}
    \label{fig:shock_4norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_4Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Interest rate increase}
    \label{fig:shock_3}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_3}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}

\begin{figure}[H]
    \centering
    \caption{Interest rate increase}
    \label{fig:shock_3norm}
    \includegraphics[width=\textwidth, height=.4\textheight]{./figs/Shock_3Norms}
    \caption*{\textbf{Source:} Authors Elaboration}
\end{figure}
#+end_export
