#+LATEX_CLASS: article
#+TITLE: Resenha 12 - Ostrom, NEI e Economia Ecológica
#+SUBTITLE: Nova Economia Institucional
#+LATEX_COMPILER: pdflatex
#+AUTHOR: Gabriel Petrini da Silveira
#+DATE: 26 de Junho de 2020
#+EMAIL: gpetrinidasilvera@gmail.com
#+COLUMNS: 2
* Ostrom (2009): A polycentric approach for coping with Climate Change

** O desafio da mudança climática

A autora abre a discussão mencionando que outros pesquisadores tem associado o sucesso da contenção da mudaça climática não poderia vir de um único país.
Não apenas isso, mas também que se apenas um país tentasse, seria um esforço em vão.

** Deveríamos esperar por uma solução a nível global?

No entanto, Ostrom também destaca que a espera por uma solução a nível global também pode ser problemática.
Outras discussões correlatas dizem respeito aos responsáveis pelo aumento da poluição, bem como pelo acerto de contas das soluções.
Além disso, mesmo que uma solução global surja, nada garante que irá funcionar.
Dentre as formas de avaliar tais problemas, a perspectiva dos bens comuns é a mais frequente dentre as abordagne dos dilemas da ação coletiva.


Em seguida, destaca que a teoria clássica da ação coletiva prevê que o agente (a nível individual) não irá alterar seu comportamente ao menos que uma autoridade coercitiva gere incentivos para tal ação.
Sendo assim, alguns analistas propõem soluções a nível global dada esta teoria da inação coletiva.

** Teoria Convencional da Ação Coletiva

A autora abre a seção destacando que o temor "dilema social" surge das configurações em que as ações não-coordenadas gera resultados sub-ótimos para os agentes no longo-prazo.
Desse modo, o resultado ótimo a nível social seria aquele que envolvesse cooperação por meio de estratégias que são diferentes do Equilíbrio de Nash.
Dentre os problemas associados à inação coletiva, destaca-se que os custos são concentrados enquanto os benefícios são difusos.
Além disso, se muitos agentes atuam como "caronistas", os demais podem decidir não contribuir para o bem coletivo.
Resumidamente, a teoria convencional da ação coletiva conclui que, na ausência de externalidades, é impossível obter uma ação coletiva.
Como consequência, tal teoria não explica a emergência de grupos auto-organizados  com o propósito de obter o bem coletivo.
Além disso, Ostrom também destaca que esta abordagem não possui respaldo empírico para dilemas sociais a nível pequeno e médio.

** A falta de respaldo empírico na teoria convencional da ação coletiva

Dentre os resultados empíricos desta agenda, destaca-se a ausência de respaldo da teoria convencional da ação coletiva.
Enquanto os estudos apresentam a presença de "caronistas" em várias pesquisas, um número grande de indivíduos que enfrentam dilemas coletivos cooperam.
Em especial, reporta-se cooperação quando os agentes confiam nos demais.
Dito isso, se faz necessário modificar o escopo teórico para algum que possual respaldo empírico.

** Atualizando a teoria da ação coletiva relacionada às mudanças climáticas  

A autora destaca que o contexto de confiança e reciprocidade é fundamental para a solução de problemas de dilema social.
Sendo assim, se faz necessário alterar os microfundamentos comportamentais em que os agentes aprendem e obtenham informação na medida que se relacionam com os demais.
Dentre as configurações que apresentam um elevado (e permanente) grau de cooperação são aquelas em que os agentes envolvidos tem a capacidade de ganhar confiança e reciprocidade com os demais.
Os seguintes elementos explicam tais configurações:

1. Disponibilidade de informações confiáveis sobre os custos e benefícios da ação
2. Os indivíduos envolvidos concebem que os recursos envolvidos são relevantes em um horizonte de longo-prazo
3. Ganhos de reputação e reciprocidade são relevantes para os agentes envolvidos
4. Agentes podem se comunicar com ao menos algumas partes
5. Monitoramento informal e factível e considerado apropriado
6. Existe liderança social relacionada com a capacidade de resolver outros problemas correlatos

Neste ponto, vale resaltar que os problemas da ação coletiva não desaparecem na presença de um externalidade do governo uma vez que estas políticas dependem do desejo de cooperação deste agentes.

** Existem apenas benefício globlais gerados pela redução da emissão dos gases causadores do efeito-estufa? 
   
Nesta seção, a autora apresenta alguns exemplos de medidas tomadas para conter a mudança climática.
Dentre elas, destaca-se o aumento de impostos sobre consumo de energia uma vez que altera-se os preços relativos e, portanto, os incentivos de consumo das famílias.
No entanto, ela reporta que discussões locais sobre os custos, impactos e benefícios são relevantes para gerar mudanças no comportamento individual.
Além disso, algumas dessas decisões podem reduzir os custos das políticas adotadas pelo governo.
Outro problema é que a questão ambiental tem sido tratada como um problema global, logo, ações individuais passam a ser vistas como pouco eficazes.

** Quais medidas estão sendo tomadas para reduzir a emissão de gases de efeito-estufa?

Nesta seção, a autora explicita algumas ações a nível local, estadual e entre países da União Europeia. 
O importante a se destacar é que os agentes que partiparam destas ações se reconhecem que são fonte tanto de emissores quanto fonte de mudança.
 
** As ações a nível global são a melhor forma de gerar ação coletiva?

A autora pontua que antes de seguir para uma defesa das ações a nível global, deve-se levar em consideração que tais iniciativas também possuem custos de eleboração e transação elevados.
Dito isso, apresenta alguns contrafactuais em que tal ação global não teve êxito (pescaria).
Além disso, também destaca que a precificação do insucesso e das mudanças também é um resultado indesejado.
No entanto, isso não implica na irrelevância de tais iniciativas, mas principalmente que se deve dar mais atenção as mudanças a nível local.

** Existem muitos agentes trabalhando sobre mudanças climática?

Nessa seção, a autora apresenta algumas críticas que tocam a questão do aumento dos projetos que tentam lidar com muda climáticas que tornariam o sistema caótico.
De modo geral, a presença dessas iniciativas reflete a ineficácia de projetos a nível global.
Associa isso ao fato que a redução da emissão dos gases do efeito-estufa também não se restringem no nível internacional.
Dito isso, a autora discute alguns problemas associados a tais projetos.

*** Vazamentos
Em linhas gerais, tais vazamentos podem ser definidos como delocamento de uma atividade da região $X$ para $Y$ por conta de adoção de medidas pró-redução de emissões na região $X$.
O vazamento de mercado, por sua vez, se refere à mudanças nos preços relativos de modo que a produção de bens mais poluentes se torna mais rentável, estimulando assim sua produção.

*** Políticas inconsistentes
Um exemplo de uma política inconsistente é a produção de novas tecnologicas que podem reduzir a emissão no futuro, mas cujo processo de elaboração e produção inicial são bastante poluentes de modo que tal atividade não é desempenhada.

*** Caronistas
Autoexplicativo.

*** Certificação inadequada
Aqui, a autora faz menção às consultorias prestadas por pessoas não tão bem certificadas que induzem a perpetuação de atividades mais poluidores.
Tal movimento está associado a tentativa de usufruir lucro a partir do maior interesse em tais serviços.

*** Quais são as lições

Nesta seção, a autora retoma alguns temas já tratados

1. Necessidade de se reconhecer a complexidade dos determinantes da mudança climática
2. Necessidade de adquirir conhecimento sobre suas causas e efeitos para agir rapidamente
3. Reconhecer a existência de uma variadade de medidas que podem reduzir a emissão de poluentes, mas que podem incentivar comportamentos oportunistas
4. Todas as políticas adotadas estão sujeitas a erros, mas apenas a tentativa e erro permitem evitá-los

** Uma abordagem policêntrica do problema


Ostrom inicia esta seção indicando as origens da abordagem policêntrica em que, inicialmente, o setor público é tratado como um sistema policêntrico invés de hierarquia monocêntrica.
Em seguida, explicita as hipóteses dessa abordagem.

1. Os bens e serviços públicos se diferem bastante em relação às suas funções de produção e efeitos de escala
2. As preferências de políticas tendem a ser mais homogêneas em unidades menores se comparadas com toda uma região metropolitana
3. Cidadãos que vivem em áreas atendidas com múltiplas jurisdições tendem a aprender mais sobre sua performace por meio do contato com as formas que tais problemas são resolvidos nas demais
4. A presença de um grande número de produtores potenciais de uma mesma região metropolitana permitem que os oficiais eleitos façam escolhas mais associadas aos produtores
5. Multiplas jurisdições com diferentes escopos e escalas de organização permitem que os cidadãos e oficiais tenham mais escolhas para selecionar o modelo de provisão dos bens públicos e tentam utilizar a melhor tecnologia disponível
6. Produtores que precisam competir por contratos são mais inclinados a pesquisar por tecnologias mais inovadoras

De modo geral, a ideia é que centrar a recomendação em uma única unidade global deve ser repensada e deve reconhecer a importância das ações de menor escala.
Além disso, estudos empíricos tem reportado a relevância da confiança reciprocidade dentre as ações coletivas exitosas.
Se apenas uma ação é adotada a nível global, é mais difícil aumentar o nível de confiança e reciprocidade dos agentes.

*** Diversas estratégias de monitoramento

As questões de monitoramento são bastante importantes quando se trata de situações em que os agentes nunca se depararam de modo que a execução se torna relevante.
Em seguida, a autora pontua a falta de consenso na literatura a respeito dos mecanismos de monitoramento.
Argumenta que o monitoramento local está entre as variáveis mais relevantes para explicar o sucesso de ações coletivas.
Encerra a seção apresentando alguns exemplos.

*** Sistemas complexos, multi-nível para lidar com problemas complexos, multi-nível

De modo geral, a autora pontua que é difícil de se esperar que soluções policêntricas sejam elaboradas em um futuro próximo.
No entanto, alternativas multi-nível são um avanço uma vez que qualquer redução de emissão se faz necessária.
A vantagem da abordagem policêntrica é que enfatiza a importância de tentativas multi-nível.

* Ostrom (2010): Analizando a ação coletiva

** Introdução 

A autora inicia o artigo pontuando que os dilemas sociais são modeloados como jogos de bens públicos, de recursos comuns, de confiança ou de ultimato.
Segue destacando que se cada indivíduo toma decisões maximizadoras, os resultados a nível social podem não ser os melhores.
Uma vez que o resultado sub-ótimo é o equilíbrio, ninguém individualmente e voluntariamente mudaria sem comportamento em prol do bem comum.
Adiante, explicita as hipóteses comuns a esses modelos.
Chama atenção para alguns resultados da literatura em que se um agente não segue o comportamento maximizador, é possível que outros agentes maximizadores adotem a estratégia cooperativa.
Além disso, argumenta que enquanto a literatura empírica tem encontrado envidências de que algumas configurações levam a soluções cooperativas, a questão é como que os agentes evitam o comportamento oportunista?

** Variáveis estruturais associadas às ações coletivas

*** Situações em que a repetição não é relevante

**** Número de participantes envolvidos

A autora pontua abordagens que enfatizam que a probabilidade de se adotar uma postura cooperativa se reduz na medida que o número de participantes aumenta.
Isso porque os benefícios são difusos enquanto os custos são concentrados.

**** Benefícios compartilhados 

Nesta seção, Ostrom discute se os benefícios são compartilhados completamente ou são subtraídos. 
Os bens que possuem benefícios substrativistas são denominados de recursos comuns.
Neste contexto, o aumento do número de participantes afeta negativamente a adoção de medidas cooperativas.

**** Heterogeneidade dos participantes

A literatura tem indicado que a heterogeneidade compromete a adoção de ações cooperativas.

**** Comunicação frente a frente

A autora destaca que a literatura reporta que decisões tomadas frente a frente tendem a ser mais cooperativas.

*** Situações em que a repetição é relevante 

**** Informação sobre o passado das interações

Em linhas gerais, as informações que os agentes possuem sobre as ações passadas são fundamentais para a ação cooperativista quando se trata de ações repetidas.
Quando as iterações são entre agentes com credibilidade e reciprocidade, a cooperação tende a aumentar ao longo do tempo.

**** Como os indivíduos são ligados

É mais provavél que ações coletivas sejam tomadas quando os agentes beneficiários destas ações são mais conectados.

**** Possibilidade de escolha de participação (entrada e saída)

Isso provê uma terceira escolha ao dilema social de modo que todos os agentes tem o poder de veto.

** Em direção a uma teoria mais geral do comportamento humano

Nesta seção, a autora discute os problemas da família de teorias da racionalidade substantiva.
Como alternativa, propõe que o contexto ao qual os agentes estão inseridos é mais relevante do que a racionalidade de seu comportamento.
Uma teoria comportamento mais geral trata os indivíduos como entidades adaptativas que tentam se sair melhor dadas as suas restrições.
Estes agentes são capazes de desenvolver ferramentas --- e isso inclui instituições --- para alterar seu meio.

*** Heurística e normas

De modo geral, os indivíduos tendem a seguir um comportamento heurístico a partir do que aprenderam ao longo do tempo e também aprendem por meio de normas sociais.
Argumenta que após se depararem com situações cooperativas que os beneficiam, os indivíduos tendem a adotar uma postura mais cooperativista.
Outra norma relevante é a percepção de justiva nas ações coletivas e quanto mais justa uma ação é vista, maior a chance de adotar uma ação coletiva.

*** Estratégias contingentes e normas de reciprocidade

Os indivíduos aprendem a usar a reciprocidade com base em suas experiênicas passadas.
Quanto mais benefícios receberam, maior a chance de tomar uma decisão coletiva.
Argumenta que existem várias estratégias que podem incentivar decisões coletivas.

*** Relações fundamentais: reputação, confiança e reciprocidade

Em situações em que os indivíduos podem ter maior reputação por usar reciprocidade ou sendo confiáveis, os demais podem aprender a confiar neles e começar a cooperar.
Quando iniciam a cooperação em repetição, os demais podem aprender a confiar neles e lever a maior cooperação.
Em linhas gerais, reputação por ser confiável, níveis de confiança e reciprocidade se reforçam positivamente.
Isso implica que a redução dessas variáveis pode gerar efeitos negativos sobre a cooperação.
** Agenda contemporânea: ligar variáveis estruturais com as fundamentais

Dito isso, a maior dificuldade recai em como conectar as variáveis estruturais mencionadas anteriormente com confiança, reciprocidade e reputação.
Partindo de uma teoria mais abrangente do comportamento humano, é possível incluir tais variáveis fundamentais.
No entanto, chama anteção para a impossibilidade de ligar todas essas variávies e uma única forma causal.
Além disso, pontua que uma agenda de pesquisa futura deve investigar em que medida as variáveis estruturais interagem entre si.
** Conclusões

O artigo pode ser resumido com a seguinte passagem:

#+BEGIN_QUOTE
A key lesson of research on collective-action theory is recognizing the complex linkages among variables at multiple levels that together affect individual reputations, trust, and reciprocity as these, in turn, affect levels of cooperation and joint benefits. Conducting empirical research on collective action is thus extremely
challenging.
#+END_QUOTE
